changelog:
    categories:
        - title: New Features
          labels:
              - feature
              - enhancement
        - title: Bug Fixes
          labels:
              - bug
              - fix
        - title: Infrastructure
          labels:
              - infra
              - ci
              - dependencies
        - title: Other Changes
          labels:
              - '*'
