export { default as BEAM_LOGO } from './beam-logo.jpeg'
export { default as BRUME_LOGO } from './brume-logo.png'
export { default as CLAVE_LOGO } from './clave-logo.jpeg'
export { default as ECO_LOGO } from './eco-logo.png'
export { default as KOFIME_LOGO } from './kofime-logo.png'
