export { default as HYPERSPHERE_LOGO } from './hypersphere-logo.png'
export { default as LONGHASH_LOGO } from './longhash-logo.png'
export { default as NAZARE_LOGO } from './nazare-logo.svg'
export { default as ZEEPRIME_LOGO } from './zeeprime-logo.png'
export { default as HYPERSPHERE_LOGO_SQUARE } from './hypersphere-logo-square.jpeg'
export { default as LONGHASH_LOGO_SQUARE } from './longhash-logo-square.jpeg'
export { default as NAZARE_LOGO_SQUARE } from './nazare-logo-square.jpg'
export { default as ZEEPRIME_LOGO_SQUARE } from './zeeprime-logo-square.png'
