import { existsSync } from 'node:fs'
import { resolve } from 'node:path'
import countryCurrencyMappings, { getFlagUrl } from '@/constants/countryCurrencyMapping'
import { countryData } from '@/components/AddMoney/consts'

// Guards the flag-asset pipeline. `public/flags/` is gitignored and
// regenerated by `scripts/copy-flags.mjs` (postinstall) from the
// `circle-flags` npm package. When a mapping `flagCode` doesn't resolve to a
// real SVG, the broken-image lands silently in production — which is exactly
// how the EUR → 'eu' regression (commit 67ff7348a, fixed in PR #1974) made it
// to main. This test fails loud at PR-CI time instead.
describe('flag asset coverage', () => {
    const publicFlagsDir = resolve(__dirname, '../../../public/flags')

    it.each(countryCurrencyMappings.map((m) => [m.currencyCode, m.flagCode]))(
        '%s → /flags/%s.svg exists in public/flags/',
        (_currency, flagCode) => {
            const path = resolve(publicFlagsDir, `${flagCode}.svg`)
            expect(existsSync(path)).toBe(true)
        }
    )

    it('xx.svg (UN fallback for null/undefined iso2) exists', () => {
        expect(existsSync(resolve(publicFlagsDir, 'xx.svg'))).toBe(true)
    })

    it('getFlagUrl(null) returns the xx.svg fallback', () => {
        expect(getFlagUrl(null)).toBe('/flags/xx.svg')
    })
})

// `path` is a URL segment: /add-money/{path} and /withdraw/{path} both resolve
// the country by an exact string match against countryData. Two ways that
// breaks, both of which shipped:
//   - a slug with a non-ASCII character ('saint-barthélemy') never matches the
//     percent-encoded segment the router hands back, so the page 404s;
//   - a slug in one table that no country in countryData carries
//     ('czech-republic' vs 'czechia') dead-ends the exchange-rate widget's
//     "Try it" redirect, which silently falls back to the region's stand-in
//     country (CZK landed on Germany).
// Both tables are hand-maintained, so guard them at CI time instead.
const URL_SAFE_SLUG = /^[a-z0-9-]+$/

describe('country path slugs', () => {
    const countries = countryData.filter((c) => c.type === 'country')

    it.each(countries.map((c) => [c.title, c.path]))('countryData %s → %s is a URL-safe slug', (_title, path) => {
        expect(path).toMatch(URL_SAFE_SLUG)
    })

    const mappedPaths = countryCurrencyMappings.filter((m) => m.path).map((m) => [m.currencyCode, m.path as string])

    it.each(mappedPaths)('countryCurrencyMapping %s → %s is a URL-safe slug', (_currency, path) => {
        expect(path).toMatch(URL_SAFE_SLUG)
    })

    it.each(mappedPaths)('countryCurrencyMapping %s → %s resolves to a country in countryData', (_currency, path) => {
        expect(countries.map((c) => c.path)).toContain(path)
    })
})
