import { existsSync } from 'node:fs'
import { resolve } from 'node:path'
import countryCurrencyMappings, { getFlagUrl } from '@/constants/countryCurrencyMapping'

// Guards the flag-asset pipeline. `public/flags/` is gitignored and
// regenerated by `scripts/copy-flags.mjs` (postinstall) from the
// `circle-flags` npm package. When a mapping `flagCode` doesn't resolve to a
// real SVG, the broken-image lands silently in production — which is exactly
// how the EUR → 'eu' regression (commit 67ff7348a, fixed in PR #1974) made it
// to main. This test fails loud at PR-CI time instead.
describe('flag asset coverage', () => {
    const publicFlagsDir = resolve(__dirname, '../../../public/flags')

    it.each(countryCurrencyMappings.map((m) => [m.currencyCode, m.flagCode]))(
        '%s → /flags/%s.svg exists in public/flags/',
        (_currency, flagCode) => {
            const path = resolve(publicFlagsDir, `${flagCode}.svg`)
            expect(existsSync(path)).toBe(true)
        }
    )

    it('xx.svg (UN fallback for null/undefined iso2) exists', () => {
        expect(existsSync(resolve(publicFlagsDir, 'xx.svg'))).toBe(true)
    })

    it('getFlagUrl(null) returns the xx.svg fallback', () => {
        expect(getFlagUrl(null)).toBe('/flags/xx.svg')
    })
})
