import { SOLANA_ICON, TRON_ICON } from '@/assets'
import { BINANCE_LOGO, LEMON_LOGO, RIPIO_LOGO } from '@/assets/exchanges'
import { METAMASK_LOGO, RAINBOW_LOGO } from '@/assets/wallets'
import { StaticImageData } from 'next/image'
import { DepositMethod } from '../components/DepositMethodList'

export interface CryptoSource {
    id: string
    name: string
    type: 'exchange' | 'wallet'
    icon?: StaticImageData
    isGeneric?: boolean
    path: string
}

export interface CryptoToken {
    id: string
    name: string
    symbol: string
    icon: StaticImageData | string
}

// @dev: this is a temporary list of tokens for the deposit screen, using this for a couple of weeks, once x-chain is ready, we will use the x-chain tokens and remove this list, only useful token is USDC here for now
export const DEPOSIT_CRYPTO_TOKENS: CryptoToken[] = [
    {
        id: 'usdc',
        name: 'USD Coin',
        symbol: 'USDC',
        icon: 'https://assets.coingecko.com/coins/images/6319/small/USD_Coin_icon.png',
    },
    {
        id: 'usdt',
        name: 'Tether',
        symbol: 'USDT',
        icon: 'https://assets.coingecko.com/coins/images/325/small/Tether-logo.png',
    },
    {
        id: 'eth',
        name: 'Ethereum',
        symbol: 'ETH',
        icon: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
    },
    {
        id: 'sol',
        name: 'Solana',
        symbol: 'SOL',
        icon: SOLANA_ICON,
    },
    {
        id: 'btc',
        name: 'Bitcoin',
        symbol: 'BTC',
        icon: 'https://assets.coingecko.com/coins/images/1/small/bitcoin.png',
    },
    {
        id: 'trx',
        name: 'Tron',
        symbol: 'TRX',
        icon: TRON_ICON,
    },
]

export const CRYPTO_EXCHANGES: CryptoSource[] = [
    {
        id: 'binance',
        name: 'Binance',
        type: 'exchange',
        icon: BINANCE_LOGO,
        path: '/add-money/crypto/binance',
    },
    {
        id: 'lemon',
        name: 'Lemon',
        type: 'exchange',
        icon: LEMON_LOGO,
        path: '/add-money/crypto/lemon',
    },
    {
        id: 'ripio',
        name: 'Ripio',
        type: 'exchange',
        icon: RIPIO_LOGO,
        path: '/add-money/crypto/ripio',
    },
    {
        id: 'other-exchanges',
        name: 'Other exchanges',
        type: 'exchange',
        isGeneric: true,
        path: '/add-money/crypto/other-exchanges',
    },
]

export const CRYPTO_WALLETS: CryptoSource[] = [
    {
        id: 'metamask',
        name: 'Metamask',
        type: 'wallet',
        icon: METAMASK_LOGO,
        path: '/add-money/crypto/metamask',
    },
    {
        id: 'rainbow',
        name: 'Rainbow',
        type: 'wallet',
        icon: RAINBOW_LOGO,
        path: '/add-money/crypto/rainbow',
    },
    {
        id: 'other-wallets',
        name: 'Other wallets',
        type: 'wallet',
        isGeneric: true,
        path: '/add-money/crypto/other-wallets',
    },
]

// includes countries and crypto
export const ALL_DEPOSIT_METHODS: DepositMethod[] = [
    {
        id: 'crypto',
        type: 'crypto',
        title: 'Crypto Deposit',
        description: 'Use an exchange or your wallet',
        path: '/add-money/crypto',
    },
    {
        id: 'AD',
        type: 'country',
        title: 'Andorra',
        currency: 'EUR',
        path: '/add-money/andorra',
    },
    {
        id: 'AE',
        type: 'country',
        title: 'United Arab Emirates',
        currency: 'AED',
        path: '/add-money/united-arab-emirates',
    },
    {
        id: 'AF',
        type: 'country',
        title: 'Afghanistan',
        currency: 'AFN',
        path: '/add-money/afghanistan',
    },
    {
        id: 'AG',
        type: 'country',
        title: 'Antigua and Barbuda',
        currency: 'XCD',
        path: '/add-money/antigua-and-barbuda',
    },
    {
        id: 'AI',
        type: 'country',
        title: 'Anguilla',
        currency: 'XCD',
        path: '/add-money/anguilla',
    },
    {
        id: 'AL',
        type: 'country',
        title: 'Albania',
        currency: 'ALL',
        path: '/add-money/albania',
    },
    {
        id: 'AM',
        type: 'country',
        title: 'Armenia',
        currency: 'AMD',
        path: '/add-money/armenia',
    },
    {
        id: 'AO',
        type: 'country',
        title: 'Angola',
        currency: 'AOA',
        path: '/add-money/angola',
    },
    {
        id: 'AQ',
        type: 'country',
        title: 'Antarctica',
        currency: '',
        path: '/add-money/antarctica',
    },
    {
        id: 'AR',
        type: 'country',
        title: 'Argentina',
        currency: 'ARS',
        path: '/add-money/argentina',
    },
    {
        id: 'AS',
        type: 'country',
        title: 'American Samoa',
        currency: 'USD',
        path: '/add-money/american-samoa',
    },
    {
        id: 'AT',
        type: 'country',
        title: 'Austria',
        currency: 'EUR',
        path: '/add-money/austria',
    },
    {
        id: 'AU',
        type: 'country',
        title: 'Australia',
        currency: 'AUD',
        path: '/add-money/australia',
    },
    {
        id: 'AW',
        type: 'country',
        title: 'Aruba',
        currency: 'AWG',
        path: '/add-money/aruba',
    },
    {
        id: 'AX',
        type: 'country',
        title: 'Åland',
        currency: 'EUR',
        path: '/add-money/åland',
    },
    {
        id: 'AZ',
        type: 'country',
        title: 'Azerbaijan',
        currency: 'AZN',
        path: '/add-money/azerbaijan',
    },
    {
        id: 'BA',
        type: 'country',
        title: 'Bosnia and Herzegovina',
        currency: 'BAM',
        path: '/add-money/bosnia-and-herzegovina',
    },
    {
        id: 'BB',
        type: 'country',
        title: 'Barbados',
        currency: 'BBD',
        path: '/add-money/barbados',
    },
    {
        id: 'BD',
        type: 'country',
        title: 'Bangladesh',
        currency: 'BDT',
        path: '/add-money/bangladesh',
    },
    {
        id: 'BE',
        type: 'country',
        title: 'Belgium',
        currency: 'EUR',
        path: '/add-money/belgium',
    },
    {
        id: 'BF',
        type: 'country',
        title: 'Burkina Faso',
        currency: 'XOF',
        path: '/add-money/burkina-faso',
    },
    {
        id: 'BG',
        type: 'country',
        title: 'Bulgaria',
        currency: 'BGN',
        path: '/add-money/bulgaria',
    },
    {
        id: 'BH',
        type: 'country',
        title: 'Bahrain',
        currency: 'BHD',
        path: '/add-money/bahrain',
    },
    {
        id: 'BI',
        type: 'country',
        title: 'Burundi',
        currency: 'BIF',
        path: '/add-money/burundi',
    },
    {
        id: 'BJ',
        type: 'country',
        title: 'Benin',
        currency: 'XOF',
        path: '/add-money/benin',
    },
    {
        id: 'BL',
        type: 'country',
        title: 'Saint Barthélemy',
        currency: 'EUR',
        path: '/add-money/saint-barthélemy',
    },
    {
        id: 'BM',
        type: 'country',
        title: 'Bermuda',
        currency: 'BMD',
        path: '/add-money/bermuda',
    },
    {
        id: 'BN',
        type: 'country',
        title: 'Brunei',
        currency: 'BND',
        path: '/add-money/brunei',
    },
    {
        id: 'BO',
        type: 'country',
        title: 'Bolivia',
        currency: 'BOB',
        path: '/add-money/bolivia',
    },
    {
        id: 'BQ',
        type: 'country',
        title: 'Bonaire',
        currency: 'USD',
        path: '/add-money/bonaire',
    },
    {
        id: 'BR',
        type: 'country',
        title: 'Brazil',
        currency: 'BRL',
        path: '/add-money/brazil',
    },
    {
        id: 'BS',
        type: 'country',
        title: 'Bahamas',
        currency: 'BSD',
        path: '/add-money/bahamas',
    },
    {
        id: 'BT',
        type: 'country',
        title: 'Bhutan',
        currency: 'BTN',
        path: '/add-money/bhutan',
    },
    {
        id: 'BV',
        type: 'country',
        title: 'Bouvet Island',
        currency: 'NOK',
        path: '/add-money/bouvet-island',
    },
    {
        id: 'BW',
        type: 'country',
        title: 'Botswana',
        currency: 'BWP',
        path: '/add-money/botswana',
    },
    {
        id: 'BY',
        type: 'country',
        title: 'Belarus',
        currency: 'BYR',
        path: '/add-money/belarus',
    },
    {
        id: 'BZ',
        type: 'country',
        title: 'Belize',
        currency: 'BZD',
        path: '/add-money/belize',
    },
    {
        id: 'CA',
        type: 'country',
        title: 'Canada',
        currency: 'CAD',
        path: '/add-money/canada',
    },
    {
        id: 'CC',
        type: 'country',
        title: 'Cocos [Keeling] Islands',
        currency: 'AUD',
        path: '/add-money/cocos-[keeling]-islands',
    },
    {
        id: 'CD',
        type: 'country',
        title: 'Democratic Republic of the Congo',
        currency: 'CDF',
        path: '/add-money/democratic-republic-of-the-congo',
    },
    {
        id: 'CF',
        type: 'country',
        title: 'Central African Republic',
        currency: 'XAF',
        path: '/add-money/central-african-republic',
    },
    {
        id: 'CG',
        type: 'country',
        title: 'Republic of the Congo',
        currency: 'XAF',
        path: '/add-money/republic-of-the-congo',
    },
    {
        id: 'CH',
        type: 'country',
        title: 'Switzerland',
        currency: 'CHF',
        path: '/add-money/switzerland',
    },
    {
        id: 'CI',
        type: 'country',
        title: 'Ivory Coast',
        currency: 'XOF',
        path: '/add-money/ivory-coast',
    },
    {
        id: 'CK',
        type: 'country',
        title: 'Cook Islands',
        currency: 'NZD',
        path: '/add-money/cook-islands',
    },
    {
        id: 'CL',
        type: 'country',
        title: 'Chile',
        currency: 'CLP',
        path: '/add-money/chile',
    },
    {
        id: 'CM',
        type: 'country',
        title: 'Cameroon',
        currency: 'XAF',
        path: '/add-money/cameroon',
    },
    {
        id: 'CN',
        type: 'country',
        title: 'China',
        currency: 'CNY',
        path: '/add-money/china',
    },
    {
        id: 'CO',
        type: 'country',
        title: 'Colombia',
        currency: 'COP',
        path: '/add-money/colombia',
    },
    {
        id: 'CR',
        type: 'country',
        title: 'Costa Rica',
        currency: 'CRC',
        path: '/add-money/costa-rica',
    },
    {
        id: 'CU',
        type: 'country',
        title: 'Cuba',
        currency: 'CUP',
        path: '/add-money/cuba',
    },
    {
        id: 'CV',
        type: 'country',
        title: 'Cape Verde',
        currency: 'CVE',
        path: '/add-money/cape-verde',
    },
    {
        id: 'CW',
        type: 'country',
        title: 'Curacao',
        currency: 'ANG',
        path: '/add-money/curacao',
    },
    {
        id: 'CX',
        type: 'country',
        title: 'Christmas Island',
        currency: 'AUD',
        path: '/add-money/christmas-island',
    },
    {
        id: 'CY',
        type: 'country',
        title: 'Cyprus',
        currency: 'EUR',
        path: '/add-money/cyprus',
    },
    {
        id: 'CZ',
        type: 'country',
        title: 'Czechia',
        currency: 'CZK',
        path: '/add-money/czechia',
    },
    {
        id: 'DE',
        type: 'country',
        title: 'Germany',
        currency: 'EUR',
        path: '/add-money/germany',
    },
    {
        id: 'DJ',
        type: 'country',
        title: 'Djibouti',
        currency: 'DJF',
        path: '/add-money/djibouti',
    },
    {
        id: 'DK',
        type: 'country',
        title: 'Denmark',
        currency: 'DKK',
        path: '/add-money/denmark',
    },
    {
        id: 'DM',
        type: 'country',
        title: 'Dominica',
        currency: 'XCD',
        path: '/add-money/dominica',
    },
    {
        id: 'DO',
        type: 'country',
        title: 'Dominican Republic',
        currency: 'DOP',
        path: '/add-money/dominican-republic',
    },
    {
        id: 'DZ',
        type: 'country',
        title: 'Algeria',
        currency: 'DZD',
        path: '/add-money/algeria',
    },
    {
        id: 'EC',
        type: 'country',
        title: 'Ecuador',
        currency: 'USD',
        path: '/add-money/ecuador',
    },
    {
        id: 'EE',
        type: 'country',
        title: 'Estonia',
        currency: 'EUR',
        path: '/add-money/estonia',
    },
    {
        id: 'EG',
        type: 'country',
        title: 'Egypt',
        currency: 'EGP',
        path: '/add-money/egypt',
    },
    {
        id: 'EH',
        type: 'country',
        title: 'Western Sahara',
        currency: 'MAD',
        path: '/add-money/western-sahara',
    },
    {
        id: 'ER',
        type: 'country',
        title: 'Eritrea',
        currency: 'ERN',
        path: '/add-money/eritrea',
    },
    {
        id: 'ES',
        type: 'country',
        title: 'Spain',
        currency: 'EUR',
        path: '/add-money/spain',
    },
    {
        id: 'ET',
        type: 'country',
        title: 'Ethiopia',
        currency: 'ETB',
        path: '/add-money/ethiopia',
    },
    {
        id: 'FI',
        type: 'country',
        title: 'Finland',
        currency: 'EUR',
        path: '/add-money/finland',
    },
    {
        id: 'FJ',
        type: 'country',
        title: 'Fiji',
        currency: 'FJD',
        path: '/add-money/fiji',
    },
    {
        id: 'FK',
        type: 'country',
        title: 'Falkland Islands',
        currency: 'FKP',
        path: '/add-money/falkland-islands',
    },
    {
        id: 'FM',
        type: 'country',
        title: 'Micronesia',
        currency: 'USD',
        path: '/add-money/micronesia',
    },
    {
        id: 'FO',
        type: 'country',
        title: 'Faroe Islands',
        currency: 'DKK',
        path: '/add-money/faroe-islands',
    },
    {
        id: 'FR',
        type: 'country',
        title: 'France',
        currency: 'EUR',
        path: '/add-money/france',
    },
    {
        id: 'GA',
        type: 'country',
        title: 'Gabon',
        currency: 'XAF',
        path: '/add-money/gabon',
    },
    {
        id: 'GB',
        type: 'country',
        title: 'United Kingdom',
        currency: 'GBP',
        path: '/add-money/united-kingdom',
    },
    {
        id: 'GD',
        type: 'country',
        title: 'Grenada',
        currency: 'XCD',
        path: '/add-money/grenada',
    },
    {
        id: 'GE',
        type: 'country',
        title: 'Georgia',
        currency: 'GEL',
        path: '/add-money/georgia',
    },
    {
        id: 'GF',
        type: 'country',
        title: 'French Guiana',
        currency: 'EUR',
        path: '/add-money/french-guiana',
    },
    {
        id: 'GG',
        type: 'country',
        title: 'Guernsey',
        currency: 'GBP',
        path: '/add-money/guernsey',
    },
    {
        id: 'GH',
        type: 'country',
        title: 'Ghana',
        currency: 'GHS',
        path: '/add-money/ghana',
    },
    {
        id: 'GI',
        type: 'country',
        title: 'Gibraltar',
        currency: 'GIP',
        path: '/add-money/gibraltar',
    },
    {
        id: 'GL',
        type: 'country',
        title: 'Greenland',
        currency: 'DKK',
        path: '/add-money/greenland',
    },
    {
        id: 'GM',
        type: 'country',
        title: 'Gambia',
        currency: 'GMD',
        path: '/add-money/gambia',
    },
    {
        id: 'GN',
        type: 'country',
        title: 'Guinea',
        currency: 'GNF',
        path: '/add-money/guinea',
    },
    {
        id: 'GP',
        type: 'country',
        title: 'Guadeloupe',
        currency: 'EUR',
        path: '/add-money/guadeloupe',
    },
    {
        id: 'GQ',
        type: 'country',
        title: 'Equatorial Guinea',
        currency: 'XAF',
        path: '/add-money/equatorial-guinea',
    },
    {
        id: 'GR',
        type: 'country',
        title: 'Greece',
        currency: 'EUR',
        path: '/add-money/greece',
    },
    {
        id: 'GS',
        type: 'country',
        title: 'South Georgia and the South Sandwich Islands',
        currency: 'GBP',
        path: '/add-money/south-georgia-and-the-south-sandwich-islands',
    },
    {
        id: 'GT',
        type: 'country',
        title: 'Guatemala',
        currency: 'GTQ',
        path: '/add-money/guatemala',
    },
    {
        id: 'GU',
        type: 'country',
        title: 'Guam',
        currency: 'USD',
        path: '/add-money/guam',
    },
    {
        id: 'GW',
        type: 'country',
        title: 'Guinea-Bissau',
        currency: 'XOF',
        path: '/add-money/guinea-bissau',
    },
    {
        id: 'GY',
        type: 'country',
        title: 'Guyana',
        currency: 'GYD',
        path: '/add-money/guyana',
    },
    {
        id: 'HK',
        type: 'country',
        title: 'Hong Kong',
        currency: 'HKD',
        path: '/add-money/hong-kong',
    },
    {
        id: 'HM',
        type: 'country',
        title: 'Heard Island and McDonald Islands',
        currency: 'AUD',
        path: '/add-money/heard-island-and-mcdonald-islands',
    },
    {
        id: 'HN',
        type: 'country',
        title: 'Honduras',
        currency: 'HNL',
        path: '/add-money/honduras',
    },
    {
        id: 'HR',
        type: 'country',
        title: 'Croatia',
        currency: 'HRK',
        path: '/add-money/croatia',
    },
    {
        id: 'HT',
        type: 'country',
        title: 'Haiti',
        currency: 'HTG',
        path: '/add-money/haiti',
    },
    {
        id: 'HU',
        type: 'country',
        title: 'Hungary',
        currency: 'HUF',
        path: '/add-money/hungary',
    },
    {
        id: 'ID',
        type: 'country',
        title: 'Indonesia',
        currency: 'IDR',
        path: '/add-money/indonesia',
    },
    {
        id: 'IE',
        type: 'country',
        title: 'Ireland',
        currency: 'EUR',
        path: '/add-money/ireland',
    },
    {
        id: 'IL',
        type: 'country',
        title: 'Israel',
        currency: 'ILS',
        path: '/add-money/israel',
    },
    {
        id: 'IM',
        type: 'country',
        title: 'Isle of Man',
        currency: 'GBP',
        path: '/add-money/isle-of-man',
    },
    {
        id: 'IN',
        type: 'country',
        title: 'India',
        currency: 'INR',
        path: '/add-money/india',
    },
    {
        id: 'IO',
        type: 'country',
        title: 'British Indian Ocean Territory',
        currency: 'USD',
        path: '/add-money/british-indian-ocean-territory',
    },
    {
        id: 'IQ',
        type: 'country',
        title: 'Iraq',
        currency: 'IQD',
        path: '/add-money/iraq',
    },
    {
        id: 'IR',
        type: 'country',
        title: 'Iran',
        currency: 'IRR',
        path: '/add-money/iran',
    },
    {
        id: 'IS',
        type: 'country',
        title: 'Iceland',
        currency: 'ISK',
        path: '/add-money/iceland',
    },
    {
        id: 'IT',
        type: 'country',
        title: 'Italy',
        currency: 'EUR',
        path: '/add-money/italy',
    },
    {
        id: 'JE',
        type: 'country',
        title: 'Jersey',
        currency: 'GBP',
        path: '/add-money/jersey',
    },
    {
        id: 'JM',
        type: 'country',
        title: 'Jamaica',
        currency: 'JMD',
        path: '/add-money/jamaica',
    },
    {
        id: 'JO',
        type: 'country',
        title: 'Jordan',
        currency: 'JOD',
        path: '/add-money/jordan',
    },
    {
        id: 'JP',
        type: 'country',
        title: 'Japan',
        currency: 'JPY',
        path: '/add-money/japan',
    },
    {
        id: 'KE',
        type: 'country',
        title: 'Kenya',
        currency: 'KES',
        path: '/add-money/kenya',
    },
    {
        id: 'KG',
        type: 'country',
        title: 'Kyrgyzstan',
        currency: 'KGS',
        path: '/add-money/kyrgyzstan',
    },
    {
        id: 'KH',
        type: 'country',
        title: 'Cambodia',
        currency: 'KHR',
        path: '/add-money/cambodia',
    },
    {
        id: 'KI',
        type: 'country',
        title: 'Kiribati',
        currency: 'AUD',
        path: '/add-money/kiribati',
    },
    {
        id: 'KM',
        type: 'country',
        title: 'Comoros',
        currency: 'KMF',
        path: '/add-money/comoros',
    },
    {
        id: 'KN',
        type: 'country',
        title: 'Saint Kitts and Nevis',
        currency: 'XCD',
        path: '/add-money/saint-kitts-and-nevis',
    },
    {
        id: 'KP',
        type: 'country',
        title: 'North Korea',
        currency: 'KPW',
        path: '/add-money/north-korea',
    },
    {
        id: 'KR',
        type: 'country',
        title: 'South Korea',
        currency: 'KRW',
        path: '/add-money/south-korea',
    },
    {
        id: 'KW',
        type: 'country',
        title: 'Kuwait',
        currency: 'KWD',
        path: '/add-money/kuwait',
    },
    {
        id: 'KY',
        type: 'country',
        title: 'Cayman Islands',
        currency: 'KYD',
        path: '/add-money/cayman-islands',
    },
    {
        id: 'KZ',
        type: 'country',
        title: 'Kazakhstan',
        currency: 'KZT',
        path: '/add-money/kazakhstan',
    },
    {
        id: 'LA',
        type: 'country',
        title: 'Laos',
        currency: 'LAK',
        path: '/add-money/laos',
    },
    {
        id: 'LB',
        type: 'country',
        title: 'Lebanon',
        currency: 'LBP',
        path: '/add-money/lebanon',
    },
    {
        id: 'LC',
        type: 'country',
        title: 'Saint Lucia',
        currency: 'XCD',
        path: '/add-money/saint-lucia',
    },
    {
        id: 'LI',
        type: 'country',
        title: 'Liechtenstein',
        currency: 'CHF',
        path: '/add-money/liechtenstein',
    },
    {
        id: 'LK',
        type: 'country',
        title: 'Sri Lanka',
        currency: 'LKR',
        path: '/add-money/sri-lanka',
    },
    {
        id: 'LR',
        type: 'country',
        title: 'Liberia',
        currency: 'LRD',
        path: '/add-money/liberia',
    },
    {
        id: 'LS',
        type: 'country',
        title: 'Lesotho',
        currency: 'LSL',
        path: '/add-money/lesotho',
    },
    {
        id: 'LT',
        type: 'country',
        title: 'Lithuania',
        currency: 'EUR',
        path: '/add-money/lithuania',
    },
    {
        id: 'LU',
        type: 'country',
        title: 'Luxembourg',
        currency: 'EUR',
        path: '/add-money/luxembourg',
    },
    {
        id: 'LV',
        type: 'country',
        title: 'Latvia',
        currency: 'EUR',
        path: '/add-money/latvia',
    },
    {
        id: 'LY',
        type: 'country',
        title: 'Libya',
        currency: 'LYD',
        path: '/add-money/libya',
    },
    {
        id: 'MA',
        type: 'country',
        title: 'Morocco',
        currency: 'MAD',
        path: '/add-money/morocco',
    },
    {
        id: 'MC',
        type: 'country',
        title: 'Monaco',
        currency: 'EUR',
        path: '/add-money/monaco',
    },
    {
        id: 'MD',
        type: 'country',
        title: 'Moldova',
        currency: 'MDL',
        path: '/add-money/moldova',
    },
    {
        id: 'ME',
        type: 'country',
        title: 'Montenegro',
        currency: 'EUR',
        path: '/add-money/montenegro',
    },
    {
        id: 'MF',
        type: 'country',
        title: 'Saint Martin',
        currency: 'EUR',
        path: '/add-money/saint-martin',
    },
    {
        id: 'MG',
        type: 'country',
        title: 'Madagascar',
        currency: 'MGA',
        path: '/add-money/madagascar',
    },
    {
        id: 'MH',
        type: 'country',
        title: 'Marshall Islands',
        currency: 'USD',
        path: '/add-money/marshall-islands',
    },
    {
        id: 'MK',
        type: 'country',
        title: 'Macedonia',
        currency: 'MKD',
        path: '/add-money/macedonia',
    },
    {
        id: 'ML',
        type: 'country',
        title: 'Mali',
        currency: 'XOF',
        path: '/add-money/mali',
    },
    {
        id: 'MM',
        type: 'country',
        title: 'Myanmar [Burma]',
        currency: 'MMK',
        path: '/add-money/myanmar-[burma]',
    },
    {
        id: 'MN',
        type: 'country',
        title: 'Mongolia',
        currency: 'MNT',
        path: '/add-money/mongolia',
    },
    {
        id: 'MO',
        type: 'country',
        title: 'Macao',
        currency: 'MOP',
        path: '/add-money/macao',
    },
    {
        id: 'MP',
        type: 'country',
        title: 'Northern Mariana Islands',
        currency: 'USD',
        path: '/add-money/northern-mariana-islands',
    },
    {
        id: 'MQ',
        type: 'country',
        title: 'Martinique',
        currency: 'EUR',
        path: '/add-money/martinique',
    },
    {
        id: 'MR',
        type: 'country',
        title: 'Mauritania',
        currency: 'MRO',
        path: '/add-money/mauritania',
    },
    {
        id: 'MS',
        type: 'country',
        title: 'Montserrat',
        currency: 'XCD',
        path: '/add-money/montserrat',
    },
    {
        id: 'MT',
        type: 'country',
        title: 'Malta',
        currency: 'EUR',
        path: '/add-money/malta',
    },
    {
        id: 'MU',
        type: 'country',
        title: 'Mauritius',
        currency: 'MUR',
        path: '/add-money/mauritius',
    },
    {
        id: 'MV',
        type: 'country',
        title: 'Maldives',
        currency: 'MVR',
        path: '/add-money/maldives',
    },
    {
        id: 'MW',
        type: 'country',
        title: 'Malawi',
        currency: 'MWK',
        path: '/add-money/malawi',
    },
    {
        id: 'MX',
        type: 'country',
        title: 'Mexico',
        currency: 'MXN',
        path: '/add-money/mexico',
    },
    {
        id: 'MY',
        type: 'country',
        title: 'Malaysia',
        currency: 'MYR',
        path: '/add-money/malaysia',
    },
    {
        id: 'MZ',
        type: 'country',
        title: 'Mozambique',
        currency: 'MZN',
        path: '/add-money/mozambique',
    },
    {
        id: 'NA',
        type: 'country',
        title: 'Namibia',
        currency: 'NAD',
        path: '/add-money/namibia',
    },
    {
        id: 'NC',
        type: 'country',
        title: 'New Caledonia',
        currency: 'XPF',
        path: '/add-money/new-caledonia',
    },
    {
        id: 'NE',
        type: 'country',
        title: 'Niger',
        currency: 'XOF',
        path: '/add-money/niger',
    },
    {
        id: 'NF',
        type: 'country',
        title: 'Norfolk Island',
        currency: 'AUD',
        path: '/add-money/norfolk-island',
    },
    {
        id: 'NG',
        type: 'country',
        title: 'Nigeria',
        currency: 'NGN',
        path: '/add-money/nigeria',
    },
    {
        id: 'NI',
        type: 'country',
        title: 'Nicaragua',
        currency: 'NIO',
        path: '/add-money/nicaragua',
    },
    {
        id: 'NL',
        type: 'country',
        title: 'Netherlands',
        currency: 'EUR',
        path: '/add-money/netherlands',
    },
    {
        id: 'NO',
        type: 'country',
        title: 'Norway',
        currency: 'NOK',
        path: '/add-money/norway',
    },
    {
        id: 'NP',
        type: 'country',
        title: 'Nepal',
        currency: 'NPR',
        path: '/add-money/nepal',
    },
    {
        id: 'NR',
        type: 'country',
        title: 'Nauru',
        currency: 'AUD',
        path: '/add-money/nauru',
    },
    {
        id: 'NU',
        type: 'country',
        title: 'Niue',
        currency: 'NZD',
        path: '/add-money/niue',
    },
    {
        id: 'NZ',
        type: 'country',
        title: 'New Zealand',
        currency: 'NZD',
        path: '/add-money/new-zealand',
    },
    {
        id: 'OM',
        type: 'country',
        title: 'Oman',
        currency: 'OMR',
        path: '/add-money/oman',
    },
    {
        id: 'PA',
        type: 'country',
        title: 'Panama',
        currency: 'PAB',
        path: '/add-money/panama',
    },
    {
        id: 'PE',
        type: 'country',
        title: 'Peru',
        currency: 'PEN',
        path: '/add-money/peru',
    },
    {
        id: 'PF',
        type: 'country',
        title: 'French Polynesia',
        currency: 'XPF',
        path: '/add-money/french-polynesia',
    },
    {
        id: 'PG',
        type: 'country',
        title: 'Papua New Guinea',
        currency: 'PGK',
        path: '/add-money/papua-new-guinea',
    },
    {
        id: 'PH',
        type: 'country',
        title: 'Philippines',
        currency: 'PHP',
        path: '/add-money/philippines',
    },
    {
        id: 'PK',
        type: 'country',
        title: 'Pakistan',
        currency: 'PKR',
        path: '/add-money/pakistan',
    },
    {
        id: 'PL',
        type: 'country',
        title: 'Poland',
        currency: 'PLN',
        path: '/add-money/poland',
    },
    {
        id: 'PM',
        type: 'country',
        title: 'Saint Pierre and Miquelon',
        currency: 'EUR',
        path: '/add-money/saint-pierre-and-miquelon',
    },
    {
        id: 'PN',
        type: 'country',
        title: 'Pitcairn Islands',
        currency: 'NZD',
        path: '/add-money/pitcairn-islands',
    },
    {
        id: 'PR',
        type: 'country',
        title: 'Puerto Rico',
        currency: 'USD',
        path: '/add-money/puerto-rico',
    },
    {
        id: 'PS',
        type: 'country',
        title: 'Palestine',
        currency: 'ILS',
        path: '/add-money/palestine',
    },
    {
        id: 'PT',
        type: 'country',
        title: 'Portugal',
        currency: 'EUR',
        path: '/add-money/portugal',
    },
    {
        id: 'PW',
        type: 'country',
        title: 'Palau',
        currency: 'USD',
        path: '/add-money/palau',
    },
    {
        id: 'PY',
        type: 'country',
        title: 'Paraguay',
        currency: 'PYG',
        path: '/add-money/paraguay',
    },
    {
        id: 'QA',
        type: 'country',
        title: 'Qatar',
        currency: 'QAR',
        path: '/add-money/qatar',
    },
    {
        id: 'RE',
        type: 'country',
        title: 'Réunion',
        currency: 'EUR',
        path: '/add-money/réunion',
    },
    {
        id: 'RO',
        type: 'country',
        title: 'Romania',
        currency: 'RON',
        path: '/add-money/romania',
    },
    {
        id: 'RS',
        type: 'country',
        title: 'Serbia',
        currency: 'RSD',
        path: '/add-money/serbia',
    },
    {
        id: 'RU',
        type: 'country',
        title: 'Russia',
        currency: 'RUB',
        path: '/add-money/russia',
    },
    {
        id: 'RW',
        type: 'country',
        title: 'Rwanda',
        currency: 'RWF',
        path: '/add-money/rwanda',
    },
    {
        id: 'SA',
        type: 'country',
        title: 'Saudi Arabia',
        currency: 'SAR',
        path: '/add-money/saudi-arabia',
    },
    {
        id: 'SB',
        type: 'country',
        title: 'Solomon Islands',
        currency: 'SBD',
        path: '/add-money/solomon-islands',
    },
    {
        id: 'SC',
        type: 'country',
        title: 'Seychelles',
        currency: 'SCR',
        path: '/add-money/seychelles',
    },
    {
        id: 'SD',
        type: 'country',
        title: 'Sudan',
        currency: 'SDG',
        path: '/add-money/sudan',
    },
    {
        id: 'SE',
        type: 'country',
        title: 'Sweden',
        currency: 'SEK',
        path: '/add-money/sweden',
    },
    {
        id: 'SG',
        type: 'country',
        title: 'Singapore',
        currency: 'SGD',
        path: '/add-money/singapore',
    },
    {
        id: 'SH',
        type: 'country',
        title: 'Saint Helena',
        currency: 'SHP',
        path: '/add-money/saint-helena',
    },
    {
        id: 'SI',
        type: 'country',
        title: 'Slovenia',
        currency: 'EUR',
        path: '/add-money/slovenia',
    },
    {
        id: 'SJ',
        type: 'country',
        title: 'Svalbard and Jan Mayen',
        currency: 'NOK',
        path: '/add-money/svalbard-and-jan-mayen',
    },
    {
        id: 'SK',
        type: 'country',
        title: 'Slovakia',
        currency: 'EUR',
        path: '/add-money/slovakia',
    },
    {
        id: 'SL',
        type: 'country',
        title: 'Sierra Leone',
        currency: 'SLL',
        path: '/add-money/sierra-leone',
    },
    {
        id: 'SM',
        type: 'country',
        title: 'San Marino',
        currency: 'EUR',
        path: '/add-money/san-marino',
    },
    {
        id: 'SN',
        type: 'country',
        title: 'Senegal',
        currency: 'XOF',
        path: '/add-money/senegal',
    },
    {
        id: 'SO',
        type: 'country',
        title: 'Somalia',
        currency: 'SOS',
        path: '/add-money/somalia',
    },
    {
        id: 'SR',
        type: 'country',
        title: 'Suriname',
        currency: 'SRD',
        path: '/add-money/suriname',
    },
    {
        id: 'SS',
        type: 'country',
        title: 'South Sudan',
        currency: 'SSP',
        path: '/add-money/south-sudan',
    },
    {
        id: 'ST',
        type: 'country',
        title: 'São Tomé and Príncipe',
        currency: 'STD',
        path: '/add-money/são-tomé-and-príncipe',
    },
    {
        id: 'SV',
        type: 'country',
        title: 'El Salvador',
        currency: 'USD',
        path: '/add-money/el-salvador',
    },
    {
        id: 'SX',
        type: 'country',
        title: 'Sint Maarten',
        currency: 'ANG',
        path: '/add-money/sint-maarten',
    },
    {
        id: 'SY',
        type: 'country',
        title: 'Syria',
        currency: 'SYP',
        path: '/add-money/syria',
    },
    {
        id: 'SZ',
        type: 'country',
        title: 'Swaziland',
        currency: 'SZL',
        path: '/add-money/swaziland',
    },
    {
        id: 'TC',
        type: 'country',
        title: 'Turks and Caicos Islands',
        currency: 'USD',
        path: '/add-money/turks-and-caicos-islands',
    },
    {
        id: 'TD',
        type: 'country',
        title: 'Chad',
        currency: 'XAF',
        path: '/add-money/chad',
    },
    {
        id: 'TF',
        type: 'country',
        title: 'French Southern Territories',
        currency: 'EUR',
        path: '/add-money/french-southern-territories',
    },
    {
        id: 'TG',
        type: 'country',
        title: 'Togo',
        currency: 'XOF',
        path: '/add-money/togo',
    },
    {
        id: 'TH',
        type: 'country',
        title: 'Thailand',
        currency: 'THB',
        path: '/add-money/thailand',
    },
    {
        id: 'TJ',
        type: 'country',
        title: 'Tajikistan',
        currency: 'TJS',
        path: '/add-money/tajikistan',
    },
    {
        id: 'TK',
        type: 'country',
        title: 'Tokelau',
        currency: 'NZD',
        path: '/add-money/tokelau',
    },
    {
        id: 'TL',
        type: 'country',
        title: 'East Timor',
        currency: 'USD',
        path: '/add-money/east-timor',
    },
    {
        id: 'TM',
        type: 'country',
        title: 'Turkmenistan',
        currency: 'TMT',
        path: '/add-money/turkmenistan',
    },
    {
        id: 'TN',
        type: 'country',
        title: 'Tunisia',
        currency: 'TND',
        path: '/add-money/tunisia',
    },
    {
        id: 'TO',
        type: 'country',
        title: 'Tonga',
        currency: 'TOP',
        path: '/add-money/tonga',
    },
    {
        id: 'TR',
        type: 'country',
        title: 'Turkey',
        currency: 'TRY',
        path: '/add-money/turkey',
    },
    {
        id: 'TT',
        type: 'country',
        title: 'Trinidad and Tobago',
        currency: 'TTD',
        path: '/add-money/trinidad-and-tobago',
    },
    {
        id: 'TV',
        type: 'country',
        title: 'Tuvalu',
        currency: 'AUD',
        path: '/add-money/tuvalu',
    },
    {
        id: 'TW',
        type: 'country',
        title: 'Taiwan',
        currency: 'TWD',
        path: '/add-money/taiwan',
    },
    {
        id: 'TZ',
        type: 'country',
        title: 'Tanzania',
        currency: 'TZS',
        path: '/add-money/tanzania',
    },
    {
        id: 'UA',
        type: 'country',
        title: 'Ukraine',
        currency: 'UAH',
        path: '/add-money/ukraine',
    },
    {
        id: 'UG',
        type: 'country',
        title: 'Uganda',
        currency: 'UGX',
        path: '/add-money/uganda',
    },
    {
        id: 'UM',
        type: 'country',
        title: 'U.S. Minor Outlying Islands',
        currency: 'USD',
        path: '/add-money/u.s.-minor-outlying-islands',
    },
    {
        id: 'US',
        type: 'country',
        title: 'United States',
        currency: 'USD',
        path: '/add-money/united-states',
    },
    {
        id: 'UY',
        type: 'country',
        title: 'Uruguay',
        currency: 'UYU',
        path: '/add-money/uruguay',
    },
    {
        id: 'UZ',
        type: 'country',
        title: 'Uzbekistan',
        currency: 'UZS',
        path: '/add-money/uzbekistan',
    },
    {
        id: 'VA',
        type: 'country',
        title: 'Vatican City',
        currency: 'EUR',
        path: '/add-money/vatican-city',
    },
    {
        id: 'VC',
        type: 'country',
        title: 'Saint Vincent and the Grenadines',
        currency: 'XCD',
        path: '/add-money/saint-vincent-and-the-grenadines',
    },
    {
        id: 'VE',
        type: 'country',
        title: 'Venezuela',
        currency: 'VEF',
        path: '/add-money/venezuela',
    },
    {
        id: 'VG',
        type: 'country',
        title: 'British Virgin Islands',
        currency: 'USD',
        path: '/add-money/british-virgin-islands',
    },
    {
        id: 'VI',
        type: 'country',
        title: 'U.S. Virgin Islands',
        currency: 'USD',
        path: '/add-money/u.s.-virgin-islands',
    },
    {
        id: 'VN',
        type: 'country',
        title: 'Vietnam',
        currency: 'VND',
        path: '/add-money/vietnam',
    },
    {
        id: 'VU',
        type: 'country',
        title: 'Vanuatu',
        currency: 'VUV',
        path: '/add-money/vanuatu',
    },
    {
        id: 'WF',
        type: 'country',
        title: 'Wallis and Futuna',
        currency: 'XPF',
        path: '/add-money/wallis-and-futuna',
    },
    {
        id: 'WS',
        type: 'country',
        title: 'Samoa',
        currency: 'WST',
        path: '/add-money/samoa',
    },
    {
        id: 'XK',
        type: 'country',
        title: 'Kosovo',
        currency: 'EUR',
        path: '/add-money/kosovo',
    },
    {
        id: 'YE',
        type: 'country',
        title: 'Yemen',
        currency: 'YER',
        path: '/add-money/yemen',
    },
    {
        id: 'YT',
        type: 'country',
        title: 'Mayotte',
        currency: 'EUR',
        path: '/add-money/mayotte',
    },
    {
        id: 'ZA',
        type: 'country',
        title: 'South Africa',
        currency: 'ZAR',
        path: '/add-money/south-africa',
    },
    {
        id: 'ZM',
        type: 'country',
        title: 'Zambia',
        currency: 'ZMW',
        path: '/add-money/zambia',
    },
    {
        id: 'ZW',
        type: 'country',
        title: 'Zimbabwe',
        currency: 'ZWL',
        path: '/add-money/zimbabwe',
    },
]
