import { MERCADO_PAGO, SOLANA_ICON, TRON_ICON, PIX } from '@/assets'
import { type IconName } from '@/components/Global/Icons/Icon'
import { type StaticImageData } from 'next/image'

// ref: https://docs.manteca.dev/cripto/key-concepts/exchanges-multi-country#Available-Exchanges
// DISABLED most exchanges because manteca support is fragile, and we need to
// check kyc for all countries
export const MantecaSupportedExchanges = {
    AR: 'ARGENTINA',
    //CL: 'CHILE',
    BR: 'BRAZIL',
    //CO: 'COLOMBIA',
    //PA: 'PANAMA',
    //CR: 'COSTA_RICA',
    //GT: 'GUATEMALA',
    // MX: 'MEXICO',
    //PH: 'PHILIPPINES',
    //BO: 'BOLIVIA',
}

export interface CryptoToken {
    id: string
    name: string
    symbol: string
    icon: StaticImageData | string
}

// @dev: this is a temporary list of tokens for the deposit screen, using this for a couple of weeks, once x-chain is ready, we will use the x-chain tokens and remove this list, only useful token is USDC here for now
export const DEPOSIT_CRYPTO_TOKENS: CryptoToken[] = [
    {
        id: 'usdc',
        name: 'USD Coin',
        symbol: 'USDC',
        icon: 'https://assets.coingecko.com/coins/images/6319/small/USD_Coin_icon.png',
    },
    {
        id: 'usdt',
        name: 'Tether',
        symbol: 'USDT',
        icon: 'https://assets.coingecko.com/coins/images/325/small/Tether-logo.png',
    },
    {
        id: 'eth',
        name: 'Ethereum',
        symbol: 'ETH',
        icon: 'https://assets.coingecko.com/coins/images/279/small/ethereum.png',
    },
    {
        id: 'sol',
        name: 'Solana',
        symbol: 'SOL',
        icon: SOLANA_ICON,
    },
    {
        id: 'btc',
        name: 'Bitcoin',
        symbol: 'BTC',
        icon: 'https://assets.coingecko.com/coins/images/1/small/bitcoin.png',
    },
    {
        id: 'trx',
        name: 'Tron',
        symbol: 'TRX',
        icon: TRON_ICON,
    },
]

export interface SpecificPaymentMethod {
    id: string
    icon: IconName | string | undefined
    title: string
    description: string
    isSoon?: boolean
    path?: string
}

export interface CountrySpecificMethods {
    add: SpecificPaymentMethod[]
    withdraw: SpecificPaymentMethod[]
}

export interface CountryData {
    id: string
    type: 'crypto' | 'country'
    title: string
    currency?: string
    description?: string
    path: string
    iso2?: string
    iso3?: string
    region?: 'europe' | 'north-america' | 'latam' | 'rest-of-the-world'
}

export interface DepositMethods extends CountryData {
    specificMethods?: CountrySpecificMethods
}

export const UPDATED_DEFAULT_ADD_MONEY_METHODS: SpecificPaymentMethod[] = [
    {
        id: 'bank-transfer-add',
        icon: 'bank' as IconName,
        title: 'From Bank',
        description: 'Usually in minutes - KYC required',
        isSoon: false,
    },
    {
        id: 'crypto-add',
        icon: 'wallet-outline' as IconName,
        path: '/add-money/crypto',
        title: 'From Crypto',
        description: 'Usually arrives instantly',
        isSoon: false,
    },
    {
        id: 'mercado-pago-add',
        path: '/add-money/argentina/manteca',
        icon: MERCADO_PAGO,
        title: 'Mercado Pago',
        description: 'Instant transfers',
        isSoon: false,
    },
    {
        id: 'pix-add',
        icon: PIX,
        path: '/add-money/brazil/manteca',
        title: 'Pix',
        description: 'Instant transfers',
        isSoon: false,
    },
    // @dev TODO: Re-enable this once we have a way to support it
    // {
    //     id: 'apple-pay-add',
    //     icon: APPLE_PAY,
    //     title: 'Apple Pay',
    //     description: 'Usually arrives instantly',
    //     isSoon: true,
    // },
    // {
    //     id: 'google-pay-add',
    //     icon: GOOGLE_PAY,
    //     title: 'Google Pay',
    //     description: 'Usually arrives instantly',
    //     isSoon: true,
    // },
]

export const DEFAULT_BANK_WITHDRAW_METHOD: SpecificPaymentMethod = {
    id: 'default-bank-withdraw',
    icon: 'bank' as IconName,
    title: 'To Bank',
    description: 'Standard bank withdrawal',
    isSoon: false,
}

export const DEFAULT_WITHDRAW_METHODS: SpecificPaymentMethod[] = [
    {
        id: 'crypto-withdraw',
        icon: 'wallet-outline' as IconName,
        title: 'Crypto',
        description: 'Withdraw to a wallet address',
        isSoon: false,
        path: '/withdraw/crypto',
    },
    {
        id: 'default-bank-withdraw',
        icon: 'bank' as IconName,
        title: 'To Bank',
        description: 'Standard bank withdrawal',
        isSoon: false,
    },
]

const countrySpecificWithdrawMethods: Record<
    string,
    Array<{ title: string; description: string; icon?: IconName | string; isSoon?: boolean }>
> = {
    India: [{ title: 'UPI', description: 'Unified Payments Interface, ~17B txns/month, 84% of digital payments.' }],
    Brazil: [{ title: 'Pix', description: 'Instant transfers', icon: PIX, isSoon: false }],
    Argentina: [
        {
            title: 'Mercado Pago',
            description: 'Instant transfers',
            icon: MERCADO_PAGO,
            isSoon: false,
        },
    ],
    Mexico: [{ title: 'CoDi', description: 'Central bank-backed RTP, adoption growing.' }],
    Kenya: [{ title: 'M-Pesa', description: 'Over 90% penetration, also in Tanzania, Mozambique, etc.' }],
    Portugal: [{ title: 'MB WAY', description: 'Popular for QR payments, instant transfers.' }],
    Poland: [{ title: 'BLIK', description: '1.5B txns/year, widely used mobile payment app.' }],
    Spain: [{ title: 'Bizum', description: 'Instant P2P + merchant payments, deeply bank-integrated.' }],
    'United States': [
        { title: 'Cash App', description: '50M+ users, QR-based, popular for P2P.' },
        { title: 'Venmo', description: 'Owned by PayPal, strong in P2P payments.' },
    ],
    Nigeria: [{ title: 'Airtel Money', description: 'Mobile money leader in Nigeria; also MTN MoMo is relevant.' }],
    Malaysia: [{ title: 'DuitNow', description: 'Instant payments, QR-based, regional links.' }],
    Thailand: [{ title: 'PromptPay', description: '10B txns in 2024, QR-based.' }],
    Australia: [{ title: 'NPP', description: 'National RTP infrastructure, 2.2B txns/year.' }],
    'United Kingdom': [{ title: 'FPS', description: 'Longstanding RTP system, 5B txns/year.' }],
    'South Africa': [{ title: 'PayShap', description: 'Newer RTP system, promotes inclusion.' }],
    Sweden: [{ title: 'Swish', description: 'Widely adopted for P2P and retail.' }],
    Indonesia: [{ title: 'QRIS', description: 'QR code standard, growing rapidly.' }],
    Philippines: [{ title: 'GCash', description: 'Leading wallet, supports RTP + QR payments.' }],
    Vietnam: [{ title: 'MoMo', description: 'Most popular mobile wallet, instant transfers.' }],
    Colombia: [{ title: 'Transfiya', description: 'Inspired by Pix, expanding fast.' }],
    Peru: [{ title: 'Yape', description: 'QR-based app, high user growth.' }],
    'Costa Rica': [{ title: 'SINPE Móvil', description: 'Mobile RTP system for instant transfers.' }],
    Singapore: [{ title: 'PayNow', description: 'Mobile number + QR-based RTP.' }],
    Japan: [{ title: 'Zengin-Net', description: 'Real-time interbank network, legacy base.' }],
    UAE: [{ title: 'UAEFTS', description: 'Central bank RTP system, modernizing rapidly.' }],
    'Saudi Arabia': [{ title: 'SARIE', description: 'Real-time fund transfers, national scale.' }],
    Tanzania: [{ title: 'M-Pesa', description: 'Same infrastructure as Kenya.' }],
    Pakistan: [{ title: 'Raast', description: 'State-backed instant payments, scaling fast.' }],
    Turkey: [{ title: 'FAST', description: "Central bank's instant payment system." }],
    Canada: [{ title: 'Interac e-Transfer', description: 'Widely used for P2P and bill payments.' }],
}

export const countryData: CountryData[] = [
    {
        id: 'crypto',
        type: 'crypto',
        title: 'Crypto',
        description: '',
        path: 'crypto',
    },
    {
        id: 'AND',
        type: 'country',
        title: 'Andorra',
        currency: 'EUR',
        path: 'andorra',
        iso2: 'AD',
        iso3: 'AND',
        region: 'europe',
    },
    {
        id: 'AE',
        type: 'country',
        title: 'United Arab Emirates',
        currency: 'AED',
        path: 'united-arab-emirates',
        iso2: 'AE',
        iso3: 'ARE',
        region: 'rest-of-the-world',
    },
    {
        id: 'AF',
        type: 'country',
        title: 'Afghanistan',
        currency: 'AFN',
        path: 'afghanistan',
        iso2: 'AF',
        iso3: 'AFG',
        region: 'rest-of-the-world',
    },
    {
        id: 'AG',
        type: 'country',
        title: 'Antigua and Barbuda',
        currency: 'XCD',
        path: 'antigua-and-barbuda',
        iso2: 'AG',
        iso3: 'ATG',
        region: 'north-america',
    },
    {
        id: 'AI',
        type: 'country',
        title: 'Anguilla',
        currency: 'XCD',
        path: 'anguilla',
        iso2: 'AI',
        iso3: 'AIA',
        region: 'north-america',
    },
    {
        id: 'AL',
        type: 'country',
        title: 'Albania',
        currency: 'ALL',
        path: 'albania',
        iso2: 'AL',
        iso3: 'ALB',
        region: 'europe',
    },
    {
        id: 'AM',
        type: 'country',
        title: 'Armenia',
        currency: 'AMD',
        path: 'armenia',
        iso2: 'AM',
        iso3: 'ARM',
        region: 'rest-of-the-world',
    },
    {
        id: 'AO',
        type: 'country',
        title: 'Angola',
        currency: 'AOA',
        path: 'angola',
        iso2: 'AO',
        iso3: 'AGO',
        region: 'rest-of-the-world',
    },
    {
        id: 'AQ',
        type: 'country',
        title: 'Antarctica',
        currency: '',
        path: 'antarctica',
        iso2: 'AQ',
        iso3: 'ATA',
        region: 'rest-of-the-world',
    },
    {
        id: 'AR',
        type: 'country',
        title: 'Argentina',
        currency: 'ARS',
        path: 'argentina',
        iso2: 'AR',
        iso3: 'ARG',
        region: 'latam',
    },
    {
        id: 'AS',
        type: 'country',
        title: 'American Samoa',
        currency: 'USD',
        path: 'american-samoa',
        iso2: 'AS',
        iso3: 'ASM',
        region: 'rest-of-the-world',
    },
    {
        id: 'AUT',
        type: 'country',
        title: 'Austria',
        currency: 'EUR',
        path: 'austria',
        iso2: 'AT',
        iso3: 'AUT',
        region: 'europe',
    },
    {
        id: 'AU',
        type: 'country',
        title: 'Australia',
        currency: 'AUD',
        path: 'australia',
        iso2: 'AU',
        iso3: 'AUS',
        region: 'rest-of-the-world',
    },
    {
        id: 'AW',
        type: 'country',
        title: 'Aruba',
        currency: 'AWG',
        path: 'aruba',
        iso2: 'AW',
        iso3: 'ABW',
        region: 'north-america',
    },
    {
        id: 'ALA',
        type: 'country',
        title: 'Åland',
        currency: 'EUR',
        path: 'aland',
        iso2: 'AX',
        iso3: 'ALA',
        region: 'europe',
    },
    {
        id: 'AZ',
        type: 'country',
        title: 'Azerbaijan',
        currency: 'AZN',
        path: 'azerbaijan',
        iso2: 'AZ',
        iso3: 'AZE',
        region: 'rest-of-the-world',
    },
    {
        id: 'BA',
        type: 'country',
        title: 'Bosnia and Herzegovina',
        currency: 'BAM',
        path: 'bosnia-and-herzegovina',
        iso2: 'BA',
        iso3: 'BIH',
        region: 'europe',
    },
    {
        id: 'BB',
        type: 'country',
        title: 'Barbados',
        currency: 'BBD',
        path: 'barbados',
        iso2: 'BB',
        iso3: 'BRB',
        region: 'north-america',
    },
    {
        id: 'BD',
        type: 'country',
        title: 'Bangladesh',
        currency: 'BDT',
        path: 'bangladesh',
        iso2: 'BD',
        iso3: 'BGD',
        region: 'rest-of-the-world',
    },
    {
        id: 'BEL',
        type: 'country',
        title: 'Belgium',
        currency: 'EUR',
        path: 'belgium',
        iso2: 'BE',
        iso3: 'BEL',
        region: 'europe',
    },
    {
        id: 'BF',
        type: 'country',
        title: 'Burkina Faso',
        currency: 'XOF',
        path: 'burkina-faso',
        iso2: 'BF',
        iso3: 'BFA',
        region: 'rest-of-the-world',
    },
    {
        id: 'BGR',
        type: 'country',
        title: 'Bulgaria',
        currency: 'BGN',
        path: 'bulgaria',
        iso2: 'BG',
        iso3: 'BGR',
        region: 'europe',
    },
    {
        id: 'BH',
        type: 'country',
        title: 'Bahrain',
        currency: 'BHD',
        path: 'bahrain',
        iso2: 'BH',
        iso3: 'BHR',
        region: 'rest-of-the-world',
    },
    {
        id: 'BI',
        type: 'country',
        title: 'Burundi',
        currency: 'BIF',
        path: 'burundi',
        iso2: 'BI',
        iso3: 'BDI',
        region: 'rest-of-the-world',
    },
    {
        id: 'BJ',
        type: 'country',
        title: 'Benin',
        currency: 'XOF',
        path: 'benin',
        iso2: 'BJ',
        iso3: 'BEN',
        region: 'rest-of-the-world',
    },
    {
        id: 'BL',
        type: 'country',
        title: 'Saint Barthélemy',
        currency: 'EUR',
        path: 'saint-barthélemy',
        iso2: 'BL',
        iso3: 'BLM',
        region: 'europe',
    },
    {
        id: 'BM',
        type: 'country',
        title: 'Bermuda',
        currency: 'BMD',
        path: 'bermuda',
        iso2: 'BM',
        iso3: 'BMU',
        region: 'north-america',
    },
    {
        id: 'BN',
        type: 'country',
        title: 'Brunei',
        currency: 'BND',
        path: 'brunei',
        iso2: 'BN',
        iso3: 'BRN',
        region: 'rest-of-the-world',
    },
    {
        id: 'BO',
        type: 'country',
        title: 'Bolivia',
        currency: 'BOB',
        path: 'bolivia',
        iso2: 'BO',
        iso3: 'BOL',
        region: 'latam',
    },
    {
        id: 'BQ',
        type: 'country',
        title: 'Bonaire',
        currency: 'USD',
        path: 'bonaire',
        iso2: 'BQ',
        iso3: 'BES',
        region: 'north-america',
    },
    {
        id: 'BR',
        type: 'country',
        title: 'Brazil',
        currency: 'BRL',
        path: 'brazil',
        iso2: 'BR',
        iso3: 'BRA',
        region: 'latam',
    },
    {
        id: 'BS',
        type: 'country',
        title: 'Bahamas',
        currency: 'BSD',
        path: 'bahamas',
        iso2: 'BS',
        iso3: 'BHS',
        region: 'north-america',
    },
    {
        id: 'BT',
        type: 'country',
        title: 'Bhutan',
        currency: 'BTN',
        path: 'bhutan',
        iso2: 'BT',
        iso3: 'BTN',
        region: 'rest-of-the-world',
    },
    {
        id: 'BV',
        type: 'country',
        title: 'Bouvet Island',
        currency: 'NOK',
        path: 'bouvet-island',
        iso2: 'BV',
        iso3: 'BVT',
        region: 'rest-of-the-world',
    },
    {
        id: 'BW',
        type: 'country',
        title: 'Botswana',
        currency: 'BWP',
        path: 'botswana',
        iso2: 'BW',
        iso3: 'BWA',
        region: 'rest-of-the-world',
    },
    {
        id: 'BY',
        type: 'country',
        title: 'Belarus',
        currency: 'BYN',
        path: 'belarus',
        iso2: 'BY',
        iso3: 'BLR',
        region: 'europe',
    },
    {
        id: 'BZ',
        type: 'country',
        title: 'Belize',
        currency: 'BZD',
        path: 'belize',
        iso2: 'BZ',
        iso3: 'BLZ',
        region: 'latam',
    },
    {
        id: 'CA',
        type: 'country',
        title: 'Canada',
        currency: 'CAD',
        path: 'canada',
        iso2: 'CA',
        iso3: 'CAN',
        region: 'north-america',
    },
    {
        id: 'CC',
        type: 'country',
        title: 'Cocos (Keeling) Islands',
        currency: 'AUD',
        path: 'cocos-keeling-islands',
        iso2: 'CC',
        iso3: 'CCK',
        region: 'rest-of-the-world',
    },
    {
        id: 'CD',
        type: 'country',
        title: 'Democratic Republic of the Congo',
        currency: 'CDF',
        path: 'democratic-republic-of-the-congo',
        iso2: 'CD',
        iso3: 'COD',
        region: 'rest-of-the-world',
    },
    {
        id: 'CF',
        type: 'country',
        title: 'Central African Republic',
        currency: 'XAF',
        path: 'central-african-republic',
        iso2: 'CF',
        iso3: 'CAF',
        region: 'rest-of-the-world',
    },
    {
        id: 'CG',
        type: 'country',
        title: 'Republic of the Congo',
        currency: 'XAF',
        path: 'republic-of-the-congo',
        iso2: 'CG',
        iso3: 'COG',
        region: 'rest-of-the-world',
    },
    {
        id: 'CHE',
        type: 'country',
        title: 'Switzerland',
        currency: 'CHF',
        path: 'switzerland',
        iso2: 'CH',
        iso3: 'CHE',
        region: 'europe',
    },
    {
        id: 'CI',
        type: 'country',
        title: 'Ivory Coast',
        currency: 'XOF',
        path: 'ivory-coast',
        iso2: 'CI',
        iso3: 'CIV',
        region: 'rest-of-the-world',
    },
    {
        id: 'CK',
        type: 'country',
        title: 'Cook Islands',
        currency: 'NZD',
        path: 'cook-islands',
        iso2: 'CK',
        iso3: 'COK',
        region: 'rest-of-the-world',
    },
    {
        id: 'CL',
        type: 'country',
        title: 'Chile',
        currency: 'CLP',
        path: 'chile',
        iso2: 'CL',
        iso3: 'CHL',
        region: 'latam',
    },
    {
        id: 'CM',
        type: 'country',
        title: 'Cameroon',
        currency: 'XAF',
        path: 'cameroon',
        iso2: 'CM',
        iso3: 'CMR',
        region: 'rest-of-the-world',
    },
    {
        id: 'CN',
        type: 'country',
        title: 'China',
        currency: 'CNY',
        path: 'china',
        iso2: 'CN',
        iso3: 'CHN',
        region: 'rest-of-the-world',
    },
    {
        id: 'CO',
        type: 'country',
        title: 'Colombia',
        currency: 'COP',
        path: 'colombia',
        iso2: 'CO',
        iso3: 'COL',
        region: 'latam',
    },
    {
        id: 'CR',
        type: 'country',
        title: 'Costa Rica',
        currency: 'CRC',
        path: 'costa-rica',
        iso2: 'CR',
        iso3: 'CRI',
        region: 'latam',
    },
    {
        id: 'CU',
        type: 'country',
        title: 'Cuba',
        currency: 'CUP',
        path: 'cuba',
        iso2: 'CU',
        iso3: 'CUB',
        region: 'north-america',
    },
    {
        id: 'CV',
        type: 'country',
        title: 'Cape Verde',
        currency: 'CVE',
        path: 'cape-verde',
        iso2: 'CV',
        iso3: 'CPV',
        region: 'rest-of-the-world',
    },
    {
        id: 'CW',
        type: 'country',
        title: 'Curacao',
        currency: 'ANG',
        path: 'curacao',
        iso2: 'CW',
        iso3: 'CUW',
        region: 'north-america',
    },
    {
        id: 'CX',
        type: 'country',
        title: 'Christmas Island',
        currency: 'AUD',
        path: 'christmas-island',
        iso2: 'CX',
        iso3: 'CXR',
        region: 'rest-of-the-world',
    },
    {
        id: 'CYP',
        type: 'country',
        title: 'Cyprus',
        currency: 'EUR',
        path: 'cyprus',
        iso2: 'CY',
        iso3: 'CYP',
        region: 'europe',
    },
    {
        id: 'CZE',
        type: 'country',
        title: 'Czechia',
        currency: 'CZK',
        path: 'czechia',
        iso2: 'CZ',
        iso3: 'CZE',
        region: 'europe',
    },
    {
        id: 'DEU',
        type: 'country',
        title: 'Germany',
        currency: 'EUR',
        path: 'germany',
        iso2: 'DE',
        iso3: 'DEU',
        region: 'europe',
    },
    {
        id: 'DJ',
        type: 'country',
        title: 'Djibouti',
        currency: 'DJF',
        path: 'djibouti',
        iso2: 'DJ',
        iso3: 'DJI',
        region: 'rest-of-the-world',
    },
    {
        id: 'DNK',
        type: 'country',
        title: 'Denmark',
        currency: 'DKK',
        path: 'denmark',
        iso2: 'DK',
        iso3: 'DNK',
        region: 'europe',
    },
    {
        id: 'DM',
        type: 'country',
        title: 'Dominica',
        currency: 'XCD',
        path: 'dominica',
        iso2: 'DM',
        iso3: 'DMA',
        region: 'latam',
    },
    {
        id: 'DO',
        type: 'country',
        title: 'Dominican Republic',
        currency: 'DOP',
        path: 'dominican-republic',
        iso2: 'DO',
        iso3: 'DOM',
        region: 'latam',
    },
    {
        id: 'DZ',
        type: 'country',
        title: 'Algeria',
        currency: 'DZD',
        path: 'algeria',
        iso2: 'DZ',
        iso3: 'DZA',
        region: 'rest-of-the-world',
    },
    {
        id: 'EC',
        type: 'country',
        title: 'Ecuador',
        currency: 'USD',
        path: 'ecuador',
        iso2: 'EC',
        iso3: 'ECU',
        region: 'latam',
    },
    {
        id: 'EST',
        type: 'country',
        title: 'Estonia',
        currency: 'EUR',
        path: 'estonia',
        iso2: 'EE',
        iso3: 'EST',
        region: 'europe',
    },
    {
        id: 'EG',
        type: 'country',
        title: 'Egypt',
        currency: 'EGP',
        path: 'egypt',
        iso2: 'EG',
        iso3: 'EGY',
        region: 'rest-of-the-world',
    },
    {
        id: 'EH',
        type: 'country',
        title: 'Western Sahara',
        currency: 'MAD',
        path: 'western-sahara',
        iso2: 'EH',
        iso3: 'ESH',
        region: 'rest-of-the-world',
    },
    {
        id: 'ER',
        type: 'country',
        title: 'Eritrea',
        currency: 'ERN',
        path: 'eritrea',
        iso2: 'ER',
        iso3: 'ERI',
        region: 'rest-of-the-world',
    },
    {
        id: 'ESP',
        type: 'country',
        title: 'Spain',
        currency: 'EUR',
        path: 'spain',
        iso2: 'ES',
        iso3: 'ESP',
        region: 'europe',
    },
    {
        id: 'ET',
        type: 'country',
        title: 'Ethiopia',
        currency: 'ETB',
        path: 'ethiopia',
        iso2: 'ET',
        iso3: 'ETH',
        region: 'rest-of-the-world',
    },
    {
        id: 'FIN',
        type: 'country',
        title: 'Finland',
        currency: 'EUR',
        path: 'finland',
        iso2: 'FI',
        iso3: 'FIN',
        region: 'europe',
    },
    {
        id: 'FJ',
        type: 'country',
        title: 'Fiji',
        currency: 'FJD',
        path: 'fiji',
        iso2: 'FJ',
        iso3: 'FJI',
        region: 'rest-of-the-world',
    },
    {
        id: 'FK',
        type: 'country',
        title: 'Falkland Islands',
        currency: 'FKP',
        path: 'falkland-islands',
        iso2: 'FK',
        iso3: 'FLK',
        region: 'latam',
    },
    {
        id: 'FM',
        type: 'country',
        title: 'Micronesia',
        currency: 'USD',
        path: 'micronesia',
        iso2: 'FM',
        iso3: 'FSM',
        region: 'rest-of-the-world',
    },
    {
        id: 'FO',
        type: 'country',
        title: 'Faroe Islands',
        currency: 'DKK',
        path: 'faroe-islands',
        iso2: 'FO',
        iso3: 'FRO',
        region: 'europe',
    },
    {
        id: 'FRA',
        type: 'country',
        title: 'France',
        currency: 'EUR',
        path: 'france',
        iso2: 'FR',
        iso3: 'FRA',
        region: 'europe',
    },
    {
        id: 'GA',
        type: 'country',
        title: 'Gabon',
        currency: 'XAF',
        path: 'gabon',
        iso2: 'GA',
        iso3: 'GAB',
        region: 'rest-of-the-world',
    },
    {
        id: 'GBR',
        type: 'country',
        title: 'United Kingdom',
        currency: 'GBP',
        path: 'united-kingdom',
        iso2: 'GB',
        iso3: 'GBR',
        region: 'europe',
    },
    {
        id: 'GD',
        type: 'country',
        title: 'Grenada',
        currency: 'XCD',
        path: 'grenada',
        iso2: 'GD',
        iso3: 'GRD',
        region: 'latam',
    },
    {
        id: 'GE',
        type: 'country',
        title: 'Georgia',
        currency: 'GEL',
        path: 'georgia',
        iso2: 'GE',
        iso3: 'GEO',
        region: 'europe',
    },
    {
        id: 'GUF',
        type: 'country',
        title: 'French Guiana',
        currency: 'EUR',
        path: 'french-guiana',
        iso2: 'GF',
        iso3: 'GUF',
        region: 'europe',
    },
    {
        id: 'GG',
        type: 'country',
        title: 'Guernsey',
        currency: 'GBP',
        path: 'guernsey',
        iso2: 'GG',
        iso3: 'GGY',
        region: 'europe',
    },
    {
        id: 'GH',
        type: 'country',
        title: 'Ghana',
        currency: 'GHS',
        path: 'ghana',
        iso2: 'GH',
        iso3: 'GHA',
        region: 'rest-of-the-world',
    },
    {
        id: 'GI',
        type: 'country',
        title: 'Gibraltar',
        currency: 'GIP',
        path: 'gibraltar',
        iso2: 'GI',
        iso3: 'GIB',
        region: 'europe',
    },
    {
        id: 'GL',
        type: 'country',
        title: 'Greenland',
        currency: 'DKK',
        path: 'greenland',
        iso2: 'GL',
        iso3: 'GRL',
        region: 'north-america',
    },
    {
        id: 'GM',
        type: 'country',
        title: 'Gambia',
        currency: 'GMD',
        path: 'gambia',
        iso2: 'GM',
        iso3: 'GMB',
        region: 'rest-of-the-world',
    },
    {
        id: 'GN',
        type: 'country',
        title: 'Guinea',
        currency: 'GNF',
        path: 'guinea',
        iso2: 'GN',
        iso3: 'GIN',
        region: 'rest-of-the-world',
    },
    {
        id: 'GP',
        type: 'country',
        title: 'Guadeloupe',
        currency: 'EUR',
        path: 'guadeloupe',
        iso2: 'GP',
        iso3: 'GLP',
        region: 'europe',
    },
    {
        id: 'GQ',
        type: 'country',
        title: 'Equatorial Guinea',
        currency: 'XAF',
        path: 'equatorial-guinea',
        iso2: 'GQ',
        iso3: 'GNQ',
        region: 'rest-of-the-world',
    },
    {
        id: 'GR',
        type: 'country',
        title: 'Greece',
        currency: 'EUR',
        path: 'greece',
        iso2: 'GR',
        iso3: 'GRC',
        region: 'europe',
    },
    {
        id: 'GS',
        type: 'country',
        title: 'South Georgia and the South Sandwich Islands',
        currency: 'GBP',
        path: 'south-georgia-and-the-south-sandwich-islands',
        iso2: 'GS',
        iso3: 'SGS',
        region: 'rest-of-the-world',
    },
    {
        id: 'GT',
        type: 'country',
        title: 'Guatemala',
        currency: 'GTQ',
        path: 'guatemala',
        iso2: 'GT',
        iso3: 'GTM',
        region: 'latam',
    },
    {
        id: 'GU',
        type: 'country',
        title: 'Guam',
        currency: 'USD',
        path: 'guam',
        iso2: 'GU',
        iso3: 'GUM',
        region: 'rest-of-the-world',
    },
    {
        id: 'GW',
        type: 'country',
        title: 'Guinea-Bissau',
        currency: 'XOF',
        path: 'guinea-bissau',
        iso2: 'GW',
        iso3: 'GNB',
        region: 'rest-of-the-world',
    },
    {
        id: 'GY',
        type: 'country',
        title: 'Guyana',
        currency: 'GYD',
        path: 'guyana',
        iso2: 'GY',
        iso3: 'GUY',
        region: 'latam',
    },
    {
        id: 'HK',
        type: 'country',
        title: 'Hong Kong',
        currency: 'HKD',
        path: 'hong-kong',
        iso2: 'HK',
        iso3: 'HKG',
        region: 'rest-of-the-world',
    },
    {
        id: 'HM',
        type: 'country',
        title: 'Heard Island and McDonald Islands',
        currency: 'AUD',
        path: 'heard-island-and-mcdonald-islands',
        iso2: 'HM',
        iso3: 'HMD',
        region: 'rest-of-the-world',
    },
    {
        id: 'HN',
        type: 'country',
        title: 'Honduras',
        currency: 'HNL',
        path: 'honduras',
        iso2: 'HN',
        iso3: 'HND',
        region: 'latam',
    },
    {
        id: 'HRV',
        type: 'country',
        title: 'Croatia',
        currency: 'EUR',
        path: 'croatia',
        iso2: 'HR',
        iso3: 'HRV',
        region: 'europe',
    },
    {
        id: 'HT',
        type: 'country',
        title: 'Haiti',
        currency: 'HTG',
        path: 'haiti',
        iso2: 'HT',
        iso3: 'HTI',
        region: 'latam',
    },
    {
        id: 'HUN',
        type: 'country',
        title: 'Hungary',
        currency: 'HUF',
        path: 'hungary',
        iso2: 'HU',
        iso3: 'HUN',
        region: 'europe',
    },
    {
        id: 'ID',
        type: 'country',
        title: 'Indonesia',
        currency: 'IDR',
        path: 'indonesia',
        iso2: 'ID',
        iso3: 'IDN',
        region: 'rest-of-the-world',
    },
    {
        id: 'IRL',
        type: 'country',
        title: 'Ireland',
        currency: 'EUR',
        path: 'ireland',
        iso2: 'IE',
        iso3: 'IRL',
        region: 'europe',
    },
    {
        id: 'IL',
        type: 'country',
        title: 'Israel',
        currency: 'ILS',
        path: 'israel',
        iso2: 'IL',
        iso3: 'ISR',
        region: 'rest-of-the-world',
    },
    {
        id: 'IM',
        type: 'country',
        title: 'Isle of Man',
        currency: 'GBP',
        path: 'isle-of-man',
        iso2: 'IM',
        iso3: 'IMN',
        region: 'europe',
    },
    {
        id: 'IN',
        type: 'country',
        title: 'India',
        currency: 'INR',
        path: 'india',
        iso2: 'IN',
        iso3: 'IND',
        region: 'rest-of-the-world',
    },
    {
        id: 'IO',
        type: 'country',
        title: 'British Indian Ocean Territory',
        currency: 'USD',
        path: 'british-indian-ocean-territory',
        iso2: 'IO',
        iso3: 'IOT',
        region: 'rest-of-the-world',
    },
    {
        id: 'IQ',
        type: 'country',
        title: 'Iraq',
        currency: 'IQD',
        path: 'iraq',
        iso2: 'IQ',
        iso3: 'IRQ',
        region: 'rest-of-the-world',
    },
    {
        id: 'IR',
        type: 'country',
        title: 'Iran',
        currency: 'IRR',
        path: 'iran',
        iso2: 'IR',
        iso3: 'IRN',
        region: 'rest-of-the-world',
    },
    {
        id: 'ISL',
        type: 'country',
        title: 'Iceland',
        currency: 'ISK',
        path: 'iceland',
        iso2: 'IS',
        iso3: 'ISL',
        region: 'europe',
    },
    {
        id: 'ITA',
        type: 'country',
        title: 'Italy',
        currency: 'EUR',
        path: 'italy',
        iso2: 'IT',
        iso3: 'ITA',
        region: 'europe',
    },
    {
        id: 'JE',
        type: 'country',
        title: 'Jersey',
        currency: 'GBP',
        path: 'jersey',
        iso2: 'JE',
        iso3: 'JEY',
        region: 'europe',
    },
    {
        id: 'JM',
        type: 'country',
        title: 'Jamaica',
        currency: 'JMD',
        path: 'jamaica',
        iso2: 'JM',
        iso3: 'JAM',
        region: 'latam',
    },
    {
        id: 'JO',
        type: 'country',
        title: 'Jordan',
        currency: 'JOD',
        path: 'jordan',
        iso2: 'JO',
        iso3: 'JOR',
        region: 'rest-of-the-world',
    },
    {
        id: 'JP',
        type: 'country',
        title: 'Japan',
        currency: 'JPY',
        path: 'japan',
        iso2: 'JP',
        iso3: 'JPN',
        region: 'rest-of-the-world',
    },
    {
        id: 'KE',
        type: 'country',
        title: 'Kenya',
        currency: 'KES',
        path: 'kenya',
        iso2: 'KE',
        iso3: 'KEN',
        region: 'rest-of-the-world',
    },
    {
        id: 'KG',
        type: 'country',
        title: 'Kyrgyzstan',
        currency: 'KGS',
        path: 'kyrgyzstan',
        iso2: 'KG',
        iso3: 'KGZ',
        region: 'rest-of-the-world',
    },
    {
        id: 'KH',
        type: 'country',
        title: 'Cambodia',
        currency: 'KHR',
        path: 'cambodia',
        iso2: 'KH',
        iso3: 'KHM',
        region: 'rest-of-the-world',
    },
    {
        id: 'KI',
        type: 'country',
        title: 'Kiribati',
        currency: 'AUD',
        path: 'kiribati',
        iso2: 'KI',
        iso3: 'KIR',
        region: 'rest-of-the-world',
    },
    {
        id: 'KM',
        type: 'country',
        title: 'Comoros',
        currency: 'KMF',
        path: 'comoros',
        iso2: 'KM',
        iso3: 'COM',
        region: 'rest-of-the-world',
    },
    {
        id: 'KN',
        type: 'country',
        title: 'Saint Kitts and Nevis',
        currency: 'XCD',
        path: 'saint-kitts-and-nevis',
        iso2: 'KN',
        iso3: 'KNA',
        region: 'latam',
    },
    {
        id: 'KP',
        type: 'country',
        title: 'North Korea',
        currency: 'KPW',
        path: 'north-korea',
        iso2: 'KP',
        iso3: 'PRK',
        region: 'rest-of-the-world',
    },
    {
        id: 'KR',
        type: 'country',
        title: 'South Korea',
        currency: 'KRW',
        path: 'south-korea',
        iso2: 'KR',
        iso3: 'KOR',
        region: 'rest-of-the-world',
    },
    {
        id: 'KW',
        type: 'country',
        title: 'Kuwait',
        currency: 'KWD',
        path: 'kuwait',
        iso2: 'KW',
        iso3: 'KWT',
        region: 'rest-of-the-world',
    },
    {
        id: 'KY',
        type: 'country',
        title: 'Cayman Islands',
        currency: 'KYD',
        path: 'cayman-islands',
        iso2: 'KY',
        iso3: 'CYM',
        region: 'north-america',
    },
    {
        id: 'KZ',
        type: 'country',
        title: 'Kazakhstan',
        currency: 'KZT',
        path: 'kazakhstan',
        iso2: 'KZ',
        iso3: 'KAZ',
        region: 'rest-of-the-world',
    },
    {
        id: 'LA',
        type: 'country',
        title: 'Laos',
        currency: 'LAK',
        path: 'laos',
        iso2: 'LA',
        iso3: 'LAO',
        region: 'rest-of-the-world',
    },
    {
        id: 'LB',
        type: 'country',
        title: 'Lebanon',
        currency: 'LBP',
        path: 'lebanon',
        iso2: 'LB',
        iso3: 'LBN',
        region: 'rest-of-the-world',
    },
    {
        id: 'LC',
        type: 'country',
        title: 'Saint Lucia',
        currency: 'XCD',
        path: 'saint-lucia',
        iso2: 'LC',
        iso3: 'LCA',
        region: 'latam',
    },
    {
        id: 'LI',
        type: 'country',
        title: 'Liechtenstein',
        currency: 'CHF',
        path: 'liechtenstein',
        iso2: 'LI',
        iso3: 'LIE',
        region: 'europe',
    },
    {
        id: 'LK',
        type: 'country',
        title: 'Sri Lanka',
        currency: 'LKR',
        path: 'sri-lanka',
        iso2: 'LK',
        iso3: 'LKA',
        region: 'rest-of-the-world',
    },
    {
        id: 'LR',
        type: 'country',
        title: 'Liberia',
        currency: 'LRD',
        path: 'liberia',
        iso2: 'LR',
        iso3: 'LBR',
        region: 'rest-of-the-world',
    },
    {
        id: 'LS',
        type: 'country',
        title: 'Lesotho',
        currency: 'LSL',
        path: 'lesotho',
        iso2: 'LS',
        iso3: 'LSO',
        region: 'rest-of-the-world',
    },
    {
        id: 'LTU',
        type: 'country',
        title: 'Lithuania',
        currency: 'EUR',
        path: 'lithuania',
        iso2: 'LT',
        iso3: 'LTU',
        region: 'europe',
    },
    {
        id: 'LUX',
        type: 'country',
        title: 'Luxembourg',
        currency: 'EUR',
        path: 'luxembourg',
        iso2: 'LU',
        iso3: 'LUX',
        region: 'europe',
    },
    {
        id: 'LVA',
        type: 'country',
        title: 'Latvia',
        currency: 'EUR',
        path: 'latvia',
        iso2: 'LV',
        iso3: 'LVA',
        region: 'europe',
    },
    {
        id: 'LY',
        type: 'country',
        title: 'Libya',
        currency: 'LYD',
        path: 'libya',
        iso2: 'LY',
        iso3: 'LBY',
        region: 'rest-of-the-world',
    },
    {
        id: 'MA',
        type: 'country',
        title: 'Morocco',
        currency: 'MAD',
        path: 'morocco',
        iso2: 'MA',
        iso3: 'MAR',
        region: 'rest-of-the-world',
    },
    {
        id: 'MC',
        type: 'country',
        title: 'Monaco',
        currency: 'EUR',
        path: 'monaco',
        iso2: 'MC',
        iso3: 'MCO',
        region: 'europe',
    },
    {
        id: 'MD',
        type: 'country',
        title: 'Moldova',
        currency: 'MDL',
        path: 'moldova',
        iso2: 'MD',
        iso3: 'MDA',
        region: 'europe',
    },
    {
        id: 'ME',
        type: 'country',
        title: 'Montenegro',
        currency: 'EUR',
        path: 'montenegro',
        iso2: 'ME',
        iso3: 'MNE',
        region: 'europe',
    },
    {
        id: 'MAF',
        type: 'country',
        title: 'Saint Martin',
        currency: 'EUR',
        path: 'saint-martin',
        iso2: 'MF',
        iso3: 'MAF',
        region: 'europe',
    },
    {
        id: 'MG',
        type: 'country',
        title: 'Madagascar',
        currency: 'MGA',
        path: 'madagascar',
        iso2: 'MG',
        iso3: 'MDG',
        region: 'rest-of-the-world',
    },
    {
        id: 'MH',
        type: 'country',
        title: 'Marshall Islands',
        currency: 'USD',
        path: 'marshall-islands',
        iso2: 'MH',
        iso3: 'MHL',
        region: 'rest-of-the-world',
    },
    {
        id: 'MK',
        type: 'country',
        title: 'Macedonia',
        currency: 'MKD',
        path: 'macedonia',
        iso2: 'MK',
        iso3: 'MKD',
        region: 'europe',
    },
    {
        id: 'ML',
        type: 'country',
        title: 'Mali',
        currency: 'XOF',
        path: 'mali',
        iso2: 'ML',
        iso3: 'MLI',
        region: 'rest-of-the-world',
    },
    {
        id: 'MM',
        type: 'country',
        title: 'Myanmar',
        currency: 'MMK',
        path: 'myanmar',
        iso2: 'MM',
        iso3: 'MMR',
        region: 'rest-of-the-world',
    },
    {
        id: 'MN',
        type: 'country',
        title: 'Mongolia',
        currency: 'MNT',
        path: 'mongolia',
        iso2: 'MN',
        iso3: 'MNG',
        region: 'rest-of-the-world',
    },
    {
        id: 'MO',
        type: 'country',
        title: 'Macao',
        currency: 'MOP',
        path: 'macao',
        iso2: 'MO',
        iso3: 'MAC',
        region: 'rest-of-the-world',
    },
    {
        id: 'MP',
        type: 'country',
        title: 'Northern Mariana Islands',
        currency: 'USD',
        path: 'northern-mariana-islands',
        iso2: 'MP',
        iso3: 'MNP',
        region: 'rest-of-the-world',
    },
    {
        id: 'MTQ',
        type: 'country',
        title: 'Martinique',
        currency: 'EUR',
        path: 'martinique',
        iso2: 'MQ',
        iso3: 'MTQ',
        region: 'europe',
    },
    {
        id: 'MR',
        type: 'country',
        title: 'Mauritania',
        currency: 'MRU',
        path: 'mauritania',
        iso2: 'MR',
        iso3: 'MRT',
        region: 'rest-of-the-world',
    },
    {
        id: 'MS',
        type: 'country',
        title: 'Montserrat',
        currency: 'XCD',
        path: 'montserrat',
        iso2: 'MS',
        iso3: 'MSR',
        region: 'rest-of-the-world',
    },
    {
        id: 'MLT',
        type: 'country',
        title: 'Malta',
        currency: 'EUR',
        path: 'malta',
        iso2: 'MT',
        iso3: 'MLT',
        region: 'europe',
    },
    {
        id: 'MU',
        type: 'country',
        title: 'Mauritius',
        currency: 'MUR',
        path: 'mauritius',
        iso2: 'MU',
        iso3: 'MUS',
        region: 'rest-of-the-world',
    },
    {
        id: 'MV',
        type: 'country',
        title: 'Maldives',
        currency: 'MVR',
        path: 'maldives',
        iso2: 'MV',
        iso3: 'MDV',
        region: 'rest-of-the-world',
    },
    {
        id: 'MW',
        type: 'country',
        title: 'Malawi',
        currency: 'MWK',
        path: 'malawi',
        iso2: 'MW',
        iso3: 'MWI',
        region: 'rest-of-the-world',
    },
    {
        id: 'MX',
        type: 'country',
        title: 'Mexico',
        currency: 'MXN',
        path: 'mexico',
        iso2: 'MX',
        iso3: 'MEX',
        region: 'latam',
    },
    {
        id: 'MY',
        type: 'country',
        title: 'Malaysia',
        currency: 'MYR',
        path: 'malaysia',
        iso2: 'MY',
        iso3: 'MYS',
        region: 'rest-of-the-world',
    },
    {
        id: 'MZ',
        type: 'country',
        title: 'Mozambique',
        currency: 'MZN',
        path: 'mozambique',
        iso2: 'MZ',
        iso3: 'MOZ',
        region: 'rest-of-the-world',
    },
    {
        id: 'NA',
        type: 'country',
        title: 'Namibia',
        currency: 'NAD',
        path: 'namibia',
        iso2: 'NA',
        iso3: 'NAM',
        region: 'rest-of-the-world',
    },
    {
        id: 'NC',
        type: 'country',
        title: 'New Caledonia',
        currency: 'XPF',
        path: 'new-caledonia',
        iso2: 'NC',
        iso3: 'NCL',
        region: 'rest-of-the-world',
    },
    {
        id: 'NE',
        type: 'country',
        title: 'Niger',
        currency: 'XOF',
        path: 'niger',
        iso2: 'NE',
        iso3: 'NER',
        region: 'rest-of-the-world',
    },
    {
        id: 'NF',
        type: 'country',
        title: 'Norfolk Island',
        currency: 'AUD',
        path: 'norfolk-island',
        iso2: 'NF',
        iso3: 'NFK',
        region: 'rest-of-the-world',
    },
    {
        id: 'NG',
        type: 'country',
        title: 'Nigeria',
        currency: 'NGN',
        path: 'nigeria',
        iso2: 'NG',
        iso3: 'NGA',
        region: 'rest-of-the-world',
    },
    {
        id: 'NI',
        type: 'country',
        title: 'Nicaragua',
        currency: 'NIO',
        path: 'nicaragua',
        iso2: 'NI',
        iso3: 'NIC',
        region: 'latam',
    },
    {
        id: 'NLD',
        type: 'country',
        title: 'Netherlands',
        currency: 'EUR',
        path: 'netherlands',
        iso2: 'NL',
        iso3: 'NLD',
        region: 'europe',
    },
    {
        id: 'NOR',
        type: 'country',
        title: 'Norway',
        currency: 'NOK',
        path: 'norway',
        iso2: 'NO',
        iso3: 'NOR',
        region: 'europe',
    },
    {
        id: 'NP',
        type: 'country',
        title: 'Nepal',
        currency: 'NPR',
        path: 'nepal',
        iso2: 'NP',
        iso3: 'NPL',
        region: 'rest-of-the-world',
    },
    {
        id: 'NR',
        type: 'country',
        title: 'Nauru',
        currency: 'AUD',
        path: 'nauru',
        iso2: 'NR',
        iso3: 'NRU',
        region: 'rest-of-the-world',
    },
    {
        id: 'NU',
        type: 'country',
        title: 'Niue',
        currency: 'NZD',
        path: 'niue',
        iso2: 'NU',
        iso3: 'NIU',
        region: 'rest-of-the-world',
    },
    {
        id: 'NZ',
        type: 'country',
        title: 'New Zealand',
        currency: 'NZD',
        path: 'new-zealand',
        iso2: 'NZ',
        iso3: 'NZL',
        region: 'rest-of-the-world',
    },
    {
        id: 'OM',
        type: 'country',
        title: 'Oman',
        currency: 'OMR',
        path: 'oman',
        iso2: 'OM',
        iso3: 'OMN',
        region: 'rest-of-the-world',
    },
    {
        id: 'PA',
        type: 'country',
        title: 'Panama',
        currency: 'PAB',
        path: 'panama',
        iso2: 'PA',
        iso3: 'PAN',
        region: 'latam',
    },
    {
        id: 'PE',
        type: 'country',
        title: 'Peru',
        currency: 'PEN',
        path: 'peru',
        iso2: 'PE',
        iso3: 'PER',
        region: 'latam',
    },
    {
        id: 'PF',
        type: 'country',
        title: 'French Polynesia',
        currency: 'XPF',
        path: 'french-polynesia',
        iso2: 'PF',
        iso3: 'PYF',
        region: 'rest-of-the-world',
    },
    {
        id: 'PG',
        type: 'country',
        title: 'Papua New Guinea',
        currency: 'PGK',
        path: 'papua-new-guinea',
        iso2: 'PG',
        iso3: 'PNG',
        region: 'rest-of-the-world',
    },
    {
        id: 'PH',
        type: 'country',
        title: 'Philippines',
        currency: 'PHP',
        path: 'philippines',
        iso2: 'PH',
        iso3: 'PHL',
        region: 'rest-of-the-world',
    },
    {
        id: 'PK',
        type: 'country',
        title: 'Pakistan',
        currency: 'PKR',
        path: 'pakistan',
        iso2: 'PK',
        iso3: 'PAK',
        region: 'rest-of-the-world',
    },
    {
        id: 'PL',
        type: 'country',
        title: 'Poland',
        currency: 'PLN',
        path: 'poland',
        iso2: 'PL',
        iso3: 'POL',
        region: 'europe',
    },
    {
        id: 'PM',
        type: 'country',
        title: 'Saint Pierre and Miquelon',
        currency: 'EUR',
        path: 'saint-pierre-and-miquelon',
        iso2: 'PM',
        iso3: 'SPM',
        region: 'north-america',
    },
    {
        id: 'PN',
        type: 'country',
        title: 'Pitcairn Islands',
        currency: 'NZD',
        path: 'pitcairn-islands',
        iso2: 'PN',
        iso3: 'PCN',
        region: 'rest-of-the-world',
    },
    {
        id: 'PR',
        type: 'country',
        title: 'Puerto Rico',
        currency: 'USD',
        path: 'puerto-rico',
        iso2: 'PR',
        iso3: 'PRI',
        region: 'latam',
    },
    {
        id: 'PS',
        type: 'country',
        title: 'Palestine',
        currency: 'ILS',
        path: 'palestine',
        iso2: 'PS',
        iso3: 'PSE',
        region: 'rest-of-the-world',
    },
    {
        id: 'PRT',
        type: 'country',
        title: 'Portugal',
        currency: 'EUR',
        path: 'portugal',
        iso2: 'PT',
        iso3: 'PRT',
        region: 'europe',
    },
    {
        id: 'PW',
        type: 'country',
        title: 'Palau',
        currency: 'USD',
        path: 'palau',
        iso2: 'PW',
        iso3: 'PLW',
        region: 'rest-of-the-world',
    },
    {
        id: 'PY',
        type: 'country',
        title: 'Paraguay',
        currency: 'PYG',
        path: 'paraguay',
        iso2: 'PY',
        iso3: 'PRY',
        region: 'latam',
    },
    {
        id: 'QA',
        type: 'country',
        title: 'Qatar',
        currency: 'QAR',
        path: 'qatar',
        iso2: 'QA',
        iso3: 'QAT',
        region: 'rest-of-the-world',
    },
    {
        id: 'REU',
        type: 'country',
        title: 'Réunion',
        currency: 'EUR',
        path: 'reunion',
        iso2: 'RE',
        iso3: 'REU',
        region: 'europe',
    },
    {
        id: 'ROU',
        type: 'country',
        title: 'Romania',
        currency: 'RON',
        path: 'romania',
        iso2: 'RO',
        iso3: 'ROU',
        region: 'europe',
    },
    {
        id: 'RS',
        type: 'country',
        title: 'Serbia',
        currency: 'RSD',
        path: 'serbia',
        iso2: 'RS',
        iso3: 'SRB',
        region: 'europe',
    },
    {
        id: 'RU',
        type: 'country',
        title: 'Russia',
        currency: 'RUB',
        path: 'russia',
        iso2: 'RU',
        iso3: 'RUS',
        region: 'europe',
    },
    {
        id: 'RW',
        type: 'country',
        title: 'Rwanda',
        currency: 'RWF',
        path: 'rwanda',
        iso2: 'RW',
        iso3: 'RWA',
        region: 'rest-of-the-world',
    },
    {
        id: 'SA',
        type: 'country',
        title: 'Saudi Arabia',
        currency: 'SAR',
        path: 'saudi-arabia',
        iso2: 'SA',
        iso3: 'SAU',
        region: 'rest-of-the-world',
    },
    {
        id: 'SB',
        type: 'country',
        title: 'Solomon Islands',
        currency: 'SBD',
        path: 'solomon-islands',
        iso2: 'SB',
        iso3: 'SLB',
        region: 'rest-of-the-world',
    },
    {
        id: 'SC',
        type: 'country',
        title: 'Seychelles',
        currency: 'SCR',
        path: 'seychelles',
        iso2: 'SC',
        iso3: 'SYC',
        region: 'rest-of-the-world',
    },
    {
        id: 'SD',
        type: 'country',
        title: 'Sudan',
        currency: 'SDG',
        path: 'sudan',
        iso2: 'SD',
        iso3: 'SDN',
        region: 'rest-of-the-world',
    },
    {
        id: 'SE',
        type: 'country',
        title: 'Sweden',
        currency: 'SEK',
        path: 'sweden',
        iso2: 'SE',
        iso3: 'SWE',
        region: 'europe',
    },
    {
        id: 'SG',
        type: 'country',
        title: 'Singapore',
        currency: 'SGD',
        path: 'singapore',
        iso2: 'SG',
        iso3: 'SGP',
        region: 'rest-of-the-world',
    },
    {
        id: 'SH',
        type: 'country',
        title: 'Saint Helena',
        currency: 'SHP',
        path: 'saint-helena',
        iso2: 'SH',
        iso3: 'SHN',
        region: 'rest-of-the-world',
    },
    {
        id: 'SVN',
        type: 'country',
        title: 'Slovenia',
        currency: 'EUR',
        path: 'slovenia',
        iso2: 'SI',
        iso3: 'SVN',
        region: 'europe',
    },
    {
        id: 'SJ',
        type: 'country',
        title: 'Svalbard and Jan Mayen',
        currency: 'NOK',
        path: 'svalbard-and-jan-mayen',
        iso2: 'SJ',
        iso3: 'SJM',
        region: 'europe',
    },
    {
        id: 'SVK',
        type: 'country',
        title: 'Slovakia',
        currency: 'EUR',
        path: 'slovakia',
        iso2: 'SK',
        iso3: 'SVK',
        region: 'europe',
    },
    {
        id: 'SL',
        type: 'country',
        title: 'Sierra Leone',
        currency: 'SLL',
        path: 'sierra-leone',
        iso2: 'SL',
        iso3: 'SLE',
        region: 'rest-of-the-world',
    },
    {
        id: 'SM',
        type: 'country',
        title: 'San Marino',
        currency: 'EUR',
        path: 'san-marino',
        iso2: 'SM',
        iso3: 'SMR',
        region: 'europe',
    },
    {
        id: 'SN',
        type: 'country',
        title: 'Senegal',
        currency: 'XOF',
        path: 'senegal',
        iso2: 'SN',
        iso3: 'SEN',
        region: 'rest-of-the-world',
    },
    {
        id: 'SO',
        type: 'country',
        title: 'Somalia',
        currency: 'SOS',
        path: 'somalia',
        iso2: 'SO',
        iso3: 'SOM',
        region: 'rest-of-the-world',
    },
    {
        id: 'SR',
        type: 'country',
        title: 'Suriname',
        currency: 'SRD',
        path: 'suriname',
        iso2: 'SR',
        iso3: 'SUR',
        region: 'latam',
    },
    {
        id: 'SS',
        type: 'country',
        title: 'South Sudan',
        currency: 'SSP',
        path: 'south-sudan',
        iso2: 'SS',
        iso3: 'SSD',
        region: 'rest-of-the-world',
    },
    {
        id: 'ST',
        type: 'country',
        title: 'São Tomé and Príncipe',
        currency: 'STD',
        path: 'sao-tome-and-principe',
        iso2: 'ST',
        iso3: 'STP',
        region: 'rest-of-the-world',
    },
    {
        id: 'SV',
        type: 'country',
        title: 'El Salvador',
        currency: 'USD',
        path: 'el-salvador',
        iso2: 'SV',
        iso3: 'SLV',
        region: 'latam',
    },
    {
        id: 'SX',
        type: 'country',
        title: 'Sint Maarten',
        currency: 'ANG',
        path: 'sint-maarten',
        iso2: 'SX',
        iso3: 'SXM',
        region: 'north-america',
    },
    {
        id: 'SY',
        type: 'country',
        title: 'Syria',
        currency: 'SYP',
        path: 'syria',
        iso2: 'SY',
        iso3: 'SYR',
        region: 'rest-of-the-world',
    },
    {
        id: 'SZ',
        type: 'country',
        title: 'Swaziland',
        currency: 'SZL',
        path: 'swaziland',
        iso2: 'SZ',
        iso3: 'SWZ',
        region: 'rest-of-the-world',
    },
    {
        id: 'TC',
        type: 'country',
        title: 'Turks and Caicos Islands',
        currency: 'USD',
        path: 'turks-and-caicos-islands',
        iso2: 'TC',
        iso3: 'TCA',
        region: 'north-america',
    },
    {
        id: 'TD',
        type: 'country',
        title: 'Chad',
        currency: 'XAF',
        path: 'chad',
        iso2: 'TD',
        iso3: 'TCD',
        region: 'rest-of-the-world',
    },
    {
        id: 'TF',
        type: 'country',
        title: 'French Southern Territories',
        currency: 'EUR',
        path: 'french-southern-territories',
        iso2: 'TF',
        iso3: 'ATF',
        region: 'rest-of-the-world',
    },
    {
        id: 'TG',
        type: 'country',
        title: 'Togo',
        currency: 'XOF',
        path: 'togo',
        iso2: 'TG',
        iso3: 'TGO',
        region: 'rest-of-the-world',
    },
    {
        id: 'TH',
        type: 'country',
        title: 'Thailand',
        currency: 'THB',
        path: 'thailand',
        iso2: 'TH',
        iso3: 'THA',
        region: 'rest-of-the-world',
    },
    {
        id: 'TJ',
        type: 'country',
        title: 'Tajikistan',
        currency: 'TJS',
        path: 'tajikistan',
        iso2: 'TJ',
        iso3: 'TJK',
        region: 'rest-of-the-world',
    },
    {
        id: 'TK',
        type: 'country',
        title: 'Tokelau',
        currency: 'NZD',
        path: 'tokelau',
        iso2: 'TK',
        iso3: 'TKL',
        region: 'rest-of-the-world',
    },
    {
        id: 'TL',
        type: 'country',
        title: 'East Timor',
        currency: 'USD',
        path: 'east-timor',
        iso2: 'TL',
        iso3: 'TLS',
        region: 'rest-of-the-world',
    },
    {
        id: 'TM',
        type: 'country',
        title: 'Turkmenistan',
        currency: 'TMT',
        path: 'turkmenistan',
        iso2: 'TM',
        iso3: 'TKM',
        region: 'rest-of-the-world',
    },
    {
        id: 'TN',
        type: 'country',
        title: 'Tunisia',
        currency: 'TND',
        path: 'tunisia',
        iso2: 'TN',
        iso3: 'TUN',
        region: 'rest-of-the-world',
    },
    {
        id: 'TO',
        type: 'country',
        title: 'Tonga',
        currency: 'TOP',
        path: 'tonga',
        iso2: 'TO',
        iso3: 'TON',
        region: 'rest-of-the-world',
    },
    {
        id: 'TR',
        type: 'country',
        title: 'Turkey',
        currency: 'TRY',
        path: 'turkey',
        iso2: 'TR',
        iso3: 'TUR',
        region: 'rest-of-the-world',
    },
    {
        id: 'TT',
        type: 'country',
        title: 'Trinidad and Tobago',
        currency: 'TTD',
        path: 'trinidad-and-tobago',
        iso2: 'TT',
        iso3: 'TTO',
        region: 'rest-of-the-world',
    },
    {
        id: 'TV',
        type: 'country',
        title: 'Tuvalu',
        currency: 'AUD',
        path: 'tuvalu',
        iso2: 'TV',
        iso3: 'TUV',
        region: 'rest-of-the-world',
    },
    {
        id: 'TW',
        type: 'country',
        title: 'Taiwan',
        currency: 'TWD',
        path: 'taiwan',
        iso2: 'TW',
        iso3: 'TWN',
        region: 'rest-of-the-world',
    },
    {
        id: 'TZ',
        type: 'country',
        title: 'Tanzania',
        currency: 'TZS',
        path: 'tanzania',
        iso2: 'TZ',
        iso3: 'TZA',
        region: 'rest-of-the-world',
    },
    {
        id: 'UA',
        type: 'country',
        title: 'Ukraine',
        currency: 'UAH',
        path: 'ukraine',
        iso2: 'UA',
        iso3: 'UKR',
        region: 'europe',
    },
    {
        id: 'UG',
        type: 'country',
        title: 'Uganda',
        currency: 'UGX',
        path: 'uganda',
        iso2: 'UG',
        iso3: 'UGA',
        region: 'rest-of-the-world',
    },
    {
        id: 'UM',
        type: 'country',
        title: 'U.S. Minor Outlying Islands',
        currency: 'USD',
        path: 'u.s.-minor-outlying-islands',
        iso2: 'UM',
        iso3: 'UMI',
        region: 'north-america',
    },
    {
        id: 'US',
        type: 'country',
        title: 'United States',
        currency: 'USD',
        path: 'usa',
        iso2: 'US',
        iso3: 'USA',
        region: 'north-america',
    },
    {
        id: 'UY',
        type: 'country',
        title: 'Uruguay',
        currency: 'UYU',
        path: 'uruguay',
        iso2: 'UY',
        iso3: 'URY',
        region: 'latam',
    },
    {
        id: 'UZ',
        type: 'country',
        title: 'Uzbekistan',
        currency: 'UZS',
        path: 'uzbekistan',
        iso2: 'UZ',
        iso3: 'UZB',
        region: 'rest-of-the-world',
    },
    {
        id: 'VA',
        type: 'country',
        title: 'Vatican City',
        currency: 'EUR',
        path: 'vatican-city',
        iso2: 'VA',
        iso3: 'VAT',
        region: 'europe',
    },
    {
        id: 'VC',
        type: 'country',
        title: 'Saint Vincent and the Grenadines',
        currency: 'XCD',
        path: 'saint-vincent-and-the-grenadines',
        iso2: 'VC',
        iso3: 'VCT',
        region: 'latam',
    },
    {
        id: 'VE',
        type: 'country',
        title: 'Venezuela',
        currency: 'VES',
        path: 'venezuela',
        iso2: 'VE',
        iso3: 'VEN',
        region: 'latam',
    },
    {
        id: 'VG',
        type: 'country',
        title: 'British Virgin Islands',
        currency: 'USD',
        path: 'british-virgin-islands',
        iso2: 'VG',
        iso3: 'VGB',
        region: 'north-america',
    },
    {
        id: 'VI',
        type: 'country',
        title: 'U.S. Virgin Islands',
        currency: 'USD',
        path: 'us-virgin-islands',
        iso2: 'VI',
        iso3: 'VIR',
        region: 'north-america',
    },
    {
        id: 'VN',
        type: 'country',
        title: 'Vietnam',
        currency: 'VND',
        path: 'vietnam',
        iso2: 'VN',
        iso3: 'VNM',
        region: 'rest-of-the-world',
    },
    {
        id: 'VU',
        type: 'country',
        title: 'Vanuatu',
        currency: 'VUV',
        path: 'vanuatu',
        iso2: 'VU',
        iso3: 'VUT',
        region: 'rest-of-the-world',
    },
    {
        id: 'WF',
        type: 'country',
        title: 'Wallis and Futuna',
        currency: 'XPF',
        path: 'wallis-and-futuna',
        iso2: 'WF',
        iso3: 'WLF',
        region: 'rest-of-the-world',
    },
    {
        id: 'WS',
        type: 'country',
        title: 'Samoa',
        currency: 'WST',
        path: 'samoa',
        iso2: 'WS',
        iso3: 'WSM',
        region: 'rest-of-the-world',
    },
    {
        id: 'XK',
        type: 'country',
        title: 'Kosovo',
        currency: 'EUR',
        path: 'kosovo',
        iso2: 'XK',
        iso3: 'XKX',
        region: 'europe',
    },
    {
        id: 'YE',
        type: 'country',
        title: 'Yemen',
        currency: 'YER',
        path: 'yemen',
        iso2: 'YE',
        iso3: 'YEM',
        region: 'rest-of-the-world',
    },
    {
        id: 'YT',
        type: 'country',
        title: 'Mayotte',
        currency: 'EUR',
        path: 'mayotte',
        iso2: 'YT',
        iso3: 'MYT',
        region: 'europe',
    },
    {
        id: 'ZA',
        type: 'country',
        title: 'South Africa',
        currency: 'ZAR',
        path: 'south-africa',
        iso2: 'ZA',
        iso3: 'ZAF',
        region: 'rest-of-the-world',
    },
    {
        id: 'ZM',
        type: 'country',
        title: 'Zambia',
        currency: 'ZMW',
        path: 'zambia',
        iso2: 'ZM',
        iso3: 'ZMB',
        region: 'rest-of-the-world',
    },
    {
        id: 'ZW',
        type: 'country',
        title: 'Zimbabwe',
        currency: 'ZWL',
        path: 'zimbabwe',
        iso2: 'ZW',
        iso3: 'ZWE',
        region: 'rest-of-the-world',
    },
]

export const COUNTRY_SPECIFIC_METHODS: Record<string, CountrySpecificMethods> = {}

// LATAM country codes
const LATAM_COUNTRY_CODES = [
    'AR',
    'BO',
    'BR',
    'CL',
    'CO',
    'CR',
    'CU',
    'DO',
    'EC',
    'SV',
    'GT',
    'HN',
    'HT',
    'MX',
    'NI',
    'PA',
    'PY',
    'PE',
    'PR',
    'UY',
    'VE',
]

// bridge EAA country codes, source: https://apidocs.bridge.xyz/docs/sepa-euro-transactions
// note: this is a map of 3-letter country codes to 2-letter country codes, for flags to work, bridge expects 3 letter codes
export const BRIDGE_ALPHA3_TO_ALPHA2: { [key: string]: string } = {
    ALA: 'AX',
    AND: 'AD',
    AUT: 'AT',
    BEL: 'BE',
    BGR: 'BG',
    HRV: 'HR',
    CYP: 'CY',
    CZE: 'CZ',
    DNK: 'DK',
    EST: 'EE',
    FIN: 'FI',
    FRA: 'FR',
    GUF: 'GF',
    DEU: 'DE',
    GRC: 'GR',
    GLP: 'GP',
    HUN: 'HU',
    ISL: 'IS',
    IRL: 'IE',
    ITA: 'IT',
    LVA: 'LV',
    LIE: 'LI',
    LTU: 'LT',
    LUX: 'LU',
    MLT: 'MT',
    MTQ: 'MQ',
    MYT: 'YT',
    NLD: 'NL',
    NOR: 'NO',
    POL: 'PL',
    PRT: 'PT',
    REU: 'RE',
    ROU: 'RO',
    MAF: 'MF',
    SVK: 'SK',
    SVN: 'SI',
    ESP: 'ES',
    SWE: 'SE',
    CHE: 'CH',
    GBR: 'GB',
    USA: 'US',
}

export const MEXICO_ALPHA3_TO_ALPHA2: { [key: string]: string } = {
    MEX: 'MX',
}

export const MANTECA_ALPHA3_TO_ALPHA2: { [key: string]: string } = {
    ARG: 'AR',
    BRA: 'BR',
}

export const UNSUPPORTED_ALPHA3_TO_ALPHA2: { [key: string]: string } = {
    AFG: 'AF',
    BLR: 'BY',
    COD: 'CD',
    CUB: 'CU',
    PSE: 'PS',
    IRN: 'IR',
    IRQ: 'IQ',
    LBN: 'LB',
    LBY: 'LY',
    MMR: 'MM',
    PRK: 'KP',
    RUS: 'RU',
    SOM: 'SO',
    SSD: 'SS',
    SDN: 'SD',
    SYR: 'SY',
    YEM: 'YE',
}

export const ALL_COUNTRIES_ALPHA3_TO_ALPHA2: { [key: string]: string } = {
    ...BRIDGE_ALPHA3_TO_ALPHA2,
    ...MANTECA_ALPHA3_TO_ALPHA2,
}

// identify sepa corridors where local currency is not eur and disable them temporarily for bank withdrawals
// this impacts withdraw and claim-to-bank flows (but not add-money from bank)
export const NON_EUR_SEPA_ALPHA2 = new Set(
    countryData
        .filter(
            (c) =>
                c.type === 'country' &&
                !!c.iso3 &&
                BRIDGE_ALPHA3_TO_ALPHA2[c.iso3] &&
                // exclude usa explicitly; bridge map includes it but it's not sepa
                c.iso3 !== 'USA'
        )
        .map((c) => ({ alpha2: BRIDGE_ALPHA3_TO_ALPHA2[c.iso3!], currency: c.currency }))
        .filter((x) => x.alpha2 && x.currency && x.currency !== 'EUR')
        .map((x) => x.alpha2 as string)
)

const enabledBankWithdrawCountries = new Set([...Object.values(BRIDGE_ALPHA3_TO_ALPHA2), 'US', 'MX', 'AR'])

// exclude non-euro sepa countries from bank deposits, same as withdrawals
const enabledBankDepositCountries = new Set([...Object.values(BRIDGE_ALPHA3_TO_ALPHA2), 'US', 'MX', 'AR'])

// Helper function to check if a country code is enabled for bank transfers
// Handles both 2-letter and 3-letter country codes
const isCountryEnabledForBankTransfer = (countryCode: string, direction: 'withdraw' | 'deposit'): boolean => {
    // Direct check for 2-letter codes
    const enabledCountries = direction === 'withdraw' ? enabledBankWithdrawCountries : enabledBankDepositCountries
    if (enabledCountries.has(countryCode)) {
        return true
    }

    // Check if it's a 3-letter code that maps to an enabled 2-letter code
    const mappedCode = ALL_COUNTRIES_ALPHA3_TO_ALPHA2[countryCode]
    return mappedCode ? enabledCountries.has(mappedCode) : false
}

countryData.forEach((country) => {
    if (country.type === 'country') {
        const countryCode = country.id
        const countryTitle = country.title

        const withdrawList: SpecificPaymentMethod[] = []

        // 1. add specific country withdrawal methods
        const specificMethodDetails = countrySpecificWithdrawMethods[countryTitle]
        if (specificMethodDetails && specificMethodDetails.length > 0) {
            specificMethodDetails.forEach((method) => {
                const methodId = `${countryCode.toLowerCase()}-${method.title.toLowerCase().replace(/\s+/g, '-')}-withdraw`

                // Check if this is a Manteca country to add appropriate routing
                const isMantecaCountry = [
                    'argentina',
                    'chile',
                    'brazil',
                    'colombia',
                    'panama',
                    'costa-rica',
                    'guatemala',
                    'philippines',
                    'bolivia',
                ].includes(country.path)

                withdrawList.push({
                    id: methodId,
                    icon: method.icon ?? undefined,
                    title: method.title,
                    description: method.description,
                    isSoon: method.isSoon ?? true,
                    // Add path for Manteca countries to route to Manteca flow
                    path: isMantecaCountry
                        ? `/withdraw/manteca?method=${method.title.toLowerCase().replace(/\s+/g, '-')}&country=${country.path}`
                        : undefined,
                })
            })
        }

        // 2. add SEPA for EUR countries if not already present from specifics
        if (country.currency === 'EUR' && countrySpecificWithdrawMethods['Germany']) {
            // Germany as proxy for SEPA availability
            const sepaExists = withdrawList.some((m) => m.title === 'SEPA Instant')
            if (!sepaExists) {
                withdrawList.push({
                    id: `${countryCode.toLowerCase()}-sepa-instant-withdraw`,
                    icon: 'bank' as IconName,
                    title: 'SEPA Instant',
                    description: 'EU-wide real-time bank transfers.',
                    isSoon: false,
                })
            }
        }

        // 3. add DEFAULT_BANK_WITHDRAW_METHOD if an identical method (by title and icon) is not already present
        // AND if SEPA was added, don't add default bank
        const defaultBankTitle = DEFAULT_BANK_WITHDRAW_METHOD.title
        const defaultBankIcon = DEFAULT_BANK_WITHDRAW_METHOD.icon

        const sepaWasAdded = withdrawList.some((m) => m.id.endsWith('-sepa-instant-withdraw'))

        const genericBankExists = withdrawList.some((m) => m.title === defaultBankTitle && m.icon === defaultBankIcon)

        // only add default bank if it doesn't already exist AND (SEPA was not added OR it's not considered redundant by SEPA)
        // for now, we simplify: if SEPA was added, we assume default bank is redundant.
        if (!genericBankExists && !sepaWasAdded) {
            const isMantecaCountry = [
                'argentina',
                'chile',
                'brazil',
                'colombia',
                'panama',
                'costa-rica',
                'guatemala',
                'philippines',
                'bolivia',
            ].includes(country.path)

            withdrawList.push({
                ...DEFAULT_BANK_WITHDRAW_METHOD,
                id: `${countryCode.toLowerCase()}-default-bank-withdraw`,
                path: isMantecaCountry
                    ? `/withdraw/manteca?method=bank-transfer&country=${country.path}`
                    : `/withdraw/${countryCode.toLowerCase()}/bank`,
                isSoon: !isCountryEnabledForBankTransfer(countryCode, 'withdraw'),
            })
        }

        const cryptoWithdrawMethod = DEFAULT_WITHDRAW_METHODS.find((m) => m.id === 'crypto-withdraw')
        if (cryptoWithdrawMethod) {
            const cryptoExists = withdrawList.some((m) => m.id === 'crypto-withdraw')
            if (!cryptoExists) {
                withdrawList.unshift(cryptoWithdrawMethod)
            }
        }

        // filter add methods: include Mercado Pago only for LATAM countries
        const currentAddMethods = UPDATED_DEFAULT_ADD_MONEY_METHODS.filter((method) => {
            if (method.id === 'mercado-pago-add') {
                return countryCode === 'AR'
            }
            if (method.id === 'pix-add') {
                return countryCode === 'BR'
            }
            return true
        }).map((m) => {
            const newMethod = { ...m }
            if (newMethod.id === 'bank-transfer-add') {
                if (MantecaSupportedExchanges[countryCode as keyof typeof MantecaSupportedExchanges]) {
                    newMethod.path = `/add-money/${country.path}/manteca`
                } else {
                    newMethod.path = `/add-money/${country.path}/bank`
                }
                newMethod.isSoon = !isCountryEnabledForBankTransfer(countryCode, 'deposit')
            }
            return newMethod
        })

        COUNTRY_SPECIFIC_METHODS[countryCode] = {
            add: currentAddMethods,
            withdraw: withdrawList,
        }
    }
})
