import chillPeanutAnim from '@/animations/GIF_ALPHA_BACKGORUND/512X512_ALPHA_GIF_konradurban_01.gif'
import happyPeanutAnim from '@/animations/GIF_ALPHA_BACKGORUND/512X512_ALPHA_GIF_konradurban_03.gif'
import { ISetupStep } from '@/components/Setup/Setup.types'
import {
    AddWallets,
    InstallPWA,
    NotificationPermission,
    PasskeySuccess,
    SetupPasskey,
    SetupSuccess,
    SignupStep,
    WelcomeStep,
} from '@/components/Setup/Views'

export const setupSteps: ISetupStep[] = [
    {
        screenId: 'welcome',
        layoutType: 'welcome',
        title: 'Access Dollars Easily',
        description: 'Peanut wallet is the easiest way to receive and spend digital dollars.',
        image: chillPeanutAnim.src,
        component: WelcomeStep,
        showBackButton: false,
        showSkipButton: false,
    },
    {
        screenId: 'signup',
        layoutType: 'signup',
        title: 'Sign up',
        image: chillPeanutAnim.src,
        component: SignupStep,
        showBackButton: true,
        showSkipButton: false,
    },
    {
        screenId: 'passkey-permission',
        layoutType: 'standard',
        title: `Let's setup passkeys`,
        description: `Use your face or fingerprint to verify it's you. There's no need for a password.`,
        image: 'https://s3-alpha-sig.figma.com/img/fcc8/7d9e/52f8872d61a2df38a2525722f41e2d25?Expires=1736121600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=YcIU-EADfTDAIWIX2rdkXAokxsYhzcSMP0p0Vaj7mzHJRqrEekkuOorIiJnYiASPTbHAl~zEFixAVAKQ~G0VJP4DfbpdhSVSM897QpvLS6JS4JDF9ozgMPu1I3036UJeiDoIcomI1Z6RycoPtLOgGw-3gdtYWf2yl8eksUuTOpb21skcmFiGmj4oiOTlfppWrXq-PrkvDMhNDcXRX1PP44Hc2H6x2mKCvNArCv90~hDDoh9oyBz1l24vxZuG38YTPIxpr8nTWsvKTPpmuybUvHiWNo3~RpPkGezdO3EP9Dj7ZHUtgbvlKuNUwwEmf94DWvfVNqsEopHq2VM6g3-spw__',
        component: SetupPasskey,
        showBackButton: true,
        showSkipButton: false,
    },
    {
        screenId: 'passkey-success',
        layoutType: 'standard',
        title: `Your Passkey is already setup now`,
        description: `Use your face or fingerprint to verify it's you. There's no need for a password.`,
        image: 'https://s3-alpha-sig.figma.com/img/e086/9fce/1967d88a6e8f75c882240879eb14c23e?Expires=1736121600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=YGygvtcricxKOAZOdua2jxq-oz46RuV~haLYJUTAqRl7eVE6j9kMF6Uhub~HmfpWAbHaE6ek~2WkB-NVyVeAKlq~9qg-YICB8upWECQrNj0MwQ0EKY4~3e~oW-EIEP5OmA~-6xrlzlLpuK8xYz5eMcJAsNdlbxzLTWpfO-En2UOGMlCrrXjwoxqNjQDSyOruOyAFjtxDRh-bd5qVnZUJddjj5LPs7q4HvmemzFFi0i4JP5dyzWG6x7zGzMCHZ-gLqS-ZQTAqFJYqCbHgHgnMswOrgFFoaJeoGXFhHBd6OuBNaies4iI5xUDF5rYC-N0BaP-2jWK0lyHoa-Ry2VXk8A__',
        component: PasskeySuccess,
        showBackButton: true,
        showSkipButton: false,
    },
    {
        screenId: 'notification-permission',
        layoutType: 'standard',
        title: 'Enable notification',
        description: 'Get notified about incoming and outgoing of payments.',
        image: chillPeanutAnim.src,
        component: NotificationPermission,
        showBackButton: true,
        showSkipButton: true,
    },
    {
        screenId: 'pwa-install',
        layoutType: 'standard',
        title: 'Install Peanut wallet App in your phone',
        description: 'You can directly use app from Homescreen on your phone.',
        image: 'https://s3-alpha-sig.figma.com/img/f240/a52b/160e0080df558149c8ff309ba2959519?Expires=1736121600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=bvem~RVYShN57Oo7dgn2Pi~WIeMEN8ycv0OPaULoYkAG7xsbo-j~NxTNBgaDPnEfk76S7CKHFJz-1pjg7ohAwygKBe2ZDR3Ggepovz7fgYoep8X9E70HMXwJWFChtL~q9GAq78IoYH3Dm2LHNjeqPYOHoPqH5v3cYbuKJqAVk6JZYC3uU9b1JHNSW4SheZKNawJ6ftCQtEGAN6OByOvpb0u2m8apD33SkaOK0lmIQC4I3DB0Wd6kLU-Eqg6elwXb9Xpe45pcNRknncWGP0msTaBPorZMbdWr7Smg2hMSI--bJbYwqLevgH5d8~uGaBj4MaFncYAR3-4M-kXbMqk1QQ__',
        component: InstallPWA,
        showBackButton: true,
        showSkipButton: true,
    },
    {
        screenId: 'add-wallets',
        layoutType: 'standard',
        title: 'Add extra wallet',
        description: 'Have another wallet? Add it here to keep everything in one place.',
        image: 'https://s3-alpha-sig.figma.com/img/f240/a52b/160e0080df558149c8ff309ba2959519?Expires=1736121600&Key-Pair-Id=APKAQ4GOSFWCVNEHN3O4&Signature=bvem~RVYShN57Oo7dgn2Pi~WIeMEN8ycv0OPaULoYkAG7xsbo-j~NxTNBgaDPnEfk76S7CKHFJz-1pjg7ohAwygKBe2ZDR3Ggepovz7fgYoep8X9E70HMXwJWFChtL~q9GAq78IoYH3Dm2LHNjeqPYOHoPqH5v3cYbuKJqAVk6JZYC3uU9b1JHNSW4SheZKNawJ6ftCQtEGAN6OByOvpb0u2m8apD33SkaOK0lmIQC4I3DB0Wd6kLU-Eqg6elwXb9Xpe45pcNRknncWGP0msTaBPorZMbdWr7Smg2hMSI--bJbYwqLevgH5d8~uGaBj4MaFncYAR3-4M-kXbMqk1QQ__',
        component: AddWallets,
        showBackButton: true,
        showSkipButton: true,
    },
    {
        screenId: 'success',
        layoutType: 'standard',
        title: `You're all set!`,
        description: 'Start using Peanut for payments.',
        image: happyPeanutAnim.src,
        component: SetupSuccess,
        showBackButton: true,
        showSkipButton: false,
    },
]
