export type LoadingStates =
    | 'Idle'
    | 'Loading'
    | 'Preparing transaction'
    | 'Sign in wallet'
    | 'Executing transaction'
    | 'Allow network switch'
    | 'Creating link'
    | 'Switching network'
    | 'Fetching route'
    | 'Asserting values'
    | 'Generating details'
