export const LOADING_STATES = [
    'Idle',
    'Loading',
    'Preparing transaction',
    'Approve transaction',
    'Sign in wallet',
    'Executing transaction',
    'Allow network switch',
    'Creating link',
    'Switching network',
    'Fetching route',
    'Fetching details',
    'Still fetching details',
    'Awaiting route fulfillment',
    'Asserting values',
    'Generating details',
    'Estimating points',
    'Getting deposit details',
    'Checking your verification',
    'Awaiting TOS confirmation',
    'Waiting for your verification',
    'Linking IBAN',
    'Linking account',
    'Submitting Offramp',
    'Getting profile',
    'Registering',
    'Requesting',
    'Logging in',
    'Logging out',
    'Paying',
    'Withdrawing',
] as const

export type LoadingStates = (typeof LOADING_STATES)[number]
