/**
 * US States with ISO 3166-2 subdivision codes
 * Format: US-XX where XX is the two-letter state code
 */
export const US_STATES = [
    { name: 'Alabama', code: 'AL' },
    { name: 'Alaska', code: 'AK' },
    { name: 'Arizona', code: 'AZ' },
    { name: 'Arkansas', code: 'AR' },
    { name: 'California', code: 'CA' },
    { name: 'Colorado', code: 'CO' },
    { name: 'Connecticut', code: 'CT' },
    { name: 'Delaware', code: 'DE' },
    { name: 'Florida', code: 'FL' },
    { name: 'Georgia', code: 'GA' },
    { name: 'Hawaii', code: 'HI' },
    { name: 'Idaho', code: 'ID' },
    { name: 'Illinois', code: 'IL' },
    { name: 'Indiana', code: 'IN' },
    { name: 'Iowa', code: 'IA' },
    { name: 'Kansas', code: 'KS' },
    { name: 'Kentucky', code: 'KY' },
    { name: 'Louisiana', code: 'LA' },
    { name: 'Maine', code: 'ME' },
    { name: 'Maryland', code: 'MD' },
    { name: 'Massachusetts', code: 'MA' },
    { name: 'Michigan', code: 'MI' },
    { name: 'Minnesota', code: 'MN' },
    { name: 'Mississippi', code: 'MS' },
    { name: 'Missouri', code: 'MO' },
    { name: 'Montana', code: 'MT' },
    { name: 'Nebraska', code: 'NE' },
    { name: 'Nevada', code: 'NV' },
    { name: 'New Hampshire', code: 'NH' },
    { name: 'New Jersey', code: 'NJ' },
    { name: 'New Mexico', code: 'NM' },
    { name: 'New York', code: 'NY' },
    { name: 'North Carolina', code: 'NC' },
    { name: 'North Dakota', code: 'ND' },
    { name: 'Ohio', code: 'OH' },
    { name: 'Oklahoma', code: 'OK' },
    { name: 'Oregon', code: 'OR' },
    { name: 'Pennsylvania', code: 'PA' },
    { name: 'Rhode Island', code: 'RI' },
    { name: 'South Carolina', code: 'SC' },
    { name: 'South Dakota', code: 'SD' },
    { name: 'Tennessee', code: 'TN' },
    { name: 'Texas', code: 'TX' },
    { name: 'Utah', code: 'UT' },
    { name: 'Vermont', code: 'VT' },
    { name: 'Virginia', code: 'VA' },
    { name: 'Washington', code: 'WA' },
    { name: 'West Virginia', code: 'WV' },
    { name: 'Wisconsin', code: 'WI' },
    { name: 'Wyoming', code: 'WY' },
] as const

export type USStateCode = (typeof US_STATES)[number]['code']

/**
 * Mexican States with ISO 3166-2 subdivision codes
 * Format: MX-XXX where XXX is the three-letter state code
 */
export const MX_STATES = [
    { name: 'Aguascalientes', code: 'AGU' },
    { name: 'Baja California', code: 'BCN' },
    { name: 'Baja California Sur', code: 'BCS' },
    { name: 'Campeche', code: 'CAM' },
    { name: 'Chiapas', code: 'CHP' },
    { name: 'Chihuahua', code: 'CHH' },
    { name: 'Ciudad de México', code: 'CMX' },
    { name: 'Coahuila', code: 'COA' },
    { name: 'Colima', code: 'COL' },
    { name: 'Durango', code: 'DUR' },
    { name: 'Guanajuato', code: 'GUA' },
    { name: 'Guerrero', code: 'GRO' },
    { name: 'Hidalgo', code: 'HID' },
    { name: 'Jalisco', code: 'JAL' },
    { name: 'México', code: 'MEX' },
    { name: 'Michoacán', code: 'MIC' },
    { name: 'Morelos', code: 'MOR' },
    { name: 'Nayarit', code: 'NAY' },
    { name: 'Nuevo León', code: 'NLE' },
    { name: 'Oaxaca', code: 'OAX' },
    { name: 'Puebla', code: 'PUE' },
    { name: 'Querétaro', code: 'QUE' },
    { name: 'Quintana Roo', code: 'ROO' },
    { name: 'San Luis Potosí', code: 'SLP' },
    { name: 'Sinaloa', code: 'SIN' },
    { name: 'Sonora', code: 'SON' },
    { name: 'Tabasco', code: 'TAB' },
    { name: 'Tamaulipas', code: 'TAM' },
    { name: 'Tlaxcala', code: 'TLA' },
    { name: 'Veracruz', code: 'VER' },
    { name: 'Yucatán', code: 'YUC' },
    { name: 'Zacatecas', code: 'ZAC' },
] as const

export type MXStateCode = (typeof MX_STATES)[number]['code']
