import type { UsageCategory } from '../../_components/UsageAudit'

// AUTO-GENERATED by the ds-real-usage-audit workflow (real-app usage verified via grep, dead claims
// independently re-verified). Do not hand-edit — regenerate with the workflow.
export const BIG_COMPONENT_CATEGORIES: UsageCategory[] = [
    {
        category: 'Modals',
        layer: 'components',
        summary:
            'The app has THREE overlay primitives and ~28 concrete modals, and they are broadly inconsistent. Base layer: (1) Global/Modal ("BaseModal", @headlessui/react Dialog+Transition; default panel rounded-md, max-w-[26rem], self-end on mobile, optional border-b title bar, cancel button top-2/right-2) — 14 real consumers; (2) Global/ActionModal, a wrapper over BaseModal with an opinionated icon+title+description+CTA layout that OVERRIDES the base to rounded-none, max-w-[85%], centered — 35 real consumers and the de-facto standard; (3) Global/Drawer (vaul bottom-sheet, rounded-t-[10px], bg-black/80 overlay) — a totally separate family used by 7 "*Drawer" components. No @radix-ui/react-dialog and no react-modal anywhere; headlessui Dialog is only used raw by MoreInfo, Select, CurrencySelect and BaseModal itself. Worst divergence: THREE modals (NoMoreJailModal, ConfirmInviteModal, QRScannerOverlay) each copy-paste the identical hand-rolled classWrap "sm:m-auto sm:self-center self-center m-4 bg-background rounded-none border-0" + an inner "rounded-md bg-white px-6 py-6" div — re-implementing centered layout that ActionModal already provides. Radius is all over: BaseModal default rounded-md, ActionModal rounded-none, CardLimitEditModal rounded-2xl, SupportedNetworks/HowToDeposit rounded-sm. Backdrop also diverges: BaseModal uses bg-n-1/85 with click-to-close wired manually (documented v1→v2 headlessui regression), Drawer uses bg-black/80, and several modals pass hideOverlay to suppress it entirely. GuestLoginModal is the only modal still using BaseModal\'s built-in title-bar chrome; everyone else renders their own header. EasterEggModal is the only modal surfaced in the /dev showcase.',
        items: [
            {
                name: 'Modal (BaseModal, Global/Modal)',
                realUsages: 14,
                status: 'canonical',
                devUsages: 1,
                source: 'components/Global/Modal/index.tsx',
                divergence:
                    "THE base primitive: @headlessui/react Dialog+Transition. Default panel rounded-md, max-w-[26rem], self-end (bottom-sheet on mobile / centered md+), bg-n-1/85 overlay with click-close wired manually to work around headlessui v2 backdrop regression; cancel button hard-fixed top-2 right-2. Every consumer overrides classWrap, so the 'default' look almost never ships.",
                usedIn: [
                    'components/Global/ActionModal/index.tsx',
                    'components/Global/GuestLoginModal/index.tsx',
                    'components/Global/ConfirmInviteModal/index.tsx',
                    'components/Global/NoMoreJailModal/index.tsx',
                    'components/Global/QRScannerOverlay/index.tsx',
                ],
            },
            {
                name: 'ActionModal (Global/ActionModal)',
                realUsages: 35,
                status: 'canonical',
                devUsages: 1,
                source: 'components/Global/ActionModal/index.tsx',
                divergence:
                    "De-facto standard wrapper over BaseModal: forces rounded-none + max-w-[85%] + centered, icon-in-pink-circle + bold title + grey description + Button CTA array. Diverges from BaseModal's own rounded-md/max-w-[26rem] defaults, so 'BaseModal' and 'ActionModal' modals look different by default.",
                usedIn: [
                    'components/Kyc/InitiateKycModal.tsx',
                    'components/Home/WelcomeUnlockModal/index.tsx',
                    'components/Notifications/SetupNotificationsModal.tsx',
                    'components/Global/InviteFriendsModal/index.tsx',
                    'app/(mobile-ui)/qr-pay/page.tsx',
                ],
            },
            {
                name: 'Drawer (Global/Drawer, vaul)',
                realUsages: 7,
                status: 'canonical',
                devUsages: 0,
                source: 'components/Global/Drawer/index.tsx',
                divergence:
                    "Entirely separate overlay family (vaul), rounded-t-[10px], bg-black/80 overlay, bottom-anchored with drag handle. Overlaps conceptually with BaseModal's mobile self-end mode — two independent 'bottom sheet' implementations exist.",
                usedIn: [
                    'components/TransactionDetails/TransactionDetailsDrawer.tsx',
                    'components/AddMoney/components/ChooseNetworkDrawer.tsx',
                    'components/Kyc/KycStatusDrawer.tsx',
                    'components/Badges/BadgeStatusDrawer.tsx',
                    'features/payments/flows/contribute-pot/components/ContributorsDrawer.tsx',
                ],
            },
            {
                name: 'GuestLoginModal',
                realUsages: 2,
                status: 'live',
                devUsages: 0,
                source: 'components/Global/GuestLoginModal/index.tsx',
                divergence:
                    "Only modal still using BaseModal's built-in title-bar chrome (passes title='Sign in with your Peanut Wallet' → border-b header). Everyone else renders a custom header, so this one is the odd chrome out. Open state via ModalsContext.isSignInModalOpen.",
                usedIn: ['app/(mobile-ui)/layout.tsx', 'app/[...recipient]/payment-layout-wrapper.tsx'],
            },
            {
                name: 'ConfirmInviteModal',
                realUsages: 1,
                status: 'variant',
                devUsages: 0,
                source: 'components/Global/ConfirmInviteModal/index.tsx',
                divergence:
                    "Hand-rolls the ActionModal layout on raw BaseModal: hideOverlay + classWrap='...rounded-none border-0' + inner 'rounded-md bg-white px-6 py-6' div. Copy of the exact same block in NoMoreJailModal & QRScannerOverlay — merge candidate into ActionModal.",
                usedIn: ['components/Claim/Link/SendLinkActionList.tsx'],
            },
            {
                name: 'NoMoreJailModal',
                realUsages: 1,
                status: 'variant',
                devUsages: 0,
                source: 'components/Global/NoMoreJailModal/index.tsx',
                divergence:
                    "Identical hand-rolled BaseModal wrapper as ConfirmInviteModal (same classWrap 'sm:m-auto sm:self-center self-center m-4 bg-background rounded-none border-0' + inner 'rounded-md bg-white px-6 py-6'). Uses hideOverlay and gates via sessionStorage 'showNoMoreJailModal'. Duplicated layout logic.",
                usedIn: ['app/(mobile-ui)/home/page.tsx'],
            },
            {
                name: 'EarlyUserModal',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/Global/EarlyUserModal/index.tsx',
                divergence: 'Standard ActionModal usage (lazy-loaded on home). Consistent — no styling override.',
                usedIn: ['app/(mobile-ui)/home/page.tsx'],
            },
            {
                name: 'IosPwaInstallModal',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/Global/IosPwaInstallModal/index.tsx',
                divergence:
                    'ActionModal-based; open state via ModalsContext.isIosPwaInstallModalOpen (dual trigger path: context + lazy render on home).',
                usedIn: ['app/(mobile-ui)/home/page.tsx'],
            },
            {
                name: 'EasterEggModal',
                realUsages: 1,
                status: 'live',
                devUsages: 1,
                source: 'components/Global/EasterEggModal/index.tsx',
                divergence:
                    "ActionModal with iconContainerClassName='size-auto rounded-none bg-transparent w-full' (full-bleed image instead of the pink icon circle). Only modal also demoed in the /dev design-system showcase.",
                usedIn: ['components/Common/CountryList.tsx'],
            },
            {
                name: 'UnsupportedBrowserModal',
                realUsages: 3,
                status: 'live',
                devUsages: 0,
                source: 'components/Global/UnsupportedBrowserModal/index.tsx',
                divergence:
                    'ActionModal with allowClose prop → conditionally passes preventClose to block dismissal on unsupported browsers. Consistent base, custom close-gate logic.',
                usedIn: [
                    'app/(setup)/setup/page.tsx',
                    'components/Invites/InvitesPage.tsx',
                    'components/Setup/Setup.utils.ts',
                ],
            },
            {
                name: 'InviteFriendsModal',
                realUsages: 3,
                status: 'live',
                devUsages: 0,
                source: 'components/Global/InviteFriendsModal/index.tsx',
                divergence: 'ActionModal-based share sheet. Consistent.',
                usedIn: [
                    'app/(mobile-ui)/rewards/page.tsx',
                    'components/Home/PerkClaimModal.tsx',
                    'components/Profile/index.tsx',
                ],
            },
            {
                name: 'BalanceWarningModal',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/Global/BalanceWarningModal/index.tsx',
                divergence:
                    'Uses raw BaseModal (not ActionModal) with its own body layout — another one-off that could be ActionModal. Lazy-loaded on home.',
                usedIn: ['app/(mobile-ui)/home/page.tsx'],
            },
            {
                name: 'CancelSendLinkModal',
                realUsages: 2,
                status: 'live',
                devUsages: 0,
                source: 'components/Global/CancelSendLinkModal/index.tsx',
                divergence: 'ActionModal-based destructive-confirm. Consistent.',
                usedIn: [
                    'components/Send/link/views/Success.link.send.view.tsx',
                    'components/TransactionDetails/TransactionDetailsReceipt.tsx',
                ],
            },
            {
                name: 'TokenAndNetworkConfirmationModal',
                realUsages: 2,
                status: 'live',
                devUsages: 0,
                source: 'components/Global/TokenAndNetworkConfirmationModal/index.tsx',
                divergence: 'ActionModal-based. Consistent.',
                usedIn: [
                    'components/AddWithdraw/AddWithdrawCountriesList.tsx',
                    'components/AddWithdraw/AddWithdrawRouterView.tsx',
                ],
            },
            {
                name: 'GuestVerificationModal',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/Global/GuestVerificationModal/index.tsx',
                divergence: 'ActionModal-based. Consistent.',
                usedIn: ['components/Claim/Link/Initial.view.tsx'],
            },
            {
                name: 'WelcomeUnlockModal',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/Home/WelcomeUnlockModal/index.tsx',
                divergence:
                    'ActionModal-based, isOpen/onClose prop naming (differs from the visible/onClose convention used by most other modals). Lazy-loaded on home.',
                usedIn: ['app/(mobile-ui)/home/page.tsx'],
            },
            {
                name: 'PerkClaimModal',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/Home/PerkClaimModal.tsx',
                divergence:
                    'ActionModal-based; also declares an internal SuccessModal component in the same file (two modal components in one file, violates one-component-per-file).',
                usedIn: ['components/Home/HomeCarouselCTA/index.tsx'],
            },
            {
                name: 'OnrampConfirmationModal',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/AddMoney/components/OnrampConfirmationModal.tsx',
                divergence: 'ActionModal-based. Consistent.',
                usedIn: ['app/(mobile-ui)/add-money/[country]/bank/page.tsx'],
            },
            {
                name: 'SupportedNetworksModal',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/AddMoney/components/SupportedNetworksModal.tsx',
                divergence:
                    "Raw BaseModal with classWrap '...bg-background rounded-sm' — uses rounded-sm, diverging from BaseModal default rounded-md AND ActionModal rounded-none. Third distinct radius.",
                usedIn: ['components/AddMoney/views/CryptoDeposit.view.tsx'],
            },
            {
                name: 'HowToDepositModal',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/AddMoney/components/HowToDepositModal.tsx',
                divergence:
                    "Raw BaseModal, classWrap '...rounded-sm' like SupportedNetworksModal; two sibling modals in the same feature reimplement the same rounded-sm wrapper instead of sharing one.",
                usedIn: ['components/AddMoney/views/CryptoDeposit.view.tsx'],
            },
            {
                name: 'LockCardModal',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/Card/LockCardModal.tsx',
                divergence:
                    "Raw BaseModal, classWrap='sm:m-auto sm:self-center self-center m-4' (keeps BaseModal default rounded-md). Yellow-1 icon circle hard-coded inline instead of ActionModal's iconContainer.",
                usedIn: ['components/Card/YourCardScreen.tsx'],
            },
            {
                name: 'CancelCardModal',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/Card/CancelCardModal.tsx',
                divergence:
                    "Raw BaseModal with same 'sm:m-auto...' classWrap as LockCardModal; duplicates the yellow-1 icon-circle + textarea block. Card modals form their own mini-variant family, none using ActionModal.",
                usedIn: ['components/Card/YourCardScreen.tsx'],
            },
            {
                name: 'CardLimitEditModal',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/Card/CardLimitEditModal.tsx',
                divergence:
                    "Raw BaseModal, classWrap='...rounded-2xl' — the ONLY modal using rounded-2xl (vs BaseModal rounded-md, ActionModal rounded-none, AddMoney rounded-sm). Fourth distinct corner radius across the modal set.",
                usedIn: ['components/Card/CardLimitsScreen.tsx'],
            },
            {
                name: 'InitiateKycModal',
                realUsages: 7,
                status: 'live',
                devUsages: 0,
                source: 'components/Kyc/InitiateKycModal.tsx',
                divergence:
                    'ActionModal with preventClose (blocks dismissal mid-KYC). Widely rendered across add-money/withdraw/claim flows; consistent base.',
                usedIn: [
                    'app/(mobile-ui)/add-money/[country]/bank/page.tsx',
                    'app/(mobile-ui)/withdraw/[country]/bank/page.tsx',
                    'app/(mobile-ui)/withdraw/manteca/page.tsx',
                    'components/AddMoney/components/MantecaAddMoney.tsx',
                    'components/Claim/Link/MantecaFlowManager.tsx',
                ],
            },
            {
                name: 'SumsubKycModals',
                realUsages: 11,
                status: 'live',
                devUsages: 0,
                source: 'components/Kyc/SumsubKycModals.tsx',
                divergence:
                    'Orchestrator that renders SumsubKycWrapper (Base+ActionModal + IframeWrapper) + KycVerificationInProgressModal. Not a single modal but a modal cluster; most-rendered KYC entry point.',
                usedIn: [
                    'app/(mobile-ui)/add-money/[country]/bank/page.tsx',
                    'app/(mobile-ui)/qr-pay/page.tsx',
                    'components/AddMoney/components/MantecaAddMoney.tsx',
                    'components/Claim/Link/MantecaFlowManager.tsx',
                    'components/Profile/views/UnlockedRegions.view.tsx',
                ],
            },
            {
                name: 'KycVerificationInProgressModal',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/Kyc/KycVerificationInProgressModal.tsx',
                divergence:
                    'ActionModal with preventClose. Only rendered inside SumsubKycModals — effectively a private sub-modal, but exported as a top-level component.',
                usedIn: ['components/Kyc/SumsubKycModals.tsx'],
            },
            {
                name: 'KycActionRequiredModal',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/Kyc/modals/KycActionRequiredModal.tsx',
                divergence:
                    'ActionModal-based; one of three near-identical Kyc/modals/* (ActionRequired/Failed/Processing) selected via getModalVariant() in UnlockedRegions.view. Three files that differ only in copy/icon — merge candidate.',
                usedIn: ['components/Profile/views/UnlockedRegions.view.tsx'],
            },
            {
                name: 'KycFailedModal',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/Kyc/modals/KycFailedModal.tsx',
                divergence:
                    'ActionModal-based; sibling of KycActionRequiredModal/KycProcessingModal, only differs by title/description/icon. Redundant trio.',
                usedIn: ['components/Profile/views/UnlockedRegions.view.tsx'],
            },
            {
                name: 'KycProcessingModal',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/Kyc/modals/KycProcessingModal.tsx',
                divergence:
                    'ActionModal-based; third of the near-duplicate Kyc/modals trio, all rendered from the same switch in UnlockedRegions.view.tsx.',
                usedIn: ['components/Profile/views/UnlockedRegions.view.tsx'],
            },
            {
                name: 'UnlockRegionModal',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/IdentityVerification/UnlockRegionModal.tsx',
                divergence: 'ActionModal-based. Consistent.',
                usedIn: ['components/Profile/views/UnlockedRegions.view.tsx'],
            },
            {
                name: 'SetupNotificationsModal',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/Notifications/SetupNotificationsModal.tsx',
                divergence:
                    'ActionModal-based; open state driven by useNotifications().showPermissionModal (hook-owned visibility, unlike the local-state pattern most modals use).',
                usedIn: ['app/(mobile-ui)/home/page.tsx'],
            },
            {
                name: 'CameraPermissionModal',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/Global/QRScanner/CameraPermissionModal.tsx',
                divergence: 'ActionModal-based. Consistent.',
                usedIn: ['components/Global/QRScanner/index.tsx'],
            },
            {
                name: 'RainCooldownIntroModal',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/Global/RainCooldown/IntroModal.tsx',
                divergence:
                    'ActionModal-based; visibility from RainCooldownContext (showIntroModal). Rendered globally at provider level, not inside a page.',
                usedIn: ['app/ClientProviders.tsx'],
            },
            {
                name: 'PasskeySetupHelpModal',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/Setup/Views/PasskeySetupHelpModal.tsx',
                divergence: 'ActionModal-based. Consistent.',
                usedIn: ['components/Setup/Views/SetupPasskey.tsx'],
            },
            {
                name: 'QRScannerOverlay (BaseModal ad-hoc)',
                realUsages: 1,
                status: 'adhoc',
                devUsages: 0,
                source: 'components/Global/QRScannerOverlay/index.tsx',
                divergence:
                    "Raw BaseModal with the SAME hand-rolled classWrap='...rounded-none border-0' as NoMoreJail/ConfirmInvite, plus a Record<EModalType, Component> content-switch and preventClose gated on modalContent !== QR_NOT_SUPPORTED. Third copy of the duplicated centered-wrapper block.",
                usedIn: ['app/(mobile-ui)/qr-pay/page.tsx'],
            },
            {
                name: 'IframeWrapper (BaseModal ad-hoc, Sumsub SDK host)',
                realUsages: 1,
                status: 'adhoc',
                devUsages: 0,
                source: 'components/Global/IframeWrapper/index.tsx',
                divergence:
                    "Uses BOTH BaseModal (classWrap='h-full w-full !max-w-none sm:!max-w-[600px] border-none' — full-screen, breaks the max-w-[26rem] convention) for the iframe host AND an ActionModal (modalPanelClassName='max-w-full') for its error state. Widest/most bespoke modal geometry in the app.",
                usedIn: ['components/Kyc/SumsubKycWrapper.tsx'],
            },
        ],
    },
    {
        category: 'Drawers & Sheets',
        layer: 'components',
        summary:
            'One real bottom-sheet primitive exists: the vaul-based Drawer at components/Global/Drawer/index.tsx (8 real consumers). On top of it sit 6 concrete drawers, all live but almost all single-use (TransactionDetailsDrawer is the only one with >1 consumer). There is NO separate Sheet/BottomSheet component and NO Radix Dialog — vaul is the sole drag primitive. Two ad-hoc sheets bypass vaul entirely and are the worst divergences: SupportDrawer (Global/SupportDrawer, 5 real consumers) hand-rolls its own fixed translate-y panel, backdrop, drag-to-dismiss and escape handling instead of using the base Drawer; and the widely-used Global/Modal (15 real consumers) is really a mobile bottom-sheet (self-end rounded-md, centers on desktop) with no vaul/handle/snap — a parallel sheet system. The base Drawer hard-codes rounded-t-[10px], a bg-black drag handle and max-h-[80vh]; SupportDrawer copies those literals by hand (rounded-t-[10px], h-1.5 w-10 bg-black) rather than reusing them. Snap points are used by exactly one drawer (QRBottomDrawer: [0.75,1], modal=false). The dev showcase only ever renders the base Drawer primitive; none of the concrete drawers appear in a real /dev/ showcase (their only /dev/ hit is a string entry in ds/audit/audit-data.ts, a catalog, not a render).',
        items: [
            {
                name: 'Drawer (base vaul primitive)',
                realUsages: 8,
                status: 'canonical',
                devUsages: 2,
                source: 'components/Global/Drawer/index.tsx',
                divergence:
                    'The ONE canonical bottom-sheet, wraps vaul Drawer.Root with shouldScaleBackground + snapToSequentialPoint. Hard-codes rounded-t-[10px], a mx-auto my-4 h-1.5 w-10 rounded-full bg-black drag handle, border, and max-h-[80vh] overflow-auto content cap in DrawerContent. Everything below should route through it; SupportDrawer and Global/Modal do not.',
                usedIn: [
                    'components/TransactionDetails/TransactionDetailsDrawer.tsx',
                    'components/Kyc/KycStatusDrawer.tsx',
                    'components/Card/CardUnlockDrawer.tsx',
                    'components/Badges/BadgeStatusDrawer.tsx',
                    'components/AddMoney/components/ChooseNetworkDrawer.tsx',
                ],
            },
            {
                name: 'TransactionDetailsDrawer',
                realUsages: 5,
                status: 'live',
                devUsages: 0,
                source: 'components/TransactionDetails/TransactionDetailsDrawer.tsx',
                divergence:
                    'Uses base Drawer. Only concrete drawer with >1 consumer. Custom close: onOpenChange guards on an internal isModalOpen and bumps DrawerContent to !z-[10] when a nested modal opens — a z-index hack no other drawer has; padding py-5 + inner px-5, sr-only title.',
                usedIn: [
                    'components/TransactionDetails/TransactionCard.tsx',
                    'components/Claim/Claim.tsx',
                    'hooks/useTransactionDetailsDrawer.ts',
                    'app/(mobile-ui)/qr-pay/page.tsx',
                    'features/payments/shared/components/PaymentSuccessView.tsx',
                ],
            },
            {
                name: 'KycStatusDrawer',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/Kyc/KycStatusDrawer.tsx',
                divergence:
                    "Uses base Drawer. onOpenChange={onClose} (fires close on any dismiss). Padding p-5 pb-12 (extra bottom pad vs others' py-5), sr-only DrawerTitle, no DrawerHeader. Renders SumsubKycModals as a sibling that must persist after the drawer closes (onKeepMounted) — unique keep-mounted contract.",
                usedIn: ['components/Kyc/KycStatusItem.tsx'],
            },
            {
                name: 'BadgeStatusDrawer',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/Badges/BadgeStatusDrawer.tsx',
                divergence:
                    'Uses base Drawer. NO DrawerTitle at all (a11y gap — others use at least sr-only), no DrawerHeader; content is py-5 outer + p-5 inner (double padding). Header is an ad-hoc Card+Image block instead of the DrawerHeader/DrawerTitle pattern.',
                usedIn: ['components/Badges/BadgeStatusItem.tsx'],
            },
            {
                name: 'CardUnlockDrawer',
                realUsages: 1,
                status: 'live',
                devUsages: 2,
                source: 'components/Card/CardUnlockDrawer.tsx',
                divergence:
                    "Uses base Drawer. Only concrete drawer that uses DrawerHeader + DrawerTitle the intended way (comment even documents 'mono Drawer pattern'). onOpenChange={(open)=>!open&&onClose()}. Content px-4 pb-6 (yet another padding value). Appears in /dev/share-builder showcase but real render is history feed.",
                usedIn: ['components/Card/CardUnlockHistoryItem.tsx'],
            },
            {
                name: 'ChooseNetworkDrawer',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/AddMoney/components/ChooseNetworkDrawer.tsx',
                divergence:
                    'Uses base Drawer. Only drawer using the full DrawerHeader/DrawerTitle/DrawerDescription trio. Padding pt-4 outer + px-4 pb-6 inner; header pt-0 text-center. onOpenChange={(isOpen)=>!isOpen&&onClose()} — same close idiom as CardUnlock but different prop name.',
                usedIn: ['components/AddMoney/views/AddMoneyMethodSelection.view.tsx'],
            },
            {
                name: 'ContributorsDrawer',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'features/payments/flows/contribute-pot/components/ContributorsDrawer.tsx',
                divergence:
                    'Uses base Drawer. ONLY drawer opened via DrawerTrigger (uncontrolled — no isOpen/onClose props); all others are controlled via open+onOpenChange. Padding py-6 + inner px-4 max-h-[60vh] (its own scroll cap vs base 80vh). DrawerTitle text-start (base is text-center).',
                usedIn: ['components/User/UserCard.tsx'],
            },
            {
                name: 'QRBottomDrawer',
                realUsages: 1,
                status: 'variant',
                devUsages: 0,
                source: 'components/Global/QRBottomDrawer/index.tsx',
                divergence:
                    'Uses base Drawer but is the ONLY one that uses snapPoints ([0.75,1]) + activeSnapPoint state + modal={false} (non-blocking peek/expand sheet). open hard-coded to true (parent controls mount). p-5 min-h-[200px]. Title text swaps on snap point. Diverges from every other drawer which is a single-height modal sheet.',
                usedIn: ['components/Global/QRScannerOverlay/index.tsx'],
            },
            {
                name: 'SupportDrawer',
                realUsages: 5,
                status: 'adhoc',
                devUsages: 0,
                source: 'components/Global/SupportDrawer/index.tsx',
                divergence:
                    'DOES NOT use vaul or the base Drawer — hand-rolls a fixed inset-x-0 bottom-0 translate-y panel, its own black/80 backdrop, manual touch drag-to-dismiss (DISMISS_THRESHOLD=100px), and manual Escape handler. Re-implements base Drawer literals by hand: rounded-t-[10px], h-1.5 w-10 rounded-full bg-black handle, md:max-w-xl, 80vh content. Prime merge candidate — should be the base Drawer with an iframe child. (useHomeCarouselCTAs/crisp-proxy are comment/modal-open references, real renders are the 3 layout files.)',
                usedIn: [
                    'app/(mobile-ui)/layout.tsx',
                    'app/[...recipient]/payment-layout-wrapper.tsx',
                    'app/not-found.tsx',
                    'hooks/useHomeCarouselCTAs.tsx',
                    'app/crisp-proxy/page.tsx',
                ],
            },
            {
                name: 'Modal (Global/Modal, mobile bottom-sheet)',
                realUsages: 15,
                status: 'duplicate',
                devUsages: 0,
                source: 'components/Global/Modal/index.tsx',
                divergence:
                    "Parallel sheet system, NOT vaul. On mobile it is a bottom-sheet: fixed inset-0 flex items-center, panel self-end rounded-md w-full (anchored to bottom); on desktop sm:self-auto sm:m-auto (centers). No drag handle, no snap points, no swipe-to-close (tap-backdrop only), rounded-md (vs Drawer's rounded-t-[10px]). 15 consumers effectively use this as the bottom-sheet, competing head-on with the vaul Drawer — the biggest consolidation target in this category.",
                usedIn: [
                    'components/AddMoney/components/SupportedNetworksModal.tsx',
                    'components/AddMoney/components/HowToDepositModal.tsx',
                    'components/Card/CancelCardModal.tsx',
                    'components/Card/LockCardModal.tsx',
                    'components/Card/CardLimitEditModal.tsx',
                ],
            },
        ],
    },
    {
        category: 'Lists & Rows',
        layer: 'patterns',
        summary:
            'Grep-verified 18 distinct list/row implementations across history, token, contact, deposit/country, saved-account, and settings buckets. 16 are live, 1 is dead (CountryRegionRow: exported, zero imports/renders anywhere), 0 are showcase-only (none of these list components appear under /dev/ — the DS showcase never renders any of them). The dominant pattern is that almost every row wraps the shared Global/Card primitive (84 real usages; px-4 py-2, position-based stacked border-radius via getCardPosition), and ActionListCard (16 real usages) is the de-facto canonical generic list row. Worst divergence: five distinct hand-rolled position-calculation blocks (the isFirst/isLast/isSingle ternary) are copy-pasted across HomeHistory, history/page, DepositMethodList, SavedAccountsMapping, and Contacts.view instead of all calling the shared getCardPosition helper (only HomeHistory, history/page, and CountryList use it). Row height/padding also diverges: ActionListCard default (py-2) vs TokenListItem (py-3.5) vs ProfileMenuItem/NetworkListItem (p-4) vs SavedAccountsMapping override (p-4 py-2.5). Empty-state handling is inconsistent: EmptyState vs NoDataEmptyState vs null across the same feed. The two transaction feeds (HomeHistory top-5 and the infinite history page) duplicate ~150 lines of WebSocket merge + synthetic-entry injection + drawer-memo logic that differ only in date-grouping.',
        items: [
            {
                name: 'Global/Card',
                realUsages: 84,
                status: 'canonical',
                devUsages: 0,
                source: 'components/Global/Card/index.tsx',
                divergence:
                    'The shared row primitive every list row wraps: px-4 py-2, border-black, position-driven border-radius (rounded-t/b-sm + border-t-0 for stacked rows). Default export, distinct from 0_Bruddle/Card. Consumers override its padding inconsistently (py-2.5/py-3.5/p-4), which is the root of the row-height divergence across all rows below.',
                usedIn: [
                    'components/ActionListCard/index.tsx',
                    'components/TransactionDetails/TransactionCard.tsx',
                    'components/Global/TokenSelector/Components/TokenListItem.tsx',
                    'components/Profile/components/ProfileMenuItem.tsx',
                    'components/Kyc/KycStatusItem.tsx',
                ],
            },
            {
                name: 'ActionListCard',
                realUsages: 16,
                status: 'canonical',
                devUsages: 0,
                source: 'components/ActionListCard/index.tsx',
                divergence:
                    'The de-facto canonical generic list row (title/description/leftIcon/rightContent/position). Default right-slot is a pink chevron pill Button; wraps Global/Card at py-2. Every other bespoke row below could collapse into this — the divergence is that TokenListItem, NetworkListItem, ProfileMenuItem, and the two feed rows re-implement its layout instead of reusing it.',
                usedIn: [
                    'components/Common/CountryList.tsx',
                    'components/AddMoney/components/DepositMethodList.tsx',
                    'components/Common/SavedAccountsView.tsx',
                    'components/Send/views/Contacts.view.tsx',
                    'features/payments/shared/components/PaymentMethodActionList.tsx',
                ],
            },
            {
                name: 'TransactionCard',
                realUsages: 2,
                status: 'live',
                devUsages: 0,
                source: 'components/TransactionDetails/TransactionCard.tsx',
                divergence:
                    'Transaction/history feed row. Wraps Global/Card directly (NOT ActionListCard) with its own avatar+name+amount layout, size-8 avatar, opens a lazy-loaded TransactionDetailsDrawer per row (each row mounts its own drawer instance — heavy). Left slot has 4 avatar branches (test-txn logo / PerkIcon / image / TransactionAvatarBadge); no other row has this.',
                usedIn: ['components/Home/HomeHistory.tsx', 'app/(mobile-ui)/history/page.tsx'],
            },
            {
                name: 'HomeHistory (feed list container)',
                realUsages: 1,
                status: 'duplicate',
                devUsages: 0,
                source: 'components/Home/HomeHistory.tsx',
                divergence:
                    "Top-5 activity feed. Duplicates ~150 lines of WebSocket-merge + synthetic-entry injection (KYC/badge/card-unlock rows) + per-row drawer memo with history/page.tsx; differs only in limit(5) and no date-grouping. Uses getCardPosition. Own HistorySkeleton loader + 3 distinct empty-state branches (EmptyState 'txn-off' vs KycStatusItem vs null via hideEmptyState).",
                usedIn: ['components/Home/HomeHistory.tsx'],
            },
            {
                name: 'HistoryPage (feed list container)',
                realUsages: 1,
                status: 'duplicate',
                devUsages: 0,
                source: 'app/(mobile-ui)/history/page.tsx',
                divergence:
                    "Full paginated activity feed. Duplicate of HomeHistory's merge/inject/memo logic but adds date-group headers (getDateGroup) and infinite scroll. Diverges on empty state: uses NoDataEmptyState (not EmptyState like HomeHistory) and its own position calc keyed on group boundaries rather than plain getCardPosition.",
                usedIn: ['app/(mobile-ui)/history/page.tsx'],
            },
            {
                name: 'TokenListItem',
                realUsages: 2,
                status: 'live',
                devUsages: 0,
                source: 'components/Global/TokenSelector/Components/TokenListItem.tsx',
                divergence:
                    'Token/asset row. Wraps Global/Card but overrides padding to p-4 py-3.5 (taller than ActionListCard py-2) and forces border+shadow-4. Left slot = token logo with an overlaid chain badge (-bottom-1 -right-1) — a unique two-image avatar not present in any other row. Selected state = bg-primary-3 applied on BOTH the outer div and the Card (double).',
                usedIn: ['components/Global/TokenSelector/TokenSelector.tsx', 'app/(mobile-ui)/recover-funds/page.tsx'],
            },
            {
                name: 'NetworkListItem',
                realUsages: 1,
                status: 'variant',
                devUsages: 0,
                source: 'components/Global/TokenSelector/Components/NetworkListItem.tsx',
                divergence:
                    "Network row — sibling of TokenListItem doing the same 'icon + name + right chevron' job but built on a Button+Card at p-4 (h-8 icon) instead of TokenListItem's py-3.5, and uses NavigationArrow for the right slot where TokenListItem uses an Icon chevron. Coming-soon state = bg-grey-4 + StatusBadge 'soon'.",
                usedIn: ['components/Global/TokenSelector/Components/NetworkListView.tsx'],
            },
            {
                name: 'NetworkListView (list container)',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/Global/TokenSelector/Components/NetworkListView.tsx',
                divergence:
                    'Scroll container that .maps NetworkListItem. Hard-codes its own scroll wrapper (max-h-[60vh] flex-col gap-3 space-y-2 overflow-y-auto) instead of reusing the sibling ScrollableList primitive in the same folder — duplicated scroll/gap styling.',
                usedIn: ['components/Global/TokenSelector/TokenSelector.tsx'],
            },
            {
                name: 'ScrollableList',
                realUsages: 2,
                status: 'live',
                devUsages: 0,
                source: 'components/Global/TokenSelector/Components/ScrollableList.tsx',
                divergence:
                    'Generic scroll wrapper (overflow-y-auto, flex-col gap-3) for token lists. Only used in 2 spots even though every other list container (NetworkListView, Contacts, CountryList, DepositMethodList) re-implements the same overflow-y-auto div inline — under-adopted, a merge candidate for those containers.',
                usedIn: ['components/Global/TokenSelector/TokenSelector.tsx', 'app/(mobile-ui)/recover-funds/page.tsx'],
            },
            {
                name: 'DepositMethodList (list container)',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/AddMoney/components/DepositMethodList.tsx',
                divergence:
                    'Deposit-method list; .maps ActionListCard. Left slot is a 4-way branch (crypto AvatarWithBadge / bank AvatarWithBadge / country flag Image / fallback). Re-implements the isFirst/isLast/isSingle position ternary inline (with extra crypto-at-slot0 special cases) instead of calling getCardPosition — one of 5 copies of that block.',
                usedIn: ['components/AddWithdraw/AddWithdrawRouterView.tsx'],
            },
            {
                name: 'CountryList (list container)',
                realUsages: 4,
                status: 'live',
                devUsages: 0,
                source: 'components/Common/CountryList.tsx',
                divergence:
                    "Country picker; .maps ActionListCard with flag leftIcon. Correctly uses getCardPosition (unlike DepositMethodList). Empty state = EmptyState 'search'. Loading = CountryListSkeleton. Per-row loading spinner via clickedCountryId + StatusBadge 'soon' for unsupported — the most feature-rich country row.",
                usedIn: [
                    'components/AddWithdraw/AddWithdrawRouterView.tsx',
                    'components/Common/CountryListRouter.tsx',
                    'components/Claim/Link/views/BankFlowManager.view.tsx',
                    'app/(mobile-ui)/add-money/page.tsx',
                ],
            },
            {
                name: 'AddWithdrawCountriesList',
                realUsages: 4,
                status: 'variant',
                devUsages: 0,
                source: 'components/AddWithdraw/AddWithdrawCountriesList.tsx',
                divergence:
                    "Second country/method list also .mapping ActionListCard — overlaps CountryList's job (both render country/payment rows for add/withdraw). Empty state = EmptyState 'Country not found'. Duplicate-country-picker candidate: CountryList and AddWithdrawCountriesList should be unified.",
                usedIn: [
                    'app/(mobile-ui)/add-money/page.tsx',
                    'app/(mobile-ui)/add-money/[country]/page.tsx',
                    'app/(mobile-ui)/withdraw/page.tsx',
                    'app/(mobile-ui)/withdraw/[country]/page.tsx',
                ],
            },
            {
                name: 'SavedAccountsMapping (in SavedAccountsView)',
                realUsages: 2,
                status: 'live',
                devUsages: 0,
                source: 'components/Common/SavedAccountsView.tsx',
                divergence:
                    "Saved-bank-account list; .maps ActionListCard but overrides padding to p-4 py-2.5 (unique height). Left slot = flag Image with an overlaid yellow bank-badge (-bottom-1 -right-1), an avatar pattern shared only with TokenListItem's chain badge. Re-implements the isFirst/isLast/isSingle position ternary inline (5th copy).",
                usedIn: [
                    'components/Claim/Link/views/BankFlowManager.view.tsx',
                    'components/AddWithdraw/AddWithdrawRouterView.tsx',
                ],
            },
            {
                name: 'ProfileMenuItem',
                realUsages: 3,
                status: 'live',
                devUsages: 0,
                source: 'components/Profile/components/ProfileMenuItem.tsx',
                divergence:
                    "Settings/menu row. Wraps Global/Card at p-4 (taller than ActionListCard) and renders as Link | onClick-Card | disabled-Card (3 render branches). Right slot = NavigationArrow | endIcon | StatusBadge 'soon'. Does the same 'icon+label+chevron' job as ActionListCard but is a separate impl — merge/variant candidate.",
                usedIn: [
                    'components/Profile/index.tsx',
                    'components/Card/YourCardScreen.tsx',
                    'components/Card/CardPinScreen.tsx',
                ],
            },
            {
                name: 'KycStatusItem',
                realUsages: 2,
                status: 'live',
                devUsages: 0,
                source: 'components/Kyc/KycStatusItem.tsx',
                divergence:
                    'Synthetic feed row for identity-verification status. Wraps Global/Card (default py-2) with gap-4 icon + title + StatusPill; opens KycStatusDrawer. Self-sources status from useIdentityVerification (no status prop). One of 3 synthetic feed rows (KYC/Badge/CardUnlock) that each hand-roll a near-identical Card layout.',
                usedIn: ['components/Home/HomeHistory.tsx', 'app/(mobile-ui)/history/page.tsx'],
            },
            {
                name: 'BadgeStatusItem',
                realUsages: 2,
                status: 'variant',
                devUsages: 0,
                source: 'components/Badges/BadgeStatusItem.tsx',
                divergence:
                    "Synthetic badge-milestone feed row. Card with gap-4, but uses a size-8 badge Image + InvitesIcon right slot instead of KycStatusItem's StatusPill — same feed-row shape, different left/right slots. Parallel impl to KycStatusItem/CardUnlockHistoryItem; the three could share one SyntheticFeedRow.",
                usedIn: ['components/Home/HomeHistory.tsx', 'app/(mobile-ui)/history/page.tsx'],
            },
            {
                name: 'CardUnlockHistoryItem',
                realUsages: 2,
                status: 'variant',
                devUsages: 0,
                source: 'components/Card/CardUnlockHistoryItem.tsx',
                divergence:
                    "Third synthetic feed row (card-unlock milestone). Uniquely wraps Card in a native <button> for a11y and uses a h-10 w-10 bg-primary-3 icon circle (bigger than KycStatusItem's KYCStatusIcon and BadgeStatusItem's size-8) — same feed-row job, third divergent avatar/left-slot size. Explicitly documented as 'Mirrors KycStatusItem's shape'.",
                usedIn: ['components/Home/HomeHistory.tsx', 'app/(mobile-ui)/history/page.tsx'],
            },
            {
                name: 'PaymentInfoRow',
                realUsages: 21,
                status: 'canonical',
                devUsages: 0,
                source: 'components/Payment/PaymentInfoRow.tsx',
                divergence:
                    "Canonical label/value detail row (NOT a Card — a flex col with dashed bottom-border border-b border-dashed, hideBottomBorder to drop the last divider). Distinct family from the Card-based rows: this is the 'key: value' receipt/detail row, used 21x. Optional copy-to-clipboard + tooltip.",
                usedIn: [
                    'components/TransactionDetails/TransactionDetailsReceipt.tsx',
                    'components/AddMoney/components/AddMoneyBankDetails.tsx',
                    'components/Kyc/states/KycCompleted.tsx',
                    'app/(mobile-ui)/qr-pay/page.tsx',
                    'components/Withdraw/views/Confirm.withdraw.view.tsx',
                ],
            },
            {
                name: 'CountryRegionRow',
                realUsages: 0,
                status: 'dead',
                devUsages: 0,
                source: 'components/Kyc/CountryRegionRow.tsx',
                divergence:
                    "DEAD: exported (components/Kyc/CountryRegionRow.tsx) but grep finds zero imports and zero <CountryRegionRow renders anywhere in src. Thin wrapper over PaymentInfoRow(label='Country/Region', value=CountryFlagAndName). Delete candidate.",
                verified: true,
            },
            {
                name: 'KYCStatusDrawerItem',
                realUsages: 4,
                status: 'variant',
                devUsages: 0,
                source: 'components/Kyc/KYCStatusDrawerItem.tsx',
                divergence:
                    "Near-duplicate of KycStatusItem for the drawer context: same Card + KYCStatusIcon + 'Identity verification' title, but uses a StatusBadge (not StatusPill), takes an explicit status prop instead of self-sourcing, and is non-clickable. Two components render the same KYC row differently — merge/variant candidate.",
                usedIn: [
                    'components/Kyc/states/KycProcessing.tsx',
                    'components/Kyc/states/KycFailed.tsx',
                    'components/Kyc/states/KycCompleted.tsx',
                    'components/Kyc/states/KycActionRequired.tsx',
                ],
            },
            {
                name: 'RejectLabelsList',
                realUsages: 4,
                status: 'live',
                devUsages: 0,
                source: 'components/Kyc/RejectLabelsList.tsx',
                divergence:
                    "KYC reject-reason list; .maps InfoCard (not Card/ActionListCard) in a space-y-2 stack. Distinct 'reason card' row family. Empty/fallback state = a single generic InfoCard rather than an EmptyState — inconsistent with every other list's empty handling.",
                usedIn: [
                    'components/Kyc/states/KycFailed.tsx',
                    'components/Kyc/states/KycActionRequired.tsx',
                    'components/Kyc/KycFailedContent.tsx',
                    'components/Kyc/modals/KycActionRequiredModal.tsx',
                ],
            },
        ],
    },
    {
        category: 'Composite Cards',
        layer: 'components',
        summary:
            "Grep-verified 18 composite *Card* components beyond the two base primitives (0_Bruddle/Card named-export + Global/Card default-export). The vast majority are LIVE and correctly compose one of the two base primitives — nothing here is showcase-only, because the /dev design-system showcase only demonstrates the base Global/Card, NOT a single one of these composites (all 12 composites I spot-checked have 0 dev usages). The real divergence problem is a cluster of ad-hoc leaderboard cards (QuestCard, UserRankCard) that reject BOTH primitives and hand-roll `border-2 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]` inline, drifting from the DS `border-n-1 rounded-sm shadow-4` token — and UserRankCard even omits `rounded-sm` entirely (sharp corners). A second family — the 4 OG cards (InviteCardOG/PaymentCardOG/ProfileCardOG/ReceiptCardOG) — necessarily roll their own `border: '3px solid #000'` inline because they render via Satori/ImageResponse where no React Card component exists (justified fork, not a bug). PioneerCard3D is a fully bespoke 3D-tilt marketing card (radius as % , 2px border, motion boxShadow) with no relation to either primitive. Two components are showcase-adjacent-infra: CatalogCard is dev-only (0 real usages, powers the DS catalog itself).",
        items: [
            {
                name: 'TransactionCard',
                realUsages: 2,
                status: 'live',
                devUsages: 0,
                source: 'components/TransactionDetails/TransactionCard.tsx',
                divergence:
                    'Composes Global/Card via position prop (stacked-list variant) — no border/radius fork; correct DS reuse.',
                usedIn: ['components/Home/HomeHistory.tsx', 'app/(mobile-ui)/history/page.tsx'],
            },
            {
                name: 'TransactionDetailsHeaderCard',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/TransactionDetails/TransactionDetailsHeaderCard.tsx',
                divergence:
                    "Composes Global/Card with position='single' + p-4/md:p-6 override; no rolled border. Clean.",
                usedIn: ['components/TransactionDetails/TransactionDetailsReceipt.tsx'],
            },
            {
                name: 'UserCard',
                realUsages: 5,
                status: 'live',
                devUsages: 0,
                source: 'components/User/UserCard.tsx',
                divergence:
                    'Composes Global/Card (gap-4 p-4). Functionally overlaps PeanutActionDetailsCard (both render avatar+title+amount over a Global/Card) — merge candidate; UserCard is the send/request-input variant, PeanutActionDetailsCard the claim/withdraw variant.',
                usedIn: [
                    'features/payments/flows/direct-send/views/SendInputView.tsx',
                    'features/payments/flows/semantic-request/views/SemanticRequestInputView.tsx',
                    'features/payments/flows/contribute-pot/views/ContributePotInputView.tsx',
                    'components/Request/direct-request/views/Initial.direct.request.view.tsx',
                    'components/AddMoney/views/RhinoDeposit.view.tsx',
                ],
            },
            {
                name: 'PeanutActionDetailsCard',
                realUsages: 11,
                status: 'live',
                devUsages: 0,
                source: 'components/Global/PeanutActionDetailsCard/index.tsx',
                divergence:
                    "Composes Global/Card (p-4). Most-used composite. Duplicates UserCard's avatar+title+amount layout with a bigger 10-branch transactionType switch — the two are variants of one 'action summary card' that should be unified.",
                usedIn: [
                    'components/Claim/Link/Onchain/Success.view.tsx',
                    'components/Withdraw/views/Confirm.withdraw.view.tsx',
                    'components/Claim/Link/Initial.view.tsx',
                    'app/(mobile-ui)/withdraw/[country]/bank/page.tsx',
                    'features/payments/flows/semantic-request/views/SemanticRequestConfirmView.tsx',
                ],
            },
            {
                name: 'PeanutActionCard',
                realUsages: 2,
                status: 'live',
                devUsages: 0,
                source: 'components/Global/PeanutActionCard/index.tsx',
                divergence: 'Composes Global/Card (gap-3 p-4); static request/send promo blurb. Clean reuse, no fork.',
                usedIn: [
                    'components/Send/link/views/Initial.link.send.view.tsx',
                    'components/Request/link/views/Create.request.link.view.tsx',
                ],
            },
            {
                name: 'MantecaDetailsCard',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/Global/MantecaDetailsCard/index.tsx',
                divergence:
                    "Composes Global/Card with a redundant className='rounded-sm' — Global/Card already applies rounded-sm for position='single' (default), so the override is a no-op / dead class.",
                usedIn: ['components/Claim/Link/views/MantecaReviewStep.tsx'],
            },
            {
                name: 'ContributorCard',
                realUsages: 2,
                status: 'live',
                devUsages: 0,
                source: 'components/Global/Contributors/ContributorCard.tsx',
                divergence: 'Composes Global/Card via position prop (stacked list rows). No border fork. Clean.',
                usedIn: [
                    'features/payments/flows/contribute-pot/components/ContributorsDrawer.tsx',
                    'components/TransactionDetails/TransactionDetailsReceipt.tsx',
                ],
            },
            {
                name: 'ActionListCard',
                realUsages: 16,
                status: 'live',
                devUsages: 0,
                source: 'components/ActionListCard/index.tsx',
                divergence:
                    "Most-reused of all composites (16 sites). Composes Global/Card via position for stacked lists; no border/radius fork. The canonical 'tappable list row' — good DS citizen.",
                usedIn: [
                    'components/AddMoney/views/AddMoneyMethodSelection.view.tsx',
                    'components/Send/views/SendRouter.view.tsx',
                    'components/Common/CountryList.tsx',
                    'features/payments/shared/components/PaymentMethodActionList.tsx',
                    'features/limits/views/LimitsPageView.tsx',
                ],
            },
            {
                name: 'InfoCard',
                realUsages: 18,
                status: 'live',
                devUsages: 0,
                source: 'components/Global/InfoCard/index.tsx',
                divergence:
                    'Composes Global/Card but OVERRIDES its border color per variant (border-yellow-9/error-5/secondary-7 etc.) instead of DS border-n-1 black — intentional semantic-banner variant, the one legitimate border override. Highest real usage.',
                usedIn: [
                    'components/AddMoney/views/CryptoDeposit.view.tsx',
                    'components/Kyc/states/KycActionRequired.tsx',
                    'components/Home/WelcomeUnlockModal/index.tsx',
                    'app/(mobile-ui)/profile/backup/page.tsx',
                    'features/limits/components/LimitsWarningCard.tsx',
                ],
            },
            {
                name: 'LimitsWarningCard',
                realUsages: 5,
                status: 'live',
                devUsages: 0,
                source: 'features/limits/components/LimitsWarningCard.tsx',
                divergence:
                    "Wraps InfoCard (2-level composition InfoCard→Global/Card); both 'warning' and 'error' branches hardcode variant='warning' (line 41: `type === 'error' ? 'warning' : 'warning'`) — dead ternary, error styling is faked via iconClassName only.",
                usedIn: [
                    'components/AddMoney/components/InputAmountStep.tsx',
                    'app/(mobile-ui)/withdraw/page.tsx',
                    'app/(mobile-ui)/withdraw/manteca/page.tsx',
                    'app/(mobile-ui)/add-money/[country]/bank/page.tsx',
                    'app/(mobile-ui)/qr-pay/page.tsx',
                ],
            },
            {
                name: 'FiatLimitsLockedCard',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'features/limits/components/FiatLimitsLockedCard.tsx',
                divergence:
                    "Composes Global/Card (position='single' className='p-0'). Clean single-purpose unlock prompt.",
                usedIn: ['features/limits/views/LimitsPageView.tsx'],
            },
            {
                name: 'PointsCard',
                realUsages: 3,
                status: 'live',
                devUsages: 0,
                source: 'components/Common/PointsCard.tsx',
                divergence: 'Composes Global/Card (gap-3 p-3). Clean; passes a ref through for share-image capture.',
                usedIn: [
                    'app/(mobile-ui)/qr-pay/page.tsx',
                    'app/(mobile-ui)/withdraw/manteca/page.tsx',
                    'features/payments/shared/components/PaymentSuccessView.tsx',
                ],
            },
            {
                name: 'SuccessViewDetailsCard',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'components/Global/SuccessViewComponents/SuccessViewDetailsCard.tsx',
                divergence:
                    'Composes the OTHER primitive — 0_Bruddle/Card (named export, p-6) rather than Global/Card. Only composite here that uses the Bruddle standalone-container primitive; consistent with its standalone success-screen role.',
                usedIn: ['components/Send/link/views/Success.link.send.view.tsx'],
            },
            {
                name: 'QuestCard',
                realUsages: 1,
                status: 'adhoc',
                devUsages: 0,
                source: 'app/quests/components/QuestCard.tsx',
                divergence:
                    'Rejects BOTH primitives — hand-rolls `rounded-sm border-2 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]` inline on a motion.div, and repeats the same string on 4 inner leaderboard-row divs. border-2 (not DS border-n-1 1px) + arbitrary shadow instead of shadow-4 token. Prime consolidation target.',
                usedIn: ['app/quests/components/QuestsHero.tsx'],
            },
            {
                name: 'UserRankCard',
                realUsages: 3,
                status: 'adhoc',
                devUsages: 0,
                source: 'app/quests/components/UserRankCard.tsx',
                divergence:
                    "Rejects both primitives; inline `border-2 border-black shadow-[4px_4px_0px_0px_rgba(0,0,0,1)]` AND omits rounded-sm entirely (sharp corners) — visually inconsistent with the DS rounded-sm radius. Duplicate of QuestCard's inner row style. Duplicate/variant of QuestCard.",
                usedIn: [
                    'app/quests/explore/page.tsx',
                    'app/quests/[questId]/page.tsx',
                    'app/quests/components/QuestCard.tsx',
                ],
            },
            {
                name: 'PioneerCard3D',
                realUsages: 2,
                status: 'adhoc',
                devUsages: 0,
                source: 'components/LandingPage/PioneerCard3D.tsx',
                divergence:
                    "Fully bespoke marketing card — no primitive. Inline styles: borderRadius '5.35%' (percentage, not rounded-sm), border '2px solid #000000', framer-motion animated boxShadow. Justified fork (3D parallax tilt), unrelated to the DS Card system.",
                usedIn: ['components/LandingPage/CardPioneers.tsx', 'app/lp/card/CardLandingPage.tsx'],
            },
            {
                name: 'InviteCardOG / PaymentCardOG / ProfileCardOG / ReceiptCardOG',
                realUsages: 4,
                status: 'variant',
                devUsages: 0,
                source: 'components/og/InviteCardOG.tsx, PaymentCardOG.tsx, ProfileCardOG.tsx, ReceiptCardOG.tsx',
                divergence:
                    "Satori/ImageResponse OG-image cards (each imported once in app/api/og/route.tsx). Must roll their own inline `border: '3px solid #000'` because Satori renders outside React DOM where Global/Card's Tailwind classes don't apply — justified fork, not a bug. Counted as one row (4 sibling files, 1 shared call site).",
                usedIn: ['app/api/og/route.tsx'],
            },
            {
                name: 'CatalogCard',
                realUsages: 0,
                status: 'showcase-only',
                devUsages: 4,
                source: 'app/(mobile-ui)/dev/ds/_components/CatalogCard.tsx',
                divergence:
                    'Dev-only design-system catalog tile (used only in app/(mobile-ui)/dev/ds/* index/primitives/patterns/foundations pages). Never rendered in the real product — it IS the showcase infrastructure, not a product card.',
                verified: true,
            },
        ],
    },
]
