import type { UsageCategory } from '../../_components/UsageAudit'

// AUTO-GENERATED by the DS audit inventory sweep (2026-08-25). Do not hand-edit.
// Source: peanut-ui feat/design-system @ 843df91b — swept at 7ae13804 by 10 parallel finders,
// one per DS category, then a mechanical re-count of every row (the adversarial pass).
// Refreshed to 843df91b (the phase-2 styling cleanup, 16 commits, 236 product files) by a delta
// pass: one probe per row over the 7ae13804 corpus and the 843df91b corpus, with the difference
// added to the swept number. A delta is method-independent, so it carries a row forward without
// having to re-derive that row's original bespoke grep. 93 rows moved; the rest are unchanged.
// 165 rows carry a prose or glob key ("inline recipe: text-sm + font-bold", "--color-avatar-*")
// that no single probe reproduces — those numbers still date from 7ae13804.
// Not re-inventoried: PageStack (64), Section (23), ListGroup (9), TitleBlock (1) and
// ActiveCardGate (3) are new primitives from this base and have no row yet.
// Replaces the 2026-06-26 giga-sweep. That method is recoverable from mono commit f9346907,
// file inbox/ds-consolidation-audit/README.md (the folder itself was deleted 2026-08-06).
// Method: usages = call sites over src/**/*.{ts,tsx,css}, minus /dev routes, __tests__ and
// *.test.* — the live-product lens the 2026-06 pass used. A component row counts JSX call sites
// with the ERE `<Name([^A-Za-z]|$)`. The `|$` is load-bearing: Prettier writes multi-line
// `<Name\n  prop=…`, and the 2026-06 sweep missed that form and called three live components dead.
// A token or CSS-class row counts word-bounded occurrences of its key. Every number here was
// machine-measured from the row's own grep and re-measured a second time at assembly, so no count
// is hand-typed.
// devUsages = the same grep counted over /dev routes only, so a row shows the gap between what the
// showcase renders and what the product renders.
export const BIG_COMPONENT_CATEGORIES: UsageCategory[] = [
    {
        category: 'Modals',
        layer: 'components',
        summary:
            'Three overlay primitives are still in the tree, but the balance changed. Global/ActionModal is now the standard: 65 app call sites against 6 for the raw base. Global/Modal (BaseModal, @headlessui/react Dialog+Transition) survives as a low-level escape hatch with 5 direct consumers — SumsubKycWrapper, SumsubNativeSdk, IframeWrapper, QRScannerOverlay and the Typeform host in Global/Layout — plus ActionModal itself. Global/Drawer (vaul) is the third family; it is covered in the next category. Radius still splits at the base. BaseModal paints rounded-md, max-w-[26rem], bg-white, and a bg-n-1/85 overlay with click-to-close wired by hand around a headlessui v2 regression. ActionModal overrides all of it to rounded-sm, border border-border-default, bg-background-default and max-w-[85%], per figma board 17800:57216. So a \'BaseModal\' modal and an \'ActionModal\' modal still do not match by default. Two modals then fight the new border back off: ConfirmInviteModal and NoMoreJailModal both pass modalPanelClassName="rounded-none border-0". Eight more copy-paste the same width recipe, modalPanelClassName="max-w-md mx-8", instead of it being a size prop. The header pattern consolidated. ActionModal owns icon + title + description as one nested stack (icon and head 16px apart, title and description 4px apart, head and CTAs 24px apart). BaseModal\'s own border-b title bar has no app consumer left. The close button is still hard-fixed at top-2 right-2 on the panel; 16 call sites hide it with hideModalCloseButton, and 13 suppress the backdrop with hideOverlay. One hand-rolled centring recipe remains: QRScannerOverlay still passes the old classWrap "sm:m-auto sm:self-center self-center m-4 bg-background rounded-none border-0" — the same string ActionModal absorbed as its default. The two other copies of it are gone. Mount points are centralised: AppGlobals hosts the always-on modals and features/home/components/HomeModals hosts the home-screen stack behind Suspense.',
        items: [
            {
                name: 'Modal (BaseModal, Global/Modal)',
                realUsages: 6,
                devUsages: 2,
                status: 'canonical',
                source: 'components/Global/Modal/index.tsx',
                divergence:
                    'The low-level primitive: headlessui Dialog+Transition. Panel defaults to rounded-md, max-w-[26rem], bg-white, self-end on mobile and centred at sm+. Overlay is bg-n-1/85 with onClick wired by hand, because headlessui v2 DialogBackdrop no longer calls onClose. Close button hard-fixed top-2 right-2. Its built-in `title` bar (border-b, text-h6) now has zero app consumers — every caller renders its own header. Only 5 files render it directly; ActionModal is the sixth via a `BaseModal` alias.',
                usedIn: [
                    'components/Global/ActionModal/index.tsx',
                    'components/Global/IframeWrapper/index.tsx',
                    'components/Global/QRScannerOverlay/index.tsx',
                    'components/Kyc/SumsubKycWrapper.tsx',
                    'components/Global/Layout/index.tsx',
                ],
                verified: true,
            },
            {
                name: 'ActionModal (Global/ActionModal)',
                realUsages: 65,
                devUsages: 2,
                status: 'canonical',
                source: 'components/Global/ActionModal/index.tsx',
                divergence:
                    'The standard modal, 65 app call sites. Wraps BaseModal and overrides its look to rounded-sm + border-border-default + bg-background-default + max-w-[85%], centred on every breakpoint. Owns the icon-in-circle + title + description + CTA-array layout, typed with text-heading-xs and text-body-s. Still diverges from BaseModal\'s own rounded-md / max-w-[26rem] defaults. Width is not a prop, so 8 call sites copy modalPanelClassName="max-w-md mx-8".',
                usedIn: [
                    'components/Kyc/InitiateKycModal.tsx',
                    'components/Global/ReConsentModal/index.tsx',
                    'components/Migration/MigrationDownloadModal.tsx',
                    'components/Notifications/SetupNotificationsModal.tsx',
                    'app/(mobile-ui)/qr-pay/page.tsx',
                ],
                verified: true,
            },
            {
                name: 'modalPanelClassName="max-w-md mx-8" (copy-pasted width recipe)',
                realUsages: 8,
                status: 'adhoc',
                source: 'components/Global/ActionModal/index.tsx',
                divergence:
                    'Eight modals set the same panel width by hand because ActionModal exposes no size prop. A `size` prop with sm/md/lg would delete all eight strings.',
                usedIn: [
                    'components/AddMoney/components/OnrampConfirmationModal.tsx',
                    'components/Global/GuestVerificationModal/index.tsx',
                    'components/Global/QRScanner/CameraPermissionModal.tsx',
                    'components/Setup/Views/PasskeySetupHelpModal.tsx',
                    'components/Claim/Link/SendLinkActionList.tsx',
                ],
                verified: true,
            },
            {
                name: 'GuestLoginModal',
                realUsages: 2,
                status: 'live',
                source: 'components/Global/GuestLoginModal/index.tsx',
                divergence:
                    "Now built on ActionModal. It no longer uses BaseModal's built-in title bar — that chrome has no consumer left.",
            },
            {
                name: 'ConfirmInviteModal',
                realUsages: 1,
                status: 'variant',
                source: 'components/Global/ConfirmInviteModal/index.tsx',
                divergence:
                    'Uses ActionModal but undoes its board chrome with modalPanelClassName="rounded-none border-0". One of two modals still fighting the shared panel style.',
                verified: true,
            },
            {
                name: 'NoMoreJailModal',
                realUsages: 1,
                status: 'variant',
                source: 'components/Global/NoMoreJailModal/index.tsx',
                divergence:
                    'Same as ConfirmInviteModal: ActionModal plus modalPanelClassName="rounded-none border-0". Mounted from HomeModals.',
                verified: true,
            },
            {
                name: 'EarlyUserModal',
                realUsages: 1,
                status: 'live',
                source: 'components/Global/EarlyUserModal/index.tsx',
                divergence: 'Mounted from HomeModals behind Suspense.',
            },
            {
                name: 'IosPwaInstallModal',
                realUsages: 1,
                status: 'live',
                source: 'components/Global/IosPwaInstallModal/index.tsx',
                divergence: 'Mounted from HomeModals behind Suspense.',
            },
            {
                name: 'EasterEggModal',
                realUsages: 1,
                devUsages: 2,
                status: 'live',
                source: 'components/Global/EasterEggModal/index.tsx',
                divergence: 'The only modal also rendered in the /dev/ds showcase.',
            },
            {
                name: 'UnsupportedBrowserModal',
                realUsages: 2,
                status: 'live',
                source: 'components/Global/UnsupportedBrowserModal/index.tsx',
                divergence:
                    'ActionModal with modalPanelClassName="max-w-md" — a fourth width value next to max-w-sm, max-w-md mx-8 and max-w-full.',
            },
            {
                name: 'InviteFriendsModal',
                realUsages: 4,
                status: 'live',
                source: 'components/Global/InviteFriendsModal/index.tsx',
            },
            {
                name: 'BalanceWarningModal',
                realUsages: 1,
                status: 'variant',
                source: 'components/Global/BalanceWarningModal/index.tsx',
                divergence:
                    'Forces its own geometry with five !important overrides: modalPanelClassName="!bottom-auto !mx-auto !w-auto !max-w-md !self-center". The heaviest panel override in the app.',
                verified: true,
            },
            {
                name: 'TokenAndNetworkConfirmationModal',
                realUsages: 3,
                status: 'live',
                source: 'components/Global/TokenAndNetworkConfirmationModal/index.tsx',
                divergence: 'ActionModal with modalPanelClassName="max-w-sm".',
            },
            {
                name: 'GuestVerificationModal',
                realUsages: 1,
                status: 'live',
                source: 'components/Global/GuestVerificationModal/index.tsx',
                divergence: 'ActionModal + the copy-pasted "max-w-md mx-8" width string.',
            },
            {
                name: 'ReConsentModal',
                realUsages: 1,
                status: 'live',
                source: 'components/Global/ReConsentModal/index.tsx',
                divergence:
                    'New since the last sweep. Legal re-consent gate on ActionModal, with snooze state in ./utils. High dev count is its Jest suite, not the showcase.',
                verified: true,
            },
            {
                name: 'WelcomeUnlockModal',
                realUsages: 1,
                status: 'live',
                source: 'components/Home/WelcomeUnlockModal/index.tsx',
            },
            {
                name: 'PerkClaimModal',
                realUsages: 1,
                status: 'live',
                source: 'components/Home/PerkClaimModal.tsx',
            },
            {
                name: 'OnrampConfirmationModal',
                realUsages: 1,
                status: 'live',
                source: 'components/AddMoney/components/OnrampConfirmationModal.tsx',
                divergence: 'ActionModal + the copy-pasted "max-w-md mx-8" width string.',
            },
            {
                name: 'SupportedNetworksModal',
                realUsages: 1,
                status: 'live',
                source: 'components/AddMoney/components/SupportedNetworksModal.tsx',
                divergence: 'Moved to ActionModal, so its old rounded-sm panel override is gone.',
            },
            {
                name: 'HowToDepositModal',
                realUsages: 1,
                status: 'live',
                source: 'components/AddMoney/components/HowToDepositModal.tsx',
                divergence: 'Moved to ActionModal, so its old rounded-sm panel override is gone.',
            },
            {
                name: 'LockCardModal',
                realUsages: 1,
                status: 'live',
                source: 'components/Card/LockCardModal.tsx',
            },
            {
                name: 'CancelCardModal',
                realUsages: 1,
                status: 'live',
                source: 'components/Card/CancelCardModal.tsx',
            },
            {
                name: 'CardLimitEditModal',
                realUsages: 1,
                status: 'live',
                source: 'components/Card/CardLimitEditModal.tsx',
                divergence:
                    'Now on ActionModal. Its old rounded-2xl panel — the outlier radius of the 2026-06 sweep — is gone.',
                verified: true,
            },
            {
                name: 'StaleCardApprovalReEnableModal',
                realUsages: 1,
                status: 'live',
                source: 'components/Global/StaleCardApproval/ReEnableModal.tsx',
                divergence:
                    'New since the last sweep. Card-approval recovery prompt on ActionModal, mounted once in app/AppGlobals.tsx. Note the import renames the default export, so a probe on `<ReEnableModal` reads 0 — the call site is `<StaleCardApprovalReEnableModal`.',
                verified: true,
            },
            {
                name: 'BadgeDetailModal',
                realUsages: 3,
                status: 'live',
                source: 'components/Badges/BadgeDetailModal.tsx',
                divergence:
                    'New since the last sweep. ActionModal with modalPanelClassName="m-0" — a fifth panel-geometry recipe.',
            },
            {
                name: 'InitiateKycModal',
                realUsages: 7,
                status: 'live',
                source: 'components/Kyc/InitiateKycModal.tsx',
                divergence:
                    'ActionModal with modalPanelClassName="max-w-full m-2" — full-bleed, unlike every other KYC modal.',
            },
            {
                name: 'SumsubKycModals (modal group)',
                realUsages: 13,
                status: 'live',
                source: 'components/Kyc/SumsubKycModals.tsx',
                divergence:
                    'Renders three overlays as one unit for the multi-phase KYC flow: SumsubKycWrapper, KycVerificationInProgressModal and the Bridge ToS IframeWrapper. Pairs with the useMultiPhaseKycFlow hook. Same host idea as HomeModals, but scoped to one flow.',
                verified: true,
            },
            {
                name: 'SumsubKycWrapper (BaseModal host)',
                realUsages: 6,
                status: 'adhoc',
                source: 'components/Kyc/SumsubKycWrapper.tsx',
                divergence:
                    'Renders BaseModal directly to host the Sumsub web SDK, then an ActionModal on top for errors. modalPanelClassName="max-w-full". A raw-BaseModal user because the SDK needs a bare panel. Delegates to SumsubNativeSdk when running under Capacitor. Five pages mount it directly instead of going through SumsubKycModals.',
                usedIn: [
                    'app/(mobile-ui)/card/page.tsx',
                    'app/(mobile-ui)/qr-pay/page.tsx',
                    'app/(mobile-ui)/withdraw/manteca/page.tsx',
                    'features/limits/components/IncreaseLimitsButton.tsx',
                    'components/Kyc/SumsubKycModals.tsx',
                ],
                verified: true,
            },
            {
                name: 'SumsubNativeSdk (BaseModal host)',
                realUsages: 1,
                status: 'adhoc',
                source: 'components/Kyc/SumsubNativeSdk.tsx',
                divergence:
                    'Second raw-BaseModal host, for the Capacitor native Sumsub SDK. Replaces the old SumsubKycModals row.',
                verified: true,
            },
            {
                name: 'KycVerificationInProgressModal',
                realUsages: 1,
                status: 'live',
                source: 'components/Kyc/KycVerificationInProgressModal.tsx',
            },
            {
                name: 'KycReverificationPendingModal',
                realUsages: 2,
                status: 'live',
                source: 'components/Kyc/KycReverificationPendingModal.tsx',
                divergence: 'New since the last sweep. ActionModal.',
            },
            {
                name: 'AdvisoryPreemptModal',
                realUsages: 2,
                status: 'live',
                source: 'components/Kyc/AdvisoryPreemptModal.tsx',
                divergence: 'New since the last sweep. ActionModal.',
            },
            {
                name: 'KycActionRequiredModal',
                realUsages: 1,
                status: 'live',
                source: 'components/Kyc/modals/KycActionRequiredModal.tsx',
            },
            {
                name: 'KycFailedModal',
                realUsages: 1,
                status: 'live',
                source: 'components/Kyc/modals/KycFailedModal.tsx',
            },
            {
                name: 'KycProcessingModal',
                realUsages: 1,
                status: 'live',
                source: 'components/Kyc/modals/KycProcessingModal.tsx',
            },
            {
                name: 'UnlockRegionModal',
                realUsages: 1,
                status: 'live',
                source: 'components/IdentityVerification/UnlockRegionModal.tsx',
            },
            {
                name: 'SetupNotificationsModal',
                realUsages: 1,
                status: 'live',
                source: 'components/Notifications/SetupNotificationsModal.tsx',
                divergence: 'ActionModal with modalPanelClassName="m-0 max-w-[90%]" — a sixth width value.',
            },
            {
                name: 'CameraPermissionModal',
                realUsages: 1,
                status: 'live',
                source: 'components/Global/QRScanner/CameraPermissionModal.tsx',
                divergence: 'ActionModal + the copy-pasted "max-w-md mx-8" width string.',
            },
            {
                name: 'RainCooldownIntroModal',
                realUsages: 1,
                status: 'live',
                source: 'components/Global/RainCooldown/IntroModal.tsx',
                divergence: 'Mounted once in app/AppGlobals.tsx.',
            },
            {
                name: 'PasskeySetupHelpModal',
                realUsages: 1,
                status: 'live',
                source: 'components/Setup/Views/PasskeySetupHelpModal.tsx',
                divergence: 'ActionModal + the copy-pasted "max-w-md mx-8" width string.',
            },
            {
                name: 'MigrationDownloadModal',
                realUsages: 1,
                status: 'live',
                source: 'components/Migration/MigrationDownloadModal.tsx',
                divergence:
                    'New since the last sweep. PWA-to-native migration prompt on ActionModal, mounted from HomeModals. Dev count is its Jest suite.',
            },
            {
                name: 'ScanToDownloadModal',
                realUsages: 2,
                status: 'live',
                source: 'components/Migration/ScanToDownloadModal.tsx',
                divergence: 'New since the last sweep. Second half of the migration pair, mounted from HomeModals.',
            },
            {
                name: 'ReviewPromptModal',
                realUsages: 1,
                status: 'live',
                source: 'components/Migration/ReviewPromptModal.tsx',
                divergence:
                    'New since the last sweep. App-store review prompt on ActionModal, mounted from HomeModals.',
            },
            {
                name: 'QRScannerOverlay (BaseModal ad-hoc)',
                realUsages: 2,
                status: 'adhoc',
                source: 'components/Global/QRScannerOverlay/index.tsx',
                divergence:
                    'The last hand-rolled centred panel: classWrap="sm:m-auto sm:self-center self-center m-4 bg-background rounded-none border-0". ActionModal now ships that exact recipe as its default, so this is a straight migration candidate. The other two copies (NoMoreJailModal, ConfirmInviteModal) already moved.',
                verified: true,
            },
            {
                name: 'IframeWrapper (BaseModal ad-hoc, external SDK host)',
                realUsages: 2,
                status: 'adhoc',
                source: 'components/Global/IframeWrapper/index.tsx',
                divergence:
                    'Renders BaseModal with classWrap="h-full w-full !max-w-none sm:!max-w-[600px] border-none sm:m-auto m-0" for a full-bleed iframe, plus an ActionModal for its confirm step. Two overlay systems in one file.',
                verified: true,
            },
            {
                name: 'SecurityVerificationOverlay',
                realUsages: 1,
                status: 'adhoc',
                source: 'components/Global/SecurityVerificationOverlay/index.tsx',
                divergence:
                    'New since the last sweep. A blocking overlay built from a plain fixed div — no BaseModal, no Drawer, no headlessui. A fourth overlay mechanism with no focus trap or escape handling.',
                verified: true,
            },
            {
                name: 'HomeModals (modal host)',
                realUsages: 1,
                status: 'live',
                source: 'features/home/components/HomeModals.tsx',
                divergence:
                    'New since the last sweep. Single host for the home-screen modal stack — 8 modals behind LazyLoadErrorBoundary + Suspense, ordered by priority. Replaces the old pattern of each page mounting its own. AppGlobals plays the same role for always-on modals.',
                verified: true,
            },
        ],
    },
    {
        category: 'Drawers & Sheets',
        layer: 'components',
        summary:
            "Global/Drawer is the one bottom-sheet primitive and it is used everywhere a sheet is needed: 10 app call sites across nine feature drawers. It wraps vaul, adds a `nested` flag that switches to vaul's NestedRoot (a plain Root inside a Root double-applies the background scale and fights the scroll lock), and paints the sheet chrome per figma board 17490:115877 — rounded-t-[10px], bg-background-page, no border, a 32x5 handle 8px from the top with 24px below, and a max-h-[80vh] md:max-w-xl scroll area with pb-safe-bottom. The overlay is bg-black/80, separate from BaseModal's bg-n-1/85. The compound parts split three ways. DrawerContent and DrawerTitle are live (10 and 11 app uses); DrawerHeader has 4 and DrawerDescription 2; DrawerFooter and DrawerClose have zero app uses and exist only in the /dev/ds showcase — delete candidates. The real divergence is padding. DrawerContent ships none, so every drawer invents its own: pb-4, p-4 pb-12, py-4, px-4 pb-6, pt-4, py-6, px-5 pt-1 pb-6, px-4 pb-8, pb-1. Nine drawers, nine recipes. A padding prop or a padded body slot would collapse all of them. Close handling also diverges: some drawers take onOpenChange, others take onClose, and vaul's own DrawerClose is unused. Two components stay outside the primitive. SupportDrawer hand-rolls a fixed panel with its own rounded-t-[10px], its own border, z-[999999] and a rounded-full handle instead of the rounded-round token one. Global/Modal is still a bottom sheet on mobile through its self-end default, but with only 6 direct consumers left the overlap it used to cause is nearly gone.",
        items: [
            {
                name: 'Drawer (base vaul primitive)',
                realUsages: 10,
                devUsages: 3,
                status: 'canonical',
                source: 'components/Global/Drawer/index.tsx',
                divergence:
                    'vaul Root wrapper. `nested` picks NestedRoot so a drawer opened from a drawer stacks instead of double-scaling. Chrome from board 17490:115877: rounded-t-[10px], bg-background-page, no border, handle 32x5 with mt-2 mb-6, scroll area max-h-[80vh] md:max-w-xl pb-safe-bottom, overlay bg-black/80. DrawerFooter and DrawerClose are exported but unused outside /dev/ds.',
                usedIn: [
                    'components/TransactionDetails/TransactionDetailsDrawer.tsx',
                    'components/Global/CancelSendLinkDrawer/index.tsx',
                    'components/AddMoney/components/ChooseNetworkDrawer.tsx',
                    'features/home/components/HomeActionDrawers.tsx',
                    'components/Global/QRBottomDrawer/index.tsx',
                ],
                verified: true,
            },
            {
                name: 'DrawerContent',
                realUsages: 10,
                devUsages: 3,
                status: 'canonical',
                source: 'components/Global/Drawer/index.tsx',
                divergence:
                    'Ships zero padding, so all nine feature drawers hand-write their own. Also owns `accessibleTitle`, the sr-only DialogTitle that silences the Radix a11y warning — no app drawer passes it, only the tests do, so every visible-title drawer relies on its own DrawerTitle instead.',
                verified: true,
            },
            {
                name: 'DrawerTitle',
                realUsages: 11,
                devUsages: 2,
                status: 'canonical',
                source: 'components/Global/Drawer/index.tsx',
                divergence:
                    'Typed with text-heading-card (18/700/24) rather than the vaul boilerplate trio. Callers that pass text-heading-s win cleanly, because the token and the caller class sit in the same conflict group.',
                verified: true,
            },
            {
                name: 'DrawerHeader / DrawerDescription',
                realUsages: 6,
                devUsages: 4,
                status: 'variant',
                source: 'components/Global/Drawer/index.tsx',
                divergence:
                    "Only 4 of 9 drawers use DrawerHeader and only 2 use DrawerDescription; the rest hand-build their header row. DrawerHeader's own `p-4 text-center sm:text-left` then gets overridden at 3 of its 4 call sites.",
                usedIn: [
                    'components/AddMoney/components/ChooseNetworkDrawer.tsx',
                    'components/Global/CancelSendLinkDrawer/index.tsx',
                    'components/Card/CardUnlockDrawer.tsx',
                    'features/payments/flows/contribute-pot/components/ContributorsDrawer.tsx',
                ],
                verified: true,
            },
            {
                name: 'DrawerFooter / DrawerClose',
                realUsages: 0,
                devUsages: 3,
                status: 'showcase-only',
                source: 'components/Global/Drawer/index.tsx',
                divergence:
                    'Exported by the primitive and rendered only in app/(mobile-ui)/dev/ds/patterns/drawer. Two greps confirm zero app call sites: `<DrawerFooter` finds nothing outside /dev/, and a plain text grep for DrawerFooter / DrawerClose finds only the definition, the export line and the showcase. Delete candidates.',
                verified: true,
            },
            {
                name: 'TransactionDetailsDrawer',
                realUsages: 3,
                status: 'live',
                source: 'components/TransactionDetails/TransactionDetailsDrawer.tsx',
                divergence:
                    'DrawerContent className="pb-4", inner px-4. The sheet the drawer chrome was designed against (board 17490:115877).',
            },
            {
                name: 'KycStatusDrawer',
                realUsages: 1,
                status: 'live',
                source: 'components/Kyc/KycStatusDrawer.tsx',
                divergence: 'DrawerContent className="p-4 pb-12" — the largest bottom padding of the nine.',
            },
            {
                name: 'BadgeStatusDrawer',
                realUsages: 1,
                status: 'live',
                source: 'components/Badges/BadgeStatusDrawer.tsx',
                divergence:
                    'DrawerContent className="py-4" plus an inner "space-y-4 p-4" — padding applied twice, at two levels.',
            },
            {
                name: 'CardUnlockDrawer',
                realUsages: 2,
                status: 'live',
                source: 'components/Card/CardUnlockDrawer.tsx',
                divergence: 'Inner "flex flex-col gap-4 px-4 pb-6". Uses DrawerHeader; closes via onOpenChange.',
            },
            {
                name: 'ChooseNetworkDrawer',
                realUsages: 1,
                status: 'live',
                source: 'components/AddMoney/components/ChooseNetworkDrawer.tsx',
                divergence:
                    'DrawerContent "pt-4", header "pt-0 text-center", body "flex flex-col px-4 pb-6". One of only two drawers using the full Header + Title + Description trio. Its rows are now 0_Bruddle/ListItem.',
            },
            {
                name: 'ContributorsDrawer',
                realUsages: 1,
                status: 'live',
                source: 'features/payments/flows/contribute-pot/components/ContributorsDrawer.tsx',
                divergence:
                    'DrawerContent "py-6", inner "max-h-[60vh] overflow-auto px-4" — a second scroll cap inside DrawerContent\'s own max-h-[80vh]. The only drawer using DrawerTrigger.',
            },
            {
                name: 'CancelSendLinkDrawer',
                realUsages: 2,
                status: 'live',
                source: 'components/Global/CancelSendLinkDrawer/index.tsx',
                divergence:
                    'New since the last sweep — this was CancelSendLinkModal, now converted to a sheet. Body "flex flex-col items-center gap-4 px-5 pt-1 pb-6 text-center": px-5 is the only 20px horizontal padding among the nine drawers.',
                verified: true,
            },
            {
                name: 'HomeActionDrawers',
                realUsages: 1,
                status: 'live',
                source: 'features/home/components/HomeActionDrawers.tsx',
                divergence:
                    'New since the last sweep. One host that drives every home action sheet from a `useHomeDrawer` key. Rows are 0_Bruddle/ListItem with getCardPosition — the reference implementation for a list inside a drawer. DrawerContent "px-4 pb-8".',
                verified: true,
            },
            {
                name: 'QRBottomDrawer',
                realUsages: 1,
                status: 'variant',
                source: 'components/Global/QRBottomDrawer/index.tsx',
                divergence:
                    'The only snap-point drawer: two fixed heights from constants/qr-drawer.consts, with drag-down at the first snap suppressed so vaul does not close it. DrawerContent "pb-1". Renders DrawerTitle with its own "space-y-2 mb-8" instead of DrawerHeader.',
            },
            {
                name: 'SupportDrawer',
                realUsages: 5,
                status: 'adhoc',
                source: 'components/Global/SupportDrawer/index.tsx',
                divergence:
                    "Does not use the Drawer primitive at all. Hand-rolls a fixed inset-x-0 panel with its own rounded-t-[10px], its own border, z-[999999] and an h-1.5 w-10 rounded-full bg-black handle instead of the primitive's 32x5 rounded-round one. It hosts the Crisp chat iframe and tracks the visual viewport, which is why it never moved — but the chrome should come from DrawerContent.",
                verified: true,
            },
            {
                name: 'Modal (Global/Modal, mobile bottom-sheet default)',
                realUsages: 6,
                devUsages: 2,
                status: 'duplicate',
                source: 'components/Global/Modal/index.tsx',
                divergence:
                    "BaseModal's panel is still `self-end ... sm:self-auto`, so on mobile it is a second bottom sheet with no handle, no drag and a different overlay (bg-n-1/85 vs bg-black/80). The overlap has shrunk a lot: 6 direct consumers now, down from 15, because ActionModal forces self-center on all 65 of its call sites.",
                verified: true,
            },
        ],
    },
    {
        category: 'Lists & Rows',
        layer: 'patterns',
        summary:
            'This category changed the most. 0_Bruddle/ListItem now exists and is the canonical row: 38 app call sites across 25 files. It comes from figma board 17802:61530 — leading slot, title at text-body-m-semibold, body at text-body-s/secondary, trailing slot, optional chevron, 56px tall at p-4, above the 44px touch floor. It handles the row states the old rows each got wrong on their own: pressed fills with background-disabled, disabled fills background-disabled + border-subtle and greys the title while leaving content at full opacity, keyboard Enter/Space activates, and every click fires haptics. Under it sits Global/Card, the grouping primitive: 47 app files, w-full bg-white px-4 py-2, and a `position` prop (single/first/middle/last) that owns the stacked border-radius and the shared top border. The old hand-rolled isFirst/isLast ternary is mostly gone — getCardPosition now has 12 app callers against 3 remaining inline ternaries (AddWithdrawCountriesList, Contacts.view, and one more). ActionListCard is deleted; its job split into ListItem plus three feature-specific action lists (PaymentMethodActionList, SendLinkActionList, RequestPotActionList). What still diverges is padding. Global/Card defaults to px-4 py-2, ListItem overrides to p-4, and the rows that never migrated keep their own: TokenListItem py-3.5, ProfileMenuItem and NetworkListItem p-4, SavedAccountsView p-4 py-2.5. The two transaction feeds also still duplicate each other: HomeHistory (top 5) and app/(mobile-ui)/history/page.tsx run near-identical WebSocket merge, synthetic-entry injection and drawer memo code, differing only in date grouping — and history/page is one of the files still hand-rolling its row position.',
        items: [
            {
                name: 'ListItem (0_Bruddle/ListItem)',
                realUsages: 38,
                devUsages: 20,
                status: 'canonical',
                source: 'components/0_Bruddle/ListItem.tsx',
                divergence:
                    "New since the last sweep and now the canonical row — 38 app call sites in 25 files. Board 17802:61530: leading slot, title text-body-m-semibold, body text-body-s/foreground-secondary, trailing slot, optional chevron. Wraps Global/Card and forwards `position`, so grouping and radius stay in one place. Overrides Card's px-4 py-2 to p-4, which is why a ListItem row and a bare Card row are not the same height.",
                usedIn: [
                    'components/Common/CountryList.tsx',
                    'components/Send/views/Contacts.view.tsx',
                    'features/home/components/HomeActionDrawers.tsx',
                    'features/payments/shared/components/PaymentMethodActionList.tsx',
                ],
                verified: true,
            },
            {
                name: 'Global/Card (row + grouping primitive)',
                realUsages: 47,
                devUsages: 4,
                status: 'canonical',
                source: 'components/Global/Card/index.tsx',
                divergence:
                    'Counted as files, not call sites: `<Card` is ambiguous because 0_Bruddle/Card renders the same tag. 47 app files import the default export. w-full bg-white px-4 py-2; `position` picks rounded-sm / rounded-t-sm / none / rounded-b-sm and drops the top border on middle and last rows so stacked rows share one hairline. Clickable cards get role=button, tabIndex and Enter/Space by default. Still paints literal bg-white rather than a background token, unlike 0_Bruddle/Card which uses bg-background-default.',
                usedIn: [
                    'components/0_Bruddle/ListItem.tsx',
                    'components/Home/HomeHistory.tsx',
                    'components/Profile/components/ProfileMenuItem.tsx',
                    'components/Global/TokenSelector/Components/TokenListItem.tsx',
                    'components/TransactionDetails/ReceiptDetailsCard.tsx',
                ],
                verified: true,
            },
            {
                name: 'getCardPosition (Global/Card/card.utils)',
                realUsages: 17,
                status: 'canonical',
                source: 'components/Global/Card/card.utils.ts',
                divergence:
                    "The shared index-to-position helper, 12 app callers now against 3 at the last sweep. Three inline ternaries survive (AddWithdrawCountriesList, Send/Contacts.view, and history/page's local calc) — the remaining copy-paste of the same four-way branch.",
                usedIn: [
                    'components/Home/HomeHistory.tsx',
                    'components/Common/CountryList.tsx',
                    'components/Settings/LanguageView.tsx',
                    'features/limits/views/LimitsPageView.tsx',
                    'features/home/components/HomeActionDrawers.tsx',
                ],
                verified: true,
            },
            {
                name: 'PaymentInfoRow',
                realUsages: 68,
                status: 'canonical',
                source: 'components/Payment/PaymentInfoRow.tsx',
                divergence:
                    'The label/value row, and the single busiest row in the app at 68 call sites (21 at the last sweep). Separate family from ListItem: it is a key-value line inside a card, not a tappable list row.',
            },
            {
                name: 'DataRow (was ReceiptRow)',
                realUsages: 40,
                status: 'duplicate',
                source: 'components/0_Bruddle/DataRow.tsx',
                divergence:
                    'New since the last sweep, and a second label/value row at 40 call sites. The phase-2 sweep promoted it into 0_Bruddle and renamed it ReceiptRow -> DataRow; every call site moved with it, so the count is unchanged. Same job as PaymentInfoRow, with extra props for copy, more-info and loading. The two together are 108 call sites of the same idea — the biggest single merge left in this category.',
                verified: true,
            },
            {
                name: 'ProfileMenuItem',
                realUsages: 18,
                devUsages: 3,
                status: 'variant',
                source: 'components/Profile/components/ProfileMenuItem.tsx',
                divergence:
                    "18 call sites, up from 3 — it grew instead of migrating. Wraps Global/Card with its own p-4 and its own leading-icon + chevron layout, which is exactly ListItem's anatomy. Highest-value single migration in this category.",
                verified: true,
            },
            {
                name: 'TokenListItem',
                realUsages: 2,
                status: 'variant',
                source: 'components/Global/TokenSelector/Components/TokenListItem.tsx',
                divergence:
                    'Wraps Global/Card directly with py-3.5 — the only 14px vertical padding among the rows. Pre-dates ListItem.',
            },
            {
                name: 'NetworkListItem',
                realUsages: 1,
                status: 'variant',
                source: 'components/Global/TokenSelector/Components/NetworkListItem.tsx',
                divergence: 'Sibling of TokenListItem, p-4. Both wrap Global/Card by hand rather than ListItem.',
            },
            {
                name: 'NetworkListView (list container)',
                realUsages: 1,
                status: 'live',
                source: 'components/Global/TokenSelector/Components/NetworkListView.tsx',
            },
            {
                name: 'ScrollableList',
                realUsages: 2,
                status: 'live',
                source: 'components/Global/TokenSelector/Components/ScrollableList.tsx',
                divergence:
                    'Token-selector-only scroll container. No other list uses it; the rest set their own overflow-auto and max-h.',
            },
            {
                name: 'DepositMethodList (list container)',
                realUsages: 1,
                status: 'live',
                source: 'components/AddMoney/components/DepositMethodList.tsx',
                divergence:
                    'Migrated to 0_Bruddle/ListItem. Still computes its own `determinedPosition` rather than calling getCardPosition.',
            },
            {
                name: 'CountryList (list container)',
                realUsages: 3,
                status: 'canonical',
                source: 'components/Common/CountryList.tsx',
                divergence:
                    'The reference list: 0_Bruddle/ListItem rows + getCardPosition. Has a matching CountryListSkeleton built from the same two pieces.',
            },
            {
                name: 'AddWithdrawCountriesList',
                realUsages: 4,
                status: 'variant',
                source: 'components/AddWithdraw/AddWithdrawCountriesList.tsx',
                divergence:
                    'Uses ListItem but still hand-rolls the position with an inline four-way ternary instead of getCardPosition. One of three remaining inline copies.',
                verified: true,
            },
            {
                name: 'SavedAccountsView (row mapping)',
                realUsages: 2,
                status: 'variant',
                source: 'components/Common/SavedAccountsView.tsx',
                divergence:
                    'Migrated to ListItem, but hard-codes position="single" on all four row groups, so saved accounts never stack into one bordered block the way every other list does.',
                verified: true,
            },
            {
                name: 'KycStatusItem',
                realUsages: 3,
                status: 'live',
                source: 'components/Kyc/KycStatusItem.tsx',
                divergence: "Feed row for KYC entries, now on ListItem, driven by the feed's `position`.",
            },
            {
                name: 'BadgeStatusItem',
                realUsages: 2,
                status: 'live',
                source: 'components/Badges/BadgeStatusItem.tsx',
                divergence: 'Feed row for badge entries, migrated to ListItem. Was a variant at the last sweep.',
            },
            {
                name: 'CardUnlockHistoryItem',
                realUsages: 3,
                status: 'live',
                source: 'components/Card/CardUnlockHistoryItem.tsx',
                divergence: 'Migrated to ListItem. Was a variant at the last sweep.',
            },
            {
                name: 'KYCStatusDrawerItem',
                realUsages: 4,
                status: 'variant',
                source: 'components/Kyc/KYCStatusDrawerItem.tsx',
                divergence:
                    'Step row inside KycStatusDrawer, still hand-built. Same leading-icon + title + body shape ListItem now owns.',
            },
            {
                name: 'RejectLabelsList',
                realUsages: 4,
                status: 'live',
                source: 'components/Kyc/RejectLabelsList.tsx',
                divergence:
                    'Now renders 0_Bruddle/Notification with `items`, so the check-row markup comes from the primitive instead of being hand-built.',
            },
            {
                name: 'CountryRegionRow',
                realUsages: 0,
                status: 'dead',
                source: 'components/Kyc/CountryRegionRow.tsx',
                divergence:
                    'Still dead. Two greps agree: `<CountryRegionRow` finds zero app renders, and a plain text grep for the name across all of src finds only its own definition and the audit data file that describes it. Thin wrapper over PaymentInfoRow. Delete candidate.',
                verified: true,
            },
            {
                name: 'PaymentMethodActionList',
                realUsages: 2,
                status: 'live',
                source: 'features/payments/shared/components/PaymentMethodActionList.tsx',
                divergence:
                    'New since the last sweep. One of the three action lists that replaced the deleted ActionListCard. Built on 0_Bruddle/ListItem with constants/actionlist.consts.',
                verified: true,
            },
            {
                name: 'SendLinkActionList',
                realUsages: 1,
                status: 'live',
                source: 'components/Claim/Link/SendLinkActionList.tsx',
                divergence:
                    'New since the last sweep. Second ActionListCard replacement, on ListItem. Also opens an ActionModal with the copy-pasted "max-w-md mx-8" width string.',
            },
            {
                name: 'RequestPotActionList',
                realUsages: 1,
                status: 'live',
                source: 'features/payments/flows/contribute-pot/components/RequestPotActionList.tsx',
                divergence:
                    'New since the last sweep. Third ActionListCard replacement, on ListItem. Two ActionModals inside it repeat the "max-w-md mx-8" string.',
            },
            {
                name: 'BadgesRow',
                realUsages: 1,
                status: 'live',
                source: 'components/Badges/BadgesRow.tsx',
                divergence:
                    'New since the last sweep. Horizontal badge strip on Global/Card — a row of items rather than a list row, so it shares the card chrome but not the ListItem anatomy.',
            },
            {
                name: 'HomeHistory (feed list container)',
                realUsages: 2,
                status: 'duplicate',
                source: 'components/Home/HomeHistory.tsx',
                divergence:
                    "Top-5 transaction feed. Uses getCardPosition correctly, but still duplicates the history page's WebSocket merge, synthetic-entry injection and drawer memo logic.",
            },
            {
                name: 'HistoryPage (feed list container)',
                realUsages: 1,
                status: 'duplicate',
                source: 'app/(mobile-ui)/history/page.tsx',
                divergence:
                    'Infinite transaction feed. Same row set and same merge logic as HomeHistory, differing only in date grouping, and it still computes row position locally instead of calling getCardPosition.',
                verified: true,
            },
        ],
    },
    {
        category: 'Composite Cards',
        layer: 'components',
        summary:
            'The card layer now has two primitives with one look. 0_Bruddle/Card is the standalone container — flex-col, rounded-sm, border border-border-default, bg-background-default, no shadow by default, with Card.Header / Title / Description / Content sub-parts typed as text-heading-card and text-body-m. Global/Card is the stacked list container described in the previous category. They agree on radius (rounded-sm) and border, and differ only in background token (bg-background-default vs a literal bg-white) and default padding (none vs px-4 py-2). No file imports both, so `<Card` is ambiguous and both rows are counted as files, not call sites. Global/InfoCard is deleted. Its job moved to 0_Bruddle/Notification — 99 app call sites across 60 files, the single most-used new primitive in this audit. Notification carries priority (info/success/attention/helper/error), optional title, up to two CTAs, an optional dismiss, and an `items` checklist mode that absorbed the check-row markup four modals used to hand-build and each got wrong. Global/MantecaDetailsCard and LandingPage/PioneerCard3D are also gone. What still diverges is padding and colour. Card ships no padding, so call sites pick from p-4 (64 uses), p-6 (33), p-3 (20) and p-2 (14) with no rule for which. The quests cards are the outliers: QuestCard and UserRankCard both use border-2 border-black plus a literal shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] and raw palette fills (bg-yellow-100, bg-pink-100, bg-blue-100, bg-purple-200) that exist in no token. The OG cards are a separate family by necessity — they render in satori for og:image, so they use inline style objects and cannot use Tailwind at all.',
        items: [
            {
                name: 'Card (0_Bruddle/Card)',
                realUsages: 21,
                devUsages: 12,
                status: 'canonical',
                source: 'components/0_Bruddle/Card.tsx',
                divergence:
                    'New since the last sweep. The standalone container, per board 17802:61536: rounded-sm, border-border-default, bg-background-default, no shadow unless shadowSize is passed (4/6/8, primary or secondary). Ships zero padding, so every call site sets its own — p-4, p-6, p-3 and p-2 all appear. Counted as files because `<Card` also matches Global/Card. Sub-parts Card.Header/Title/Description/Content use the card-head and card-content classes plus text-heading-card and text-body-m.',
                usedIn: [
                    'components/Global/EmptyStates/EmptyState.tsx',
                    'components/Global/ExchangeRateWidget/index.tsx',
                    'components/Home/HomeCarouselCTA/CarouselCTA.tsx',
                    'components/Global/SuccessViewComponents/SuccessViewDetailsCard.tsx',
                    'components/Setup/Views/Landing.tsx',
                ],
                verified: true,
            },
            {
                name: 'Notification (0_Bruddle/Notification)',
                realUsages: 99,
                devUsages: 26,
                status: 'canonical',
                source: 'components/0_Bruddle/Notification.tsx',
                divergence:
                    'New since the last sweep and the replacement for the deleted InfoCard and ErrorAlert. 99 app call sites in 60 files — the most-used new primitive here. Board 17802:61535: priority sets tone, background and leading icon (info/success/attention/helper/error); supports body, title + body, dismiss, and up to two CTAs (first purple, second stroke). `items` renders a check-marked checklist and deliberately drops the leading priority icon, because all four former InfoCard checklist call sites passed no icon.',
                usedIn: [
                    'app/(mobile-ui)/profile/backup/page.tsx',
                    'components/AddWithdraw/DynamicBankAccountForm.tsx',
                    'components/Withdraw/views/Confirm.withdraw.view.tsx',
                    'features/limits/components/LimitsWarningCard.tsx',
                    'components/Kyc/RejectLabelsList.tsx',
                ],
                verified: true,
            },
            {
                name: 'TransactionCard',
                realUsages: 3,
                status: 'live',
                source: 'components/TransactionDetails/TransactionCard.tsx',
                divergence:
                    'Now built on 0_Bruddle/ListItem, so the feed row and the standalone card share one anatomy.',
            },
            {
                name: 'TransactionDetailsHeaderCard',
                realUsages: 1,
                status: 'live',
                source: 'components/TransactionDetails/TransactionDetailsHeaderCard.tsx',
            },
            {
                name: 'ReceiptDetailsCard',
                realUsages: 1,
                status: 'live',
                source: 'components/TransactionDetails/ReceiptDetailsCard.tsx',
                divergence:
                    "New since the last sweep. Global/Card with a conditional position ('first' when a QR share block follows, otherwise 'single') — a good use of the grouping prop outside a list.",
            },
            {
                name: 'UserCard',
                realUsages: 5,
                status: 'live',
                source: 'components/User/UserCard.tsx',
                divergence:
                    'Global/Card with "flex flex-col items-center gap-4 p-4" — overrides the card\'s px-4 py-2 to p-4. Body text uses the text-body-xs / foreground-secondary tokens.',
            },
            {
                name: 'PeanutActionDetailsCard',
                realUsages: 11,
                status: 'live',
                source: 'components/Global/PeanutActionDetailsCard/index.tsx',
                divergence:
                    'Busiest composite card at 11 call sites. Wraps Global/Card and hand-builds an avatar cluster with rounded-full sizing rather than using 0_Bruddle/IconBubble.',
            },
            {
                name: 'PeanutActionCard',
                realUsages: 2,
                status: 'live',
                source: 'components/Global/PeanutActionCard/index.tsx',
                divergence:
                    'Sibling of PeanutActionDetailsCard on Global/Card. The two names differ by one word and are easy to confuse.',
            },
            {
                name: 'ContributorCard',
                realUsages: 1,
                status: 'live',
                source: 'components/Global/Contributors/ContributorCard.tsx',
            },
            {
                name: 'LimitsWarningCard',
                realUsages: 5,
                status: 'live',
                source: 'features/limits/components/LimitsWarningCard.tsx',
                divergence:
                    'Now renders 0_Bruddle/Notification instead of the deleted InfoCard. Still draws its own separators with a bare `border-t` div rather than 0_Bruddle/Divider.',
                verified: true,
            },
            {
                name: 'FiatLimitsLockedCard',
                realUsages: 1,
                status: 'live',
                source: 'features/limits/components/FiatLimitsLockedCard.tsx',
            },
            {
                name: 'PointsCard',
                realUsages: 3,
                status: 'live',
                source: 'components/Common/PointsCard.tsx',
                divergence:
                    'Global/Card with p-3 — a third padding value next to the card default (py-2) and the common p-4.',
            },
            {
                name: 'SuccessViewDetailsCard',
                realUsages: 1,
                status: 'live',
                source: 'components/Global/SuccessViewComponents/SuccessViewDetailsCard.tsx',
                divergence: 'Moved from Global/Card to 0_Bruddle/Card since the last sweep.',
            },
            {
                name: 'QuestCard',
                realUsages: 1,
                status: 'adhoc',
                source: 'app/quests/components/QuestCard.tsx',
                divergence:
                    'Uses neither Card primitive. Hand-built with border-2 border-black, a literal shadow-[4px_4px_0px_0px_rgba(0,0,0,1)] instead of shadow-4, and raw palette fills (bg-yellow-100, bg-pink-100, bg-blue-100) that map to no design token. Repeats the same recipe on three inner blocks.',
                verified: true,
            },
            {
                name: 'UserRankCard',
                realUsages: 3,
                status: 'adhoc',
                source: 'app/quests/components/UserRankCard.tsx',
                divergence:
                    'Same hand-built quests recipe as QuestCard — border-2 border-black, literal 4px shadow, bg-purple-200 / bg-pink-100 / bg-blue-100. No radius at all, so it is the one square card in the app.',
                verified: true,
            },
            {
                name: 'RoleCard',
                realUsages: 1,
                status: 'live',
                source: 'components/Jobs/RoleCard.tsx',
                divergence: 'New since the last sweep. Careers-page card on 0_Bruddle/Card.',
            },
            {
                name: 'CarouselCTA',
                realUsages: 2,
                devUsages: 1,
                status: 'live',
                source: 'components/Home/HomeCarouselCTA/CarouselCTA.tsx',
                divergence:
                    'New since the last sweep. Home carousel slide on 0_Bruddle/Card, paired with 0_Bruddle/CarouselDots.',
            },
            {
                name: 'InviteCardOG / PaymentCardOG / ProfileCardOG / ReceiptCardOG',
                realUsages: 4,
                status: 'variant',
                source: 'components/og/InviteCardOG.tsx',
                divergence:
                    "Four near-identical og:image cards. They render through satori, which supports no Tailwind, so each repeats the border and layout as an inline style object (border: '3px solid #000'). A shared OG card shell would collapse the four. Not a Card-primitive candidate — the constraint is real.",
                usedIn: [
                    'components/og/InviteCardOG.tsx',
                    'components/og/PaymentCardOG.tsx',
                    'components/og/ProfileCardOG.tsx',
                    'components/og/ReceiptCardOG.tsx',
                ],
                verified: true,
            },
            {
                name: 'CatalogCard',
                realUsages: 0,
                devUsages: 38,
                status: 'showcase-only',
                source: 'app/(mobile-ui)/dev/ds/_components/CatalogCard.tsx',
                divergence:
                    'Showcase navigation tile for /dev/ds. Two greps agree it never leaves /dev: `<CatalogCard` finds zero app renders, and a plain text grep for the name lists only the four /dev/ds index pages, the audit data files and its own definition. Correct as showcase-only, not dead.',
                verified: true,
            },
        ],
    },
]
