'use client'

import { useMemo, useState } from 'react'
import { DocPage } from '../_components/DocPage'
import { AUDIT_ITEMS, AUDIT_CLUSTERS, LAYER_STATS, type AuditStatus } from './audit-data'

const STATUS_META: Record<AuditStatus, { label: string; cls: string }> = {
    canonical: { label: 'canonical', cls: 'bg-green-1/40 text-n-1 border-n-1' },
    variant: { label: 'variant', cls: 'bg-secondary-6 text-n-1 border-n-1' },
    duplicate: { label: 'duplicate', cls: 'bg-error-1 text-n-1 border-n-1' },
    adhoc: { label: 'ad-hoc inline', cls: 'bg-yellow-1/50 text-n-1 border-n-1' },
    dead: { label: 'DEAD · never used', cls: 'bg-n-1/10 text-grey-1 border-grey-1' },
}
const STATUS_ORDER: AuditStatus[] = ['canonical', 'variant', 'duplicate', 'adhoc', 'dead']
const LAYERS = ['tokens', 'styles', 'primitives', 'components', 'patterns', 'templates']

function StatusChip({ status }: { status: AuditStatus }) {
    const m = STATUS_META[status]
    return (
        <span
            className={`inline-block whitespace-nowrap rounded-full border px-2 py-0.5 text-[10px] font-bold ${m.cls}`}
        >
            {m.label}
        </span>
    )
}

export default function DesignSystemAuditPage() {
    const [tab, setTab] = useState<'inventory' | 'clusters'>('inventory')
    const [layer, setLayer] = useState<string>('all')
    const [status, setStatus] = useState<string>('all')
    const [q, setQ] = useState('')

    const totals = useMemo(() => {
        const dead = AUDIT_ITEMS.filter((i) => i.status === 'dead').length
        return { items: AUDIT_ITEMS.length, dead, clusters: AUDIT_CLUSTERS.length }
    }, [])

    const items = useMemo(() => {
        const ql = q.trim().toLowerCase()
        return AUDIT_ITEMS.filter(
            (i) =>
                (layer === 'all' || i.layer === layer) &&
                (status === 'all' || i.status === status) &&
                (!ql ||
                    i.name.toLowerCase().includes(ql) ||
                    i.catLabel.toLowerCase().includes(ql) ||
                    i.notes.toLowerCase().includes(ql))
        ).sort((a, b) => b.usages - a.usages)
    }, [layer, status, q])

    const grouped = useMemo(() => {
        const g: Record<string, typeof items> = {}
        for (const i of items) (g[i.catLabel] ||= []).push(i)
        return Object.entries(g).sort((a, b) => b[1].length - a[1].length)
    }, [items])

    const clusters = useMemo(() => {
        const ql = q.trim().toLowerCase()
        return AUDIT_CLUSTERS.filter(
            (c) =>
                (layer === 'all' || c.layer === layer) &&
                (!ql ||
                    c.name.toLowerCase().includes(ql) ||
                    c.rec.toLowerCase().includes(ql) ||
                    c.collapses.join(' ').toLowerCase().includes(ql))
        ).sort((a, b) => b.from - a.from)
    }, [layer, q])

    return (
        <DocPage>
            {/* Hero */}
            <div className="rounded-sm border border-n-1 bg-purple-1 p-5">
                <p className="text-[11px] font-bold uppercase tracking-wide text-n-1/70">Design System · Code Audit</p>
                <h1 className="mt-1 text-h4">Code-level consolidation</h1>
                <p className="mt-2 text-sm font-bold text-n-1">
                    ~916 distinct <em>code</em> implementations → ~138 canonical (−85%). This is a DRY audit of the
                    codebase: every row is a distinct implementation with its grep call-site count. Merge the
                    duplicates.
                </p>
                <p className="mt-2 text-xs text-n-1/70">
                    Generated by the consolidation giga-sweep · full report in{' '}
                    <code className="rounded bg-n-1/10 px-1">inbox/ds-consolidation-audit/</code>
                </p>
            </div>

            {/* Scope caveat + cross-link to the app-usage audit */}
            <div className="rounded-sm border border-dashed border-n-1 bg-yellow-1/30 p-3 text-xs leading-snug text-n-1">
                <span className="font-bold">This is a CODE audit, not a design-system / app audit.</span> Counts here
                are raw call-sites across <code>src/</code> — they include the <code>/dev</code> showcase and tests, so
                a high count does <span className="font-bold">not</span> mean the live product renders it. For
                &ldquo;what the real app actually shows&rdquo; (and what&rsquo;s dead-in-product despite existing in
                code), see{' '}
                <a href="/dev/ds/audit/app" className="font-bold underline">
                    App Divergences →
                </a>
            </div>

            {/* Quick stats */}
            <div className="grid grid-cols-3 gap-2">
                {[
                    { label: 'inventoried', value: String(totals.items) },
                    { label: 'flagged dead', value: String(totals.dead) },
                    { label: 'merge clusters', value: String(totals.clusters) },
                ].map((s) => (
                    <div key={s.label} className="rounded-sm border border-n-1 p-3 text-center">
                        <p className="text-2xl font-bold">{s.value}</p>
                        <p className="text-[11px] text-grey-1">{s.label}</p>
                    </div>
                ))}
            </div>

            {/* Layer reduction table */}
            <div className="overflow-hidden rounded-sm border border-n-1">
                <table className="w-full text-left text-xs">
                    <thead className="bg-grey-3">
                        <tr>
                            <th className="px-3 py-2 font-bold">Layer</th>
                            <th className="px-3 py-2 text-right font-bold">Today</th>
                            <th className="px-3 py-2 text-right font-bold">Target</th>
                            <th className="px-3 py-2 text-right font-bold">Cut</th>
                        </tr>
                    </thead>
                    <tbody>
                        {LAYER_STATS.map((l) => (
                            <tr key={l.layer} className="border-t border-grey-2">
                                <td className="px-3 py-2 font-bold capitalize">{l.layer}</td>
                                <td className="px-3 py-2 text-right">{l.distinct}</td>
                                <td className="px-3 py-2 text-right">{l.target}</td>
                                <td className="px-3 py-2 text-right text-grey-1">
                                    −{Math.round((1 - l.target / l.distinct) * 100)}%
                                </td>
                            </tr>
                        ))}
                    </tbody>
                </table>
            </div>

            {/* Tabs */}
            <div className="flex gap-2">
                {(['inventory', 'clusters'] as const).map((t) => (
                    <button
                        key={t}
                        onClick={() => setTab(t)}
                        className={`flex-1 rounded-sm border border-n-1 px-3 py-2 text-sm font-bold capitalize ${
                            tab === t ? 'bg-n-1 text-white' : 'bg-white text-n-1'
                        }`}
                    >
                        {t === 'inventory' ? `Inventory (${items.length})` : `Clusters (${clusters.length})`}
                    </button>
                ))}
            </div>

            {/* Filters */}
            <div className="space-y-2">
                <input
                    value={q}
                    onChange={(e) => setQ(e.target.value)}
                    placeholder="Search name / notes…"
                    className="w-full rounded-sm border border-n-1 bg-white px-3 py-2 text-sm outline-none focus:border-primary-1"
                />
                <div className="flex flex-wrap gap-1">
                    {['all', ...LAYERS].map((l) => (
                        <button
                            key={l}
                            onClick={() => setLayer(l)}
                            className={`rounded-full border border-n-1 px-2.5 py-1 text-[11px] font-bold capitalize ${
                                layer === l ? 'bg-primary-1 text-n-1' : 'bg-white text-grey-1'
                            }`}
                        >
                            {l}
                        </button>
                    ))}
                </div>
                {tab === 'inventory' && (
                    <div className="flex flex-wrap gap-1">
                        {['all', ...STATUS_ORDER].map((s) => (
                            <button
                                key={s}
                                onClick={() => setStatus(s)}
                                className={`rounded-full border px-2.5 py-1 text-[11px] font-bold ${
                                    status === s ? 'border-n-1 bg-n-1 text-white' : 'border-grey-2 bg-white text-grey-1'
                                }`}
                            >
                                {s === 'all' ? 'all status' : STATUS_META[s as AuditStatus].label}
                            </button>
                        ))}
                    </div>
                )}
            </div>

            {/* Inventory */}
            {tab === 'inventory' &&
                grouped.map(([cat, list]) => (
                    <div key={cat}>
                        <div className="mb-2 flex items-center justify-between border-b border-n-1 pb-1">
                            <h2 className="text-sm font-bold">{cat}</h2>
                            <span className="text-[11px] text-grey-1">{list.length} impls</span>
                        </div>
                        <div className="space-y-2">
                            {list.map((i, idx) => (
                                <div
                                    key={cat + idx}
                                    className={`rounded-sm border p-3 ${
                                        i.status === 'dead'
                                            ? 'border-dashed border-grey-1 bg-grey-3/40'
                                            : 'border-grey-2 bg-white'
                                    }`}
                                >
                                    <div className="flex items-start justify-between gap-2">
                                        <p className="text-sm font-bold leading-tight">{i.name}</p>
                                        <span className="shrink-0 rounded-sm bg-n-1 px-2 py-0.5 text-xs font-bold text-white">
                                            {i.usages}×
                                        </span>
                                    </div>
                                    <div className="mt-1 flex flex-wrap items-center gap-1.5">
                                        <StatusChip status={i.status} />
                                        {i.role && <span className="text-[11px] text-grey-1">{i.role}</span>}
                                    </div>
                                    {i.notes && (
                                        <p className="mt-1.5 text-[11px] leading-snug text-grey-1">{i.notes}</p>
                                    )}
                                    {i.source && (
                                        <p className="mt-1 truncate font-mono text-[10px] text-grey-1/80">{i.source}</p>
                                    )}
                                </div>
                            ))}
                        </div>
                    </div>
                ))}

            {/* Clusters */}
            {tab === 'clusters' &&
                clusters.map((c, idx) => (
                    <div key={idx} className="rounded-sm border border-n-1 p-3">
                        <div className="flex items-start justify-between gap-2">
                            <p className="text-sm font-bold leading-tight">→ {c.name}</p>
                            {c.from > 0 && (
                                <span className="shrink-0 rounded-sm border border-n-1 bg-yellow-1/40 px-2 py-0.5 text-[11px] font-bold">
                                    {c.from} → 1
                                </span>
                            )}
                        </div>
                        <p className="mt-0.5 text-[11px] uppercase tracking-wide text-grey-1">{c.catLabel}</p>
                        {c.collapses.length > 0 && (
                            <p className="mt-1.5 text-[11px] text-grey-1">
                                <span className="font-bold text-n-1">collapses:</span> {c.collapses.join(' · ')}
                            </p>
                        )}
                        {c.rec && <p className="mt-1.5 text-xs leading-snug text-n-1">{c.rec}</p>}
                    </div>
                ))}

            <div className="rounded-sm border border-dashed border-grey-1 p-3 text-[11px] text-grey-1">
                Counts are call-site greps over <code>src/</code> (all usages, incl. some dev/test). “DEAD” = a delete-
                <em>candidate</em> to confirm, not an auto-delete — two items were re-classified live after manual
                re-grep. Full methodology + per-layer detail: <code>inbox/ds-consolidation-audit/</code>.
            </div>
        </DocPage>
    )
}
