export const PAYMENT_LOADING_WORDS = [
    'Cracking',
    'Smacking',
    'Smoothing',
    'Stacking',
    'Tallying',
    'Balancing',
    'Double-checking',
    'Triple-checking',
    'Wiring',
    'Shuffling',
    'Hustling',
    'Slinging',
    'Wandering',
    'Saying hola',
    'Dodging fees',
    'Outrunning your bank',
    'Skipping the line',
    'Cutting the line',
    'Ditching wires',
    'Bypassing borders',
    'Sneaking past',
    'Sidestepping',
    'Going around',
    'Outsmarting SWIFT',
    'Hunting rates',
    'Rate-hunting',
    'Negotiating',
    'Haggling',
    'Bartering',
    'Chasing the rate',
    'Beating your card!',
    'Cooking',
    'Marinating',
    'Yodeling',
] as const
