export { default as PEANUTMAN_BEER } from './peanut-holding-beer.svg'
export { default as PEANUTMAN_MANTLE } from './peanut-holding-mantle-logo.svg'
export { default as PEANUTMAN_MOBILE } from './peanut-holding-mobile.svg'
export { default as PEANUTMAN_CHEERING } from './peanutman-cheering.svg'
export { default as PEANUTMAN_HAPPY } from './peanutman-happy.svg'
export { default as PEANUTMAN_LOGO_BLACK } from './peanutman-logo-dark.svg'
export { default as PEANUTMAN_LOGO } from './peanutman-logo.svg'
export { default as PEANUTMAN_PRESENTING } from './peanutman-presenting.svg'
export { default as PEANUTMAN_REDPACKET } from './peanutman-redpacket.svg'
export { default as PEANUTMAN_SAD } from './peanutman-sad.svg'
export { default as PEANUTMAN_THINKING } from './peanutman-thinking.svg'
export { default as PEANUTMAN_WALLET } from './peanutman-wallets.svg'

