export { default as PEANUTMAN_BEER } from './peanut-holding-beer.svg'
export { default as PEANUTMAN_MOBILE } from './peanut-holding-mobile.svg'
export { default as PEANUTMAN_PFP } from './peanut-pfp.svg'
export { default as PEANUTMAN_RAISING_HANDS } from './peanut-raising-hands.svg'
export { default as PEANUTMAN_CHEERING } from './peanutman-cheering.svg'
export { default as PEANUTMAN_HAPPY } from './peanutman-happy.svg'
export { default as PEANUTMAN_LOGO } from './peanutman-logo.svg'
export { default as PEANUTMAN_PRESENTING } from './peanutman-presenting.svg'
export { default as PEANUTMAN_SAD } from './peanutman-sad.svg'

