"use client";
import providerOptions from "@/config/UAuth.config";
import { Web3ModalProvider } from "@/context/Web3ModalContext";
import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import * as UAuthWeb3Modal from "@uauth/web3modal";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
//Move this somewhere else

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3ModalProvider
          cacheProvider={true}
          providerOptions={providerOptions}
          onNewWeb3Modal={UAuthWeb3Modal.registerWeb3Modal}
        >
          {children}
        </Web3ModalProvider>
      </body>
    </html>
  );
}
