import { DepositMethod } from './components/DepositMethodList'

export const ALL_DEPOSIT_METHODS: DepositMethod[] = [
    {
        id: 'crypto',
        type: 'crypto',
        title: 'Crypto Deposit',
        description: 'Use an exchange or your wallet',
        path: '/add-money/crypto',
    },
    // South America
    {
        id: 'ar',
        type: 'country',
        title: 'Argentina',
        currency: 'ARS',
        iconUrl: 'https://flagcdn.com/w320/ar.png',
        path: '/add-money/argentina',
    },
    {
        id: 'bo',
        type: 'country',
        title: 'Bolivia',
        currency: 'BOB',
        iconUrl: 'https://flagcdn.com/w320/bo.png',
        path: '/add-money/bolivia',
    },
    {
        id: 'br',
        type: 'country',
        title: 'Brazil',
        currency: 'BRL',
        iconUrl: 'https://flagcdn.com/w320/br.png',
        path: '/add-money/brazil',
    },
    {
        id: 'cl',
        type: 'country',
        title: 'Chile',
        currency: 'CLP',
        iconUrl: 'https://flagcdn.com/w320/cl.png',
        path: '/add-money/chile',
    },
    {
        id: 'co',
        type: 'country',
        title: 'Colombia',
        currency: 'COP',
        iconUrl: 'https://flagcdn.com/w320/co.png',
        path: '/add-money/colombia',
    },
    {
        id: 'ec',
        type: 'country',
        title: 'Ecuador',
        currency: 'USD',
        iconUrl: 'https://flagcdn.com/w320/ec.png',
        path: '/add-money/ecuador',
    },
    {
        id: 'gy',
        type: 'country',
        title: 'Guyana',
        currency: 'GYD',
        iconUrl: 'https://flagcdn.com/w320/gy.png',
        path: '/add-money/guyana',
    },
    {
        id: 'py',
        type: 'country',
        title: 'Paraguay',
        currency: 'PYG',
        iconUrl: 'https://flagcdn.com/w320/py.png',
        path: '/add-money/paraguay',
    },
    {
        id: 'pe',
        type: 'country',
        title: 'Peru',
        currency: 'PEN',
        iconUrl: 'https://flagcdn.com/w320/pe.png',
        path: '/add-money/peru',
    },
    {
        id: 'sr',
        type: 'country',
        title: 'Suriname',
        currency: 'SRD',
        iconUrl: 'https://flagcdn.com/w320/sr.png',
        path: '/add-money/suriname',
    },
    {
        id: 'uy',
        type: 'country',
        title: 'Uruguay',
        currency: 'UYU',
        iconUrl: 'https://flagcdn.com/w320/uy.png',
        path: '/add-money/uruguay',
    },
    {
        id: 've',
        type: 'country',
        title: 'Venezuela',
        currency: 'VES',
        iconUrl: 'https://flagcdn.com/w320/ve.png',
        path: '/add-money/venezuela',
    },
    // North America
    {
        id: 'us',
        type: 'country',
        title: 'United States',
        currency: 'USD',
        iconUrl: 'https://flagcdn.com/w320/us.png',
        path: '/add-money/united-states',
    },
    // Europe
    {
        id: 'gb',
        type: 'country',
        title: 'United Kingdom',
        currency: 'GBP',
        iconUrl: 'https://flagcdn.com/w320/gb.png',
        path: '/add-money/united-kingdom',
    },
    {
        id: 'de',
        type: 'country',
        title: 'Germany',
        currency: 'EUR',
        iconUrl: 'https://flagcdn.com/w320/de.png',
        path: '/add-money/germany',
    },
    {
        id: 'fr',
        type: 'country',
        title: 'France',
        currency: 'EUR',
        iconUrl: 'https://flagcdn.com/w320/fr.png',
        path: '/add-money/france',
    },
    {
        id: 'it',
        type: 'country',
        title: 'Italy',
        currency: 'EUR',
        iconUrl: 'https://flagcdn.com/w320/it.png',
        path: '/add-money/italy',
    },
    {
        id: 'es',
        type: 'country',
        title: 'Spain',
        currency: 'EUR',
        iconUrl: 'https://flagcdn.com/w320/es.png',
        path: '/add-money/spain',
    },
    {
        id: 'pt',
        type: 'country',
        title: 'Portugal',
        currency: 'EUR',
        iconUrl: 'https://flagcdn.com/w320/pt.png',
        path: '/add-money/portugal',
    },
    {
        id: 'nl',
        type: 'country',
        title: 'Netherlands',
        currency: 'EUR',
        iconUrl: 'https://flagcdn.com/w320/nl.png',
        path: '/add-money/netherlands',
    },
    {
        id: 'be',
        type: 'country',
        title: 'Belgium',
        currency: 'EUR',
        iconUrl: 'https://flagcdn.com/w320/be.png',
        path: '/add-money/belgium',
    },
    {
        id: 'ch',
        type: 'country',
        title: 'Switzerland',
        currency: 'CHF',
        iconUrl: 'https://flagcdn.com/w320/ch.png',
        path: '/add-money/switzerland',
    },
    {
        id: 'at',
        type: 'country',
        title: 'Austria',
        currency: 'EUR',
        iconUrl: 'https://flagcdn.com/w320/at.png',
        path: '/add-money/austria',
    },
    {
        id: 'se',
        type: 'country',
        title: 'Sweden',
        currency: 'SEK',
        iconUrl: 'https://flagcdn.com/w320/se.png',
        path: '/add-money/sweden',
    },
    {
        id: 'no',
        type: 'country',
        title: 'Norway',
        currency: 'NOK',
        iconUrl: 'https://flagcdn.com/w320/no.png',
        path: '/add-money/norway',
    },
    {
        id: 'dk',
        type: 'country',
        title: 'Denmark',
        currency: 'DKK',
        iconUrl: 'https://flagcdn.com/w320/dk.png',
        path: '/add-money/denmark',
    },
    {
        id: 'fi',
        type: 'country',
        title: 'Finland',
        currency: 'EUR',
        iconUrl: 'https://flagcdn.com/w320/fi.png',
        path: '/add-money/finland',
    },
    {
        id: 'ie',
        type: 'country',
        title: 'Ireland',
        currency: 'EUR',
        iconUrl: 'https://flagcdn.com/w320/ie.png',
        path: '/add-money/ireland',
    },
    {
        id: 'pl',
        type: 'country',
        title: 'Poland',
        currency: 'PLN',
        iconUrl: 'https://flagcdn.com/w320/pl.png',
        path: '/add-money/poland',
    },
    {
        id: 'cz',
        type: 'country',
        title: 'Czech Republic',
        currency: 'CZK',
        iconUrl: 'https://flagcdn.com/w320/cz.png',
        path: '/add-money/czech-republic',
    },
]
