import {
  gnosis,
  mainnet,
  arbitrum,
  polygon,
  bsc,
  goerli,
  scrollTestnet,
  optimism,
  bscTestnet,
  optimismGoerli,
  polygonZkEvmTestnet,
  mantleTestnet,
  gnosisChiado,
  avalancheFuji,
  avalanche,
  celoAlfajores,
  polygonMumbai,
  filecoinCalibration,
  neonDevnet,
} from "@wagmi/chains";

export const chains = [
  mainnet,
  arbitrum,
  polygon,
  bsc,
  goerli,
  gnosis,
  scrollTestnet,
  optimism,
  bscTestnet,
  optimismGoerli,
  polygonZkEvmTestnet,
  mantleTestnet,
  gnosisChiado,
  avalancheFuji,
  avalanche,
  celoAlfajores,
  polygonMumbai,
  filecoinCalibration,
  neonDevnet,
];

//have a look to make this more modular
