export { default as COINBASE_LOGO } from './coinbase.svg'
export { default as METAMASK_LOGO } from './metamask.svg'
export { default as RAINBOW_LOGO } from './rainbow.svg'
export { default as TRUST_WALLET_LOGO } from './trust_wallet.svg'
export { default as TRUST_WALLET_SMALL_LOGO } from './trust_wallet_2.svg'
