import type { AppLocale } from './config'
import type { AppMessages, DeepPartial } from './messages'
import { deepMerge } from './messages'
import en from './messages/en.marketing.json'

/*
 * Marketing-site catalogs: the handful of namespaces the landing page and the
 * localized marketing pages actually use, generated by
 * scripts/generate-marketing-messages.js. Typed as a partial app catalog —
 * `useTranslations` for a namespace outside the subset would be a missing
 * message, which is why the generator's namespace list is asserted in a test.
 */
export const marketingBase = en as unknown as AppMessages

export async function loadMarketingMessages(locale: AppLocale): Promise<AppMessages> {
    const merge = (override: unknown) => deepMerge(marketingBase, override as DeepPartial<AppMessages>)
    switch (locale) {
        case 'en':
            return marketingBase
        case 'es-419':
            return merge((await import('./messages/es-419.marketing.json')).default)
        // es-AR is deltas-only over es-419, same as the full catalog
        case 'es-AR': {
            const es419 = (await import('./messages/es-419.marketing.json')).default
            const esAR = (await import('./messages/es-AR.marketing.json')).default
            return deepMerge(merge(es419), esAR as DeepPartial<AppMessages>)
        }
        case 'pt-BR':
            return merge((await import('./messages/pt-BR.marketing.json')).default)
    }
}
