export { default as DEREK_PERSON } from './derek.png'
export { default as HUGO_PERSON } from './hugo0-no-bg.png'
export { default as KONRAD_PERSON } from './kkonrad-no-bg.png'
export { default as MYDAS_PERSON } from './mydas.jpg'
export { default as OREST_PERSON } from './orest.jpg'
export { default as SHARUK_PERSON } from './sharuk.png'
export { default as SBF_PERSON } from './sbf.jpeg'
export { default as KOFIME_PERSON } from './kofime-icon.jpeg'
