export const SETUP = 'setup'
export const WALLET_SLICE = 'wallet_slice'
export const ZERODEV_SLICE = 'zerodev_slice'
export const AUTH_SLICE = 'auth_slice'
export const BANK_FORM_SLICE = 'bank_form_slice'
