#!/usr/bin/env tsx
/**
 * Generates input/context/valid-links.md for the content submodule.
 * This file is loaded by LLMs during content generation so they know
 * exactly which internal URLs exist.
 *
 * Run: pnpm script scripts/generate-valid-links.ts
 * Run after adding new pages/countries/corridors/etc.
 */

import fs from 'fs'
import path from 'path'

const ROOT = path.join(process.cwd(), 'src/content')
const CONTENT_DIR = path.join(ROOT, 'content')
const OUTPUT = path.join(ROOT, 'input/context/valid-links.md')

const LOCALES = ['en', 'es-419', 'es-ar', 'es-es', 'pt-br']

function listDirs(dir: string): string[] {
    if (!fs.existsSync(dir)) return []
    return fs
        .readdirSync(dir, { withFileTypes: true })
        .filter((d) => d.isDirectory())
        .map((d) => d.name)
        .sort()
}

function main() {
    const countrySlugs = listDirs(path.join(CONTENT_DIR, 'countries'))
    const competitorSlugs = listDirs(path.join(CONTENT_DIR, 'compare'))
    const payWithSlugs = listDirs(path.join(CONTENT_DIR, 'pay-with'))
    const depositSlugs = listDirs(path.join(CONTENT_DIR, 'deposit'))
    const helpSlugs = listDirs(path.join(CONTENT_DIR, 'help'))
    const useCaseSlugs = listDirs(path.join(CONTENT_DIR, 'use-cases'))
    const withdrawSlugs = listDirs(path.join(CONTENT_DIR, 'withdraw'))

    // Build corridors from file structure
    const corridors: Array<{ to: string; from: string }> = []
    for (const dest of listDirs(path.join(CONTENT_DIR, 'send-to'))) {
        const fromDir = path.join(CONTENT_DIR, 'send-to', dest, 'from')
        for (const origin of listDirs(fromDir)) {
            corridors.push({ to: dest, from: origin })
        }
    }
    const receiveSources = [...new Set(corridors.map((c) => c.from))].sort()

    const lines: string[] = []
    lines.push('# Valid Internal Links')
    lines.push('')
    lines.push('> Auto-generated by `scripts/generate-valid-links.ts`. Do not edit manually.')
    lines.push('> Regenerate after adding new pages: `pnpm script scripts/generate-valid-links.ts`')
    lines.push('')
    lines.push(
        'When writing content, **only link to URLs listed below**. Replace `{locale}` with the target locale (`en`, `es-419`, `es-ar`, `es-es`, `pt-br`).'
    )
    lines.push('')

    // Static pages
    lines.push('## Static Pages')
    lines.push('')
    for (const p of ['/', '/careers', '/exchange', '/privacy', '/terms', '/lp/card']) {
        lines.push(`- \`${p}\``)
    }
    lines.push('')

    // Pricing
    lines.push('## Pricing')
    lines.push('')
    lines.push('- `/{locale}/pricing`')
    lines.push('')

    // Help
    lines.push('## Help Pages')
    lines.push('')
    lines.push('- `/{locale}/help`')
    for (const slug of helpSlugs) {
        lines.push(`- \`/{locale}/help/${slug}\``)
    }
    lines.push('')

    // Country hubs
    lines.push('## Country Hub Pages')
    lines.push('')
    lines.push('Pattern: `/{locale}/{country}`')
    lines.push('')
    for (const slug of countrySlugs) {
        lines.push(`- \`/{locale}/${slug}\``)
    }
    lines.push('')

    // Send money to
    lines.push('## Send Money To Pages')
    lines.push('')
    lines.push('Pattern: `/{locale}/send-money-to/{country}`')
    lines.push('')
    for (const slug of countrySlugs) {
        lines.push(`- \`/{locale}/send-money-to/${slug}\``)
    }
    lines.push('')

    // Corridors
    lines.push('## Corridor Pages (Send Money From)')
    lines.push('')
    lines.push('Pattern: `/{locale}/send-money-from/{origin}/to/{destination}`')
    lines.push('')
    for (const c of corridors) {
        lines.push(`- \`/{locale}/send-money-from/${c.from}/to/${c.to}\``)
    }
    lines.push('')

    // Receive money
    lines.push('## Receive Money Pages')
    lines.push('')
    lines.push('Pattern: `/{locale}/receive-money-from/{source}`')
    lines.push('')
    for (const source of receiveSources) {
        lines.push(`- \`/{locale}/receive-money-from/${source}\``)
    }
    lines.push('')

    // Compare
    lines.push('## Comparison Pages')
    lines.push('')
    lines.push('Pattern: `/{locale}/compare/peanut-vs-{competitor}`')
    lines.push('')
    for (const slug of competitorSlugs) {
        lines.push(`- \`/{locale}/compare/peanut-vs-${slug}\``)
    }
    lines.push('')

    // Pay-with
    lines.push('## Pay With Pages')
    lines.push('')
    lines.push('Pattern: `/{locale}/pay-with/{method}`')
    lines.push('')
    for (const slug of payWithSlugs) {
        lines.push(`- \`/{locale}/pay-with/${slug}\``)
    }
    lines.push('')

    // Deposit
    lines.push('## Deposit Pages')
    lines.push('')
    lines.push('Pattern: `/{locale}/deposit/from-{source}`')
    lines.push('')
    for (const slug of depositSlugs) {
        lines.push(`- \`/{locale}/deposit/from-${slug}\``)
    }
    lines.push('')

    // Withdraw
    lines.push('## Withdraw Pages')
    lines.push('')
    lines.push('Pattern: `/{locale}/withdraw/to-{destination}`')
    lines.push('')
    for (const slug of withdrawSlugs) {
        lines.push(`- \`/{locale}/withdraw/to-${slug}\``)
    }
    lines.push('')

    // Use cases
    lines.push('## Use Case Pages')
    lines.push('')
    lines.push('Pattern: `/{locale}/use-cases/{slug}`')
    lines.push('')
    for (const slug of useCaseSlugs) {
        lines.push(`- \`/{locale}/use-cases/${slug}\``)
    }
    lines.push('')

    fs.mkdirSync(path.dirname(OUTPUT), { recursive: true })
    fs.writeFileSync(OUTPUT, lines.join('\n'))
    console.log(`Generated ${OUTPUT} with valid links for:`)
    console.log(`  ${countrySlugs.length} countries`)
    console.log(`  ${corridors.length} corridors`)
    console.log(`  ${competitorSlugs.length} competitors`)
    console.log(`  ${payWithSlugs.length} payment methods`)
    console.log(`  ${depositSlugs.length} deposit sources`)
    console.log(`  ${withdrawSlugs.length} withdraw destinations`)
    console.log(`  ${helpSlugs.length} help articles`)
    console.log(`  ${useCaseSlugs.length} use cases`)
}

main()
