/**
 * Profile avatars (TASK-22142). The catalog is the API's badge manifest
 * (`badge-assets.json`, regenerated by `pnpm badge:check --write-manifest`
 * in peanut-api-ts — never hand-edited): `avatars.basics` is the set every
 * user gets, `avatars.badges[CODE]` the slugs holding that badge unlocks.
 *
 * Keys are `basic.<slug>` and `badge.<CODE>.<slug>`; the API validates a
 * pick against the same pool, so this file never decides who may wear what —
 * it only mirrors the manifest into paths and palettes.
 */
import badgeAssets from '@/types/badge-assets.json'

const BASICS: readonly string[] = badgeAssets.avatars.basics
const BADGE_AVATARS: Readonly<Record<string, readonly string[]>> = badgeAssets.avatars.badges

export const basicAvatarKeys = (): string[] => BASICS.map((slug) => `basic.${slug}`)

/** Avatar keys unlocked by holding these badge codes, in badge order. */
export const badgeAvatarKeys = (heldCodes: readonly string[]): string[] =>
    heldCodes.flatMap((code) => (BADGE_AVATARS[code] ?? []).map((slug) => `badge.${code}.${slug}`))

/** Everything the user may pick: the basics plus what their badges unlock. */
export const avatarPool = (heldCodes: readonly string[]): string[] => [
    ...basicAvatarKeys(),
    ...badgeAvatarKeys(heldCodes),
]

/** Public path of the avatar art, or null for a key the manifest does not know. */
export function avatarSrc(key: string | null | undefined): string | null {
    if (!key) return null
    const [kind, ...rest] = key.split('.')
    if (kind === 'basic' && rest.length === 1 && BASICS.includes(rest[0])) return `/avatars/basic/${rest[0]}.svg`
    if (kind === 'badge' && rest.length === 2 && BADGE_AVATARS[rest[0]]?.includes(rest[1])) {
        return `/avatars/badge/${rest[0]}/${rest[1]}.svg`
    }
    return null
}

// the seven avatar triples (board 17802:61529) as full class literals so the
// tailwind scanner emits them; fill and border travel together
const PALETTE_CLASSES = [
    'bg-avatar-pink border-avatar-pink-border',
    'bg-avatar-yellow border-avatar-yellow-border',
    'bg-avatar-purple border-avatar-purple-border',
    'bg-avatar-blue border-avatar-blue-border',
    'bg-avatar-red border-avatar-red-border',
    'bg-avatar-orange border-avatar-orange-border',
    'bg-avatar-green border-avatar-green-border',
] as const

/** Fill + border classes of one avatar triple, stable per key. */
export function avatarPaletteClass(key: string): string {
    let hash = 5381
    for (let i = 0; i < key.length; i++) hash = ((hash << 5) + hash + key.charCodeAt(i)) >>> 0
    return PALETTE_CLASSES[hash % PALETTE_CLASSES.length]
}
