/**
 * Profile avatars (TASK-22142). The catalog is the API's badge manifest,
 * `badge-assets.json`, regenerated by `pnpm badge:check --write-manifest`
 * in peanut-api-ts and never hand-edited. `avatars.basics` is the set every
 * user gets; `avatars.badges[CODE]` lists the slugs holding that badge unlocks.
 *
 * Keys are `basic.<slug>` and `badge.<CODE>.<slug>`. The API validates a
 * pick against the same pool. This file only mirrors the manifest into
 * paths and palettes; it never decides who may wear what.
 */
import badgeAssets from '@/types/badge-assets.json'

const BASICS: readonly string[] = badgeAssets.avatars.basics
const BADGE_AVATARS: Readonly<Record<string, readonly string[]>> = badgeAssets.avatars.badges

// plain JSON object: a code like `constructor` must read as "no avatars", not
// as Object.prototype
const slugsOf = (code: string): readonly string[] => (Object.hasOwn(BADGE_AVATARS, code) ? BADGE_AVATARS[code] : [])

export const basicAvatarKeys = (): string[] => BASICS.map((slug) => `basic.${slug}`)

/** Avatar keys unlocked by holding these badge codes, in badge order. */
export const badgeAvatarKeys = (heldCodes: readonly string[]): string[] =>
    heldCodes.flatMap((code) => slugsOf(code).map((slug) => `badge.${code}.${slug}`))

/** Everything the user may pick: the basics plus what their badges unlock. */
export const avatarPool = (heldCodes: readonly string[]): string[] => [
    ...basicAvatarKeys(),
    ...badgeAvatarKeys(heldCodes),
]

/**
 * The basics row the picker offers: the current pick if it is a basic, then
 * random basics to fill `n`. The dice rerolls this row and never the pick
 * (Split's semantics: the dice changes what is offered, not who you are).
 */
export function offerBasics(pick: string | null, n = 5, random: () => number = Math.random): string[] {
    const basics = basicAvatarKeys()
    const keep = pick && basics.includes(pick) ? [pick] : []
    const rest = basics.filter((key) => key !== pick)
    for (let i = rest.length - 1; i > 0; i--) {
        const j = Math.floor(random() * (i + 1))
        ;[rest[i], rest[j]] = [rest[j], rest[i]]
    }
    return [...keep, ...rest].slice(0, n)
}

/** Public path of the avatar art, or null for a key the manifest does not know. */
export function avatarSrc(key: string | null | undefined): string | null {
    if (!key) return null
    const [kind, ...rest] = key.split('.')
    if (kind === 'basic' && rest.length === 1 && BASICS.includes(rest[0])) return `/avatars/basic/${rest[0]}.svg`
    if (kind === 'badge' && rest.length === 2 && slugsOf(rest[0]).includes(rest[1])) {
        return `/avatars/badge/${rest[0]}/${rest[1]}.svg`
    }
    return null
}

// the seven avatar triples (board 17802:61529) as full class literals so the
// tailwind scanner emits them; fill and border travel together
const PALETTE_CLASSES = [
    'bg-avatar-pink border-avatar-pink-border',
    'bg-avatar-yellow border-avatar-yellow-border',
    'bg-avatar-purple border-avatar-purple-border',
    'bg-avatar-blue border-avatar-blue-border',
    'bg-avatar-red border-avatar-red-border',
    'bg-avatar-orange border-avatar-orange-border',
    'bg-avatar-green border-avatar-green-border',
] as const

/** Fill + border classes of one avatar triple, stable per key. */
export function avatarPaletteClass(key: string): string {
    let hash = 5381
    for (let i = 0; i < key.length; i++) hash = ((hash << 5) + hash + key.charCodeAt(i)) >>> 0
    return PALETTE_CLASSES[hash % PALETTE_CLASSES.length]
}
