export const MAX_TRANSACTIONS_PER_BLOCK = 250

export const MANTLE_CHAIN_ID = '5000'

export const MANTLE_TESTNET_CHAIN_ID = '5001'

export const MANTLE_NATIVE_TOKEN_ADDRESS = '0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000'
