import type { UsageCategory } from '../../_components/UsageAudit'

// AUTO-GENERATED by the DS audit inventory sweep (2026-08-25). Do not hand-edit.
// Source: peanut-ui feat/design-system @ 843df91b — swept at 7ae13804 by 10 parallel finders,
// one per DS category, then a mechanical re-count of every row (the adversarial pass).
// Refreshed to 843df91b (the phase-2 styling cleanup, 16 commits, 236 product files) by a delta
// pass: one probe per row over the 7ae13804 corpus and the 843df91b corpus, with the difference
// added to the swept number. A delta is method-independent, so it carries a row forward without
// having to re-derive that row's original bespoke grep. 93 rows moved; the rest are unchanged.
// 165 rows carry a prose or glob key ("inline recipe: text-sm + font-bold", "--color-avatar-*")
// that no single probe reproduces — those numbers still date from 7ae13804.
// Not re-inventoried: PageStack (64), Section (23), ListGroup (9), TitleBlock (1) and
// ActiveCardGate (3) are new primitives from this base and have no row yet.
// Replaces the 2026-06-26 giga-sweep. That method is recoverable from mono commit f9346907,
// file inbox/ds-consolidation-audit/README.md (the folder itself was deleted 2026-08-06).
// Method: usages = call sites over src/**/*.{ts,tsx,css}, minus /dev routes, __tests__ and
// *.test.* — the live-product lens the 2026-06 pass used. A component row counts JSX call sites
// with the ERE `<Name([^A-Za-z]|$)`. The `|$` is load-bearing: Prettier writes multi-line
// `<Name\n  prop=…`, and the 2026-06 sweep missed that form and called three live components dead.
// A token or CSS-class row counts word-bounded occurrences of its key. Every number here was
// machine-measured from the row's own grep and re-measured a second time at assembly, so no count
// is hand-typed.
// devUsages = the same grep counted over /dev routes only, so a row shows the gap between what the
// showcase renders and what the product renders.
export const APP_DIVERGENCE_CATEGORIES: UsageCategory[] = [
    {
        category: 'Primitives & Backgrounds',
        layer: 'primitives',
        summary:
            'src/components/0_Bruddle/ has grown from 10 files to 21. Ten primitives are new since the June sweep (LinkButton, Accordion, ProgressBar, SegmentedControl, CarouselDots, Notification, SlideToConfirm, Toggle, ListItem, IconBubble, plus the split-out ToastStack) and three of them are already among the most-rendered components in the product: Notification (99 call-sites, imported by 60 product files), ListItem (38) and LinkButton (20). No 0_Bruddle barrel exists, so imports cannot hide. Counts are grep occurrences in src/**/*.{ts,tsx,css}; realUsages excludes /dev routes, __tests__ and *.test.*, devUsages is the remainder. Two June findings survive re-testing unchanged: Title still has exactly ONE product consumer (MarketingHero) against 8 /dev references, so it is still a Marketing-only decorative primitive parked in the shared DS; and the bg-peanut-repeat-* backgrounds still render on ZERO product screens — the only non-/dev matches are the class definitions in globals.css and the twMerge group config in utils/tw.ts. public/bg.svg is still orphaned. New this round: CloudsBackground dropped to 2 call-sites and both still pass `minimal`, so the full cloud config remains a dead branch; Accordion has 24 /dev references against a single product consumer (BridgeLimitsView), which makes it the most showcase-heavy of the new primitives.',
        items: [
            {
                name: 'Button (0_Bruddle/Button)',
                realUsages: 215,
                devUsages: 76,
                status: 'canonical',
                source: 'src/components/0_Bruddle/Button.tsx',
                divergence:
                    "Still the workhorse — 216 product call-sites, up from 134 in June. Restyled to the figma button board (17802:61527): pill shape via rounded-round, sizes l=48 / m=44 (default) / s=40, blue focus ring, disabled = 40% opacity. The June 'large is shorter than default' trap is FIXED — btn-large is now h-12 (48px) against .btn's h-11 (44px). One real defect remains inside the primitive: the long-press progress bar at Button.tsx:198 uses `from-purple-400 to-purple-600`, and the v4 @theme disables the stock purple scale, so that gradient renders transparent.",
                usedIn: [
                    'app/(setup)/setup/page.tsx',
                    'app/app/page.tsx',
                    'app/quests/[questId]/page.tsx',
                    'app/[...recipient]/error.tsx',
                    'app/quests/explore/page.tsx',
                ],
                verified: true,
            },
            {
                name: 'Notification (0_Bruddle/Notification) — NEW',
                realUsages: 99,
                devUsages: 26,
                status: 'canonical',
                source: 'src/components/0_Bruddle/Notification.tsx',
                divergence:
                    'New since June and already the second most-rendered primitive: 99 product call-sites across 60 importing product files. It absorbed the deleted ErrorAlert / InfoCard / MessageContainer-style inline banners. Colors come from the semantic --color-background-badge-* tokens, so it is one of the few primitives fully on the new token layer.',
                usedIn: [
                    'app/recover-wallet/page.tsx',
                    'app/(mobile-ui)/recover-funds/page.tsx',
                    'app/(mobile-ui)/qr-pay/page.tsx',
                    'app/(mobile-ui)/qr/[code]/page.tsx',
                    'app/(mobile-ui)/add-money/[country]/bank/page.tsx',
                ],
                verified: true,
            },
            {
                name: 'PageContainer (0_Bruddle/PageContainer)',
                realUsages: 36,
                devUsages: 1,
                status: 'canonical',
                source: 'src/components/0_Bruddle/PageContainer.tsx',
                divergence:
                    'Canonical page shell, up from 30 to 42 product call-sites (mostly route page.tsx / layout.tsx). Almost invisible in /dev (1 reference) — the opposite profile to Title or Accordion: a primitive the product uses and the showcase ignores.',
                usedIn: [
                    'app/[...recipient]/page.tsx',
                    'app/recover-wallet/layout.tsx',
                    'app/(mobile-ui)/settings/language/page.tsx',
                    'app/(mobile-ui)/card/pin/page.tsx',
                    'app/(mobile-ui)/recover-funds/layout.tsx',
                ],
            },
            {
                name: 'ListItem (0_Bruddle/ListItem) — NEW',
                realUsages: 38,
                devUsages: 20,
                status: 'canonical',
                source: 'src/components/0_Bruddle/ListItem.tsx',
                divergence:
                    'New primitive, 38 product call-sites across 25 files. It is the row primitive the old Global/Card stacked-list variant used to cover, but Global/Card is still imported by 44 product files — so the two row idioms now coexist and the migration is roughly half done.',
                usedIn: [
                    'app/(mobile-ui)/profile/backup/page.tsx',
                    'features/home/components/HomeActionDrawers.tsx',
                    'features/payments/shared/components/PaymentMethodActionList.tsx',
                    'features/limits/views/LimitsPageView.tsx',
                ],
            },
            {
                name: 'Card (0_Bruddle/Card)',
                realUsages: 21,
                devUsages: 12,
                status: 'variant',
                source: 'src/components/0_Bruddle/Card.tsx',
                divergence:
                    'Counted as importing product files (21), because a bare `<Card` grep cannot separate this from Global/Card — and that is exactly the divergence. Two different components named Card still ship: 0_Bruddle/Card (named export, standalone container) in 21 product files, Global/Card (default export, stacked list item) in 44. The naming collision the June audit flagged is unresolved, and the new ListItem primitive now overlaps the Global/Card job as well.',
                usedIn: [
                    'app/[locale]/(marketing)/press/page.tsx',
                    'app/(mobile-ui)/withdraw/manteca/page.tsx',
                    'app/(mobile-ui)/card-recovery/page.tsx',
                    'components/Home/HomeCarouselCTA/CarouselCTA.tsx',
                    'components/Setup/Views/Landing.tsx',
                ],
                verified: true,
            },
            {
                name: 'useToast (0_Bruddle/Toast hook)',
                realUsages: 22,
                devUsages: 1,
                status: 'live',
                source: 'src/components/0_Bruddle/Toast.tsx',
                divergence:
                    'The consumed surface of the Toast file is still the hook, not a component — 22 product call-sites vs 1 for ToastProvider and 0 for any exported Toast element.',
                usedIn: [
                    'context/authContext.tsx',
                    'context/RainCooldownContext.tsx',
                    'components/Card/YourCardScreen.tsx',
                    'components/Settings/DeleteAccountButton.tsx',
                    'app/(mobile-ui)/qr/[code]/success/page.tsx',
                ],
            },
            {
                name: 'LinkButton (0_Bruddle/LinkButton) — NEW',
                realUsages: 20,
                devUsages: 11,
                status: 'canonical',
                source: 'src/components/0_Bruddle/LinkButton.tsx',
                divergence:
                    'New anchor-shaped sibling of Button, 20 product call-sites in 17 files. It is the sanctioned answer to the ad-hoc <a className="btn ..."> pattern the June audit found; those hand-rolled anchors are gone.',
                usedIn: [
                    'app/[...recipient]/error.tsx',
                    'app/recover-wallet/page.tsx',
                    'app/maintenance/page.tsx',
                    'app/(mobile-ui)/card-recovery/page.tsx',
                    'components/Card/ApplicationStatusScreen.tsx',
                ],
            },
            {
                name: 'IconBubble (0_Bruddle/IconBubble) — NEW',
                realUsages: 17,
                devUsages: 21,
                status: 'canonical',
                source: 'src/components/0_Bruddle/IconBubble.tsx',
                divergence:
                    'New primitive, 17 product call-sites in 11 files — but as many references again live in /dev. It is backed by the semantic --color-background-icon-bubble-* tokens (20 product call-sites for that token group), so adopting IconBubble is what makes those tokens live at all.',
                usedIn: [
                    'app/(mobile-ui)/withdraw/manteca/page.tsx',
                    'components/AddWithdraw/AddWithdrawRouterView.tsx',
                    'components/Common/SavedAccountsView.tsx',
                    'components/Send/views/SendRouter.view.tsx',
                ],
            },
            {
                name: 'BaseInput (0_Bruddle/BaseInput)',
                realUsages: 10,
                devUsages: 15,
                status: 'live',
                source: 'src/components/0_Bruddle/BaseInput.tsx + src/styles/globals.css:1010 (.input)',
                divergence:
                    "Still a thin wrapper over the .input component class, now re-sourced to globals.css:1010 (tailwind.config.js is gone). The class was restyled to the input board (17802:61538): border-border-subtle at rest, border-default on focus, blue focus ring, aria-invalid red. The June note that variant sizes duplicate the class's own h-16 still holds. More references in /dev (14) than in the product (10).",
                usedIn: [
                    'components/AddWithdraw/DynamicBankAccountForm.tsx',
                    'components/SearchInput/index.tsx',
                    'components/Profile/components/ProfileEditField.tsx',
                    'components/Invites/JoinWaitlistPage.tsx',
                    'components/LandingPage/CurrencySelect.tsx',
                ],
            },
            {
                name: 'Divider (0_Bruddle/Divider)',
                realUsages: 9,
                devUsages: 6,
                status: 'live',
                source: 'src/components/0_Bruddle/Divider.tsx',
                divergence:
                    'Live, roughly flat since June (7 → 9). Still hard-codes its own line thickness and color with no thickness/color prop; callers override only through the dividerClassname twMerge.',
                usedIn: [
                    'features/payments/shared/components/PaymentMethodActionList.tsx',
                    'components/Send/views/SendRouter.view.tsx',
                    'components/Global/TokenSelector/TokenSelector.tsx',
                    'components/Common/SavedAccountsView.tsx',
                    'components/Setup/Views/JoinWaitlist.tsx',
                ],
            },
            {
                name: 'SlideToConfirm (0_Bruddle/SlideToConfirm) — NEW',
                realUsages: 7,
                status: 'canonical',
                source: 'src/components/0_Bruddle/SlideToConfirm.tsx',
                divergence:
                    'New confirmation primitive with a healthy product-first profile: 7 product call-sites, 1 in /dev. Used on the destructive/irreversible paths (card lock, card cancel, crypto withdraw, onramp confirm).',
                usedIn: [
                    'app/(mobile-ui)/withdraw/crypto/page.tsx',
                    'components/Card/LockCardModal.tsx',
                    'components/Card/CancelCardModal.tsx',
                    'components/AddMoney/components/OnrampConfirmationModal.tsx',
                    'components/Global/TokenAndNetworkConfirmationModal/index.tsx',
                ],
            },
            {
                name: 'Checkbox (0_Bruddle/Checkbox)',
                realUsages: 4,
                devUsages: 6,
                status: 'live',
                source: 'src/components/0_Bruddle/Checkbox.tsx',
                divergence:
                    'Unchanged at 4 product call-sites, still concentrated in the Card flows, and now outnumbered by its /dev references (7).',
                usedIn: [
                    'components/Card/CardTermsScreen.tsx',
                    'components/Card/CardUnlockDrawer.tsx',
                    'components/Card/BadgeSkipCelebration.tsx',
                    'components/Global/QRScannerOverlay/index.tsx',
                ],
            },
            {
                name: 'Accordion (0_Bruddle/Accordion) — NEW',
                realUsages: 4,
                devUsages: 17,
                status: 'canonical',
                source: 'src/components/0_Bruddle/Accordion.tsx',
                divergence:
                    'The most showcase-heavy of the new primitives: 4 product call-sites, ALL inside one file (features/limits/views/BridgeLimitsView.tsx), against 24 references in /dev. Built and documented, but the product has adopted it on exactly one screen so far.',
                usedIn: ['features/limits/views/BridgeLimitsView.tsx'],
                verified: true,
            },
            {
                name: 'BaseSelect (0_Bruddle/BaseSelect)',
                realUsages: 3,
                devUsages: 6,
                status: 'live',
                source: 'src/components/0_Bruddle/BaseSelect.tsx',
                divergence:
                    'Was 1 product call-site in June, now 3 across 2 files — still barely-live, and still the only select primitive after Global/Select was deleted, so it now carries that job with almost no coverage.',
                usedIn: [
                    'app/(mobile-ui)/withdraw/manteca/page.tsx',
                    'components/AddWithdraw/DynamicBankAccountForm.tsx',
                ],
            },
            {
                name: 'ProgressBar (0_Bruddle/ProgressBar) — NEW',
                realUsages: 2,
                status: 'canonical',
                source: 'src/components/0_Bruddle/ProgressBar.tsx',
                divergence:
                    'Replaces the deleted Global/ProgressBar and LimitsProgressBar. Two product call-sites so far (MantecaLimitsView, PotProgress) — the consolidation landed, the adoption is thin.',
                usedIn: ['features/limits/views/MantecaLimitsView.tsx', 'components/User/PotProgress.tsx'],
            },
            {
                name: 'SegmentedControl (0_Bruddle/SegmentedControl) — NEW',
                realUsages: 2,
                status: 'canonical',
                source: 'src/components/0_Bruddle/SegmentedControl.tsx',
                divergence:
                    'New tab/toggle-group primitive, 2 product call-sites (MantecaLimitsView, RhinoDeposit). Low usage but product-first.',
                usedIn: [
                    'features/limits/views/MantecaLimitsView.tsx',
                    'components/AddMoney/views/RhinoDeposit.view.tsx',
                ],
            },
            {
                name: 'CarouselDots (0_Bruddle/CarouselDots) — NEW',
                realUsages: 2,
                status: 'canonical',
                source: 'src/components/0_Bruddle/CarouselDots.tsx',
                divergence:
                    'New pagination-dot primitive, 2 product call-sites and ZERO /dev references — the reverse of the usual gap: shipped in the product but absent from the showcase, so a designer browsing /dev will not know it exists.',
                usedIn: ['components/Card/AddToWalletCarousel.tsx', 'components/Global/Carousel/index.tsx'],
                verified: true,
            },
            {
                name: 'CloudsBackground (0_Bruddle/CloudsBackground)',
                realUsages: 2,
                status: 'live',
                source: 'src/components/0_Bruddle/CloudsBackground.tsx',
                divergence:
                    'Down from 3 to 2 product call-sites (StartVerificationView stopped using it), and both remaining callers still pass `minimal` — the full desktopClouds/mobileClouds config in the file is still a branch the product never renders.',
                usedIn: ['components/Setup/components/SetupWrapper.tsx', 'components/Invites/InvitesPageLayout.tsx'],
                verified: true,
            },
            {
                name: 'Toggle (0_Bruddle/Toggle) — NEW',
                realUsages: 1,
                devUsages: 6,
                status: 'canonical',
                source: 'src/components/0_Bruddle/Toggle.tsx',
                divergence:
                    "New switch primitive with exactly ONE product consumer (ShowNameToggle) against 5 /dev references — the new-primitive equivalent of Title's profile. Delete-candidate only if no further settings surfaces adopt it.",
                usedIn: ['components/Profile/components/ShowNameToggle.tsx'],
                verified: true,
            },
            {
                name: 'Title (0_Bruddle/Title)',
                realUsages: 1,
                devUsages: 8,
                status: 'live',
                source: 'src/components/0_Bruddle/Title.tsx',
                divergence:
                    "RE-TESTED, VERDICT UNCHANGED. The 'about 4 importing files' figure is a /dev artefact: of the 4 files that import it, 3 are showcase pages (dev/ds/page, dev/ds/foundations/typography, dev/ds/primitives/title) and only MarketingHero.tsx is product. One product call-site, 8 /dev references. Still a Marketing-only decorative title (font-knerd-filled + offset outline layer) parked in the shared DS — belongs in components/Marketing/.",
                usedIn: ['components/Marketing/MarketingHero.tsx'],
                verified: true,
            },
            {
                name: 'ToastProvider / ToastStack (0_Bruddle/Toast)',
                realUsages: 1,
                status: 'live',
                source: 'src/components/0_Bruddle/Toast.tsx + src/components/0_Bruddle/ToastStack.tsx',
                divergence:
                    "Provider mounted once, and it moved: context/appFlowProviders.tsx now, not contextProvider.tsx (June's source is stale). The render surface was split into ToastStack.tsx, which is dynamically imported by Toast.tsx and imported by nothing else — live through the provider, invisible to every consumer.",
                usedIn: ['context/appFlowProviders.tsx'],
                verified: true,
            },
            {
                name: 'bg-peanut-repeat-{normal,large,small} (component classes)',
                realUsages: 4,
                devUsages: 3,
                status: 'showcase-only',
                source: 'src/styles/globals.css:1013-1021',
                divergence:
                    'SUSPICION RE-CONFIRMED AFTER THE TAILWIND 4 MIGRATION. Re-sourced from the deleted tailwind.config.js to globals.css:1013-1021. All 4 non-/dev matches are plumbing, not renders: 3 are the class definitions themselves in globals.css and 1 is the twMerge conflict-group registration in utils/tw.ts. ZERO product screens render the waving-peanut background that CLAUDE.md documents as the product background. Everything else is /dev/ds/foundations/colors, the audit pages and the twMerge unit test.',
                verified: true,
            },
            {
                name: 'public/bg.svg',
                realUsages: 0,
                status: 'dead',
                source: 'public/bg.svg',
                divergence:
                    "STILL DEAD. Every remaining match is this audit's own data file describing it. No product file imports it or points a URL at it; the bg-peanut-repeat-* classes point at src/assets/bg/peanut-bg.svg instead. Safe delete — unchanged verdict since June.",
                verified: true,
            },
        ],
    },
    {
        category: 'Button variants & ad-hoc buttons',
        layer: 'primitives',
        summary:
            'Button was restyled to vlad\'s button board (17802:61527) and the June headline finding is now OBSOLETE in a good way: size="large" is no longer the shorter-than-default trap — btn-large is h-12 (48px) against .btn\'s h-11 (44px) default. Nothing regressed, but nothing got deleted either: every knob June called dead or showcase-only is STILL unused in the product — variant="dark" (0), shape="square" (0), shadowType="secondary" (0), shadowSize="6"/"8" (0), and now size="large" (0) joins them. Two of those moved from `dead` to `showcase-only` only because the /dev showcase grew to demo them. The bigger untouched surface is CSS: six btn-* size/color classes (btn-purple-2, btn-yellow, btn-xs, btn-xl, btn-2xl, btn-xl-fixed) exist in globals.css and are referenced by nothing but their own definitions — the Button component does not even map to them. Product shadows remain effectively one value: shadowSize="4" on 184 call-sites against 2 for "3" and 0 for everything else, and the JSDoc now admits "4" is a no-op on purple/stroke because those variants carry the shadow already. Ad-hoc <button> elements are down: 65 in product files, of which only 10 carry their own bg-/rounded- styling.',
        items: [
            {
                name: 'shadowSize="4"',
                realUsages: 183,
                devUsages: 30,
                status: 'live',
                source: "src/components/0_Bruddle/Button.tsx (buttonShadows.primary['4'] -> btn-shadow-primary-4)",
                divergence:
                    "184 product call-sites — and the component's own JSDoc now says passing it is a no-op on purple/stroke, which already carry the 4px shadow by default. So most of those 184 props do nothing; they are compatibility noise, not styling. Product shadow depth is effectively a single value.",
                usedIn: [
                    'app/(setup)/setup/page.tsx',
                    'app/recover-wallet/page.tsx',
                    'app/quests/explore/page.tsx',
                    'app/app/page.tsx',
                    'app/quests/[questId]/page.tsx',
                ],
                verified: true,
            },
            {
                name: 'variant="purple"',
                realUsages: 75,
                devUsages: 33,
                status: 'canonical',
                source: 'src/components/0_Bruddle/Button.tsx (buttonVariants.purple -> btn-purple, globals.css:821)',
                divergence:
                    'Canonical primary CTA and still the implicit default, so the rendered count exceeds these 76 explicit call-sites. Now token-backed: btn-purple resolves to bg-action-primary / hover bg-action-primary-hover, not a raw hex.',
                usedIn: [
                    'app/recover-wallet/page.tsx',
                    'app/[...recipient]/error.tsx',
                    'app/(mobile-ui)/card/pin/page.tsx',
                    'app/(mobile-ui)/card/limit/page.tsx',
                    'app/shhhhh/ShhhhhLandingPage.tsx',
                ],
            },
            {
                name: 'variant="stroke"',
                realUsages: 28,
                devUsages: 24,
                status: 'canonical',
                source: 'src/components/0_Bruddle/Button.tsx (buttonVariants.stroke -> btn-stroke, globals.css:833)',
                divergence:
                    'Canonical secondary CTA, up from 15 to 28 product call-sites. Now bg-background-default with the 4px shadow baked in, so it no longer needs a shadowSize prop.',
                usedIn: [
                    'app/(setup)/setup/page.tsx',
                    'app/not-found.tsx',
                    'app/(mobile-ui)/recover-funds/page.tsx',
                    'components/Card/CardRejectionScreen.tsx',
                    'components/Card/BadgeSkipCelebration.tsx',
                ],
            },
            {
                name: 'variant="primary-soft"',
                realUsages: 16,
                devUsages: 3,
                status: 'variant',
                source: "src/components/0_Bruddle/Button.tsx (buttonVariants['primary-soft'])",
                divergence:
                    "Still the only variant with no btn-* class behind it — an inline 'bg-white active:bg-action-primary' literal. It is now half-migrated: the active state uses a semantic token while the rest state is still a raw bg-white.",
                usedIn: [
                    'app/(mobile-ui)/qr-pay/page.tsx',
                    'features/payments/shared/components/PaymentSuccessView.tsx',
                    'components/Setup/Views/Landing.tsx',
                    'components/Setup/Views/SetupPasskey.tsx',
                ],
            },
            {
                name: 'size="small"',
                realUsages: 16,
                devUsages: 14,
                status: 'live',
                source: 'src/components/0_Bruddle/Button.tsx (buttonSizes.small -> btn-small, globals.css:847)',
                divergence:
                    'The only size the product actually reaches for besides the default. btn-small is 40px visual with an ::after pseudo-element extending the hit area to 44px, so it satisfies the touch-target rule without looking 44px. Note this prop name is shared with StatusBadge and Notification, so a raw size="small" grep is not Button-exclusive.',
                usedIn: [
                    'app/(mobile-ui)/rewards/page.tsx',
                    'app/(mobile-ui)/rewards/invites/page.tsx',
                    'components/Kyc/KYCStatusDrawerItem.tsx',
                    'components/AddWithdraw/AddWithdrawCountriesList.tsx',
                    'components/TransactionDetails/TransactionDetailsReceipt.tsx',
                ],
            },
            {
                name: 'size="medium" (redundant — it is the default)',
                realUsages: 11,
                devUsages: 4,
                status: 'variant',
                source: 'src/components/0_Bruddle/Button.tsx (buttonSizes.medium -> btn-medium, globals.css:853)',
                divergence:
                    'btn-medium re-applies h-11 px-3 text-button-m, which .btn already sets — so all 11 product call-sites pass a prop that changes nothing. Same class of no-op as shadowSize="4". (Prop name is shared with StatusBadge, so the count is not Button-exclusive.)',
                usedIn: [
                    'features/limits/components/FiatLimitsLockedCard.tsx',
                    'components/TransactionDetails/TransactionDetailsHeaderCard.tsx',
                    'components/Profile/components/ProfileMenuItem.tsx',
                    'components/Global/OfflineScreen/index.tsx',
                    'components/Payment/Views/Error.validation.view.tsx',
                ],
            },
            {
                name: 'variant="transparent"',
                realUsages: 6,
                devUsages: 1,
                status: 'live',
                source: 'src/components/0_Bruddle/Button.tsx (buttonVariants.transparent — inline utility chain)',
                divergence:
                    'Down from 11 to 6 product call-sites. Still a raw utility chain rather than a btn-* class, and still the only variant needing a special-case disabled patch in buttonClasses — but its hover/active colors now come from --color-action-ghost-hover.',
                usedIn: [
                    'components/SearchInput/index.tsx',
                    'components/Global/TokenSelector/TokenSelector.tsx',
                    'components/Global/LogoutButton/index.tsx',
                    'components/TransactionDetails/ReceiptReferralNudge.tsx',
                    'features/payments/flows/contribute-pot/components/ContributorsDrawer.tsx',
                ],
            },
            {
                name: 'variant="transparent-dark"',
                realUsages: 3,
                status: 'variant',
                source: "src/components/0_Bruddle/Button.tsx (buttonVariants['transparent-dark'] -> btn-transparent-dark)",
                divergence:
                    'Still marginal (3 sites). Together with transparent and transparent-light this is three ghost variants for what the figma board calls one type — consolidation candidate, unchanged from June.',
                usedIn: ['components/Setup/components/SetupWrapper.tsx', 'components/Badges/BadgesRow.tsx'],
            },
            {
                name: 'variant="transparent-light"',
                realUsages: 2,
                devUsages: 1,
                status: 'variant',
                source: "src/components/0_Bruddle/Button.tsx (buttonVariants['transparent-light'] -> btn-transparent-light)",
                divergence:
                    'Two product call-sites, both in the QR scanner, matched by two in /dev. Merge candidate with transparent / transparent-dark.',
                usedIn: ['components/Global/QRScanner/index.tsx'],
            },
            {
                name: 'shadowSize="3"',
                realUsages: 2,
                status: 'variant',
                source: "src/components/0_Bruddle/Button.tsx (buttonShadows.primary['3'])",
                divergence:
                    'Two product call-sites against 184 for "4". A depth the product uses twice — the whole shadowSize prop could be a boolean.',
                usedIn: ['components/AddMoney/views/RhinoDeposit.view.tsx', 'components/UserHeader/index.tsx'],
            },
            {
                name: 'variant="dark"',
                realUsages: 0,
                status: 'showcase-only',
                source: 'src/components/0_Bruddle/Button.tsx (buttonVariants.dark -> btn-dark, globals.css:830)',
                divergence:
                    'Was `dead` in June; now `showcase-only` — the /dev showcase picked it up, the product still never renders it. Its btn-dark class is likewise referenced only by its own definition and the variant map. Still a delete candidate; the showcase reference is the only thing keeping it alive.',
                verified: true,
            },
            {
                name: 'size="large" (trap now FIXED)',
                realUsages: 0,
                devUsages: 4,
                status: 'showcase-only',
                source: 'src/components/0_Bruddle/Button.tsx (buttonSizes.large -> btn-large, globals.css:856)',
                divergence:
                    "STATUS CHANGE, AND THE UNDERLYING BUG IS GONE. In June this was the CLAUDE.md 'naming trap' — large meant h-10 (40px), shorter than the h-13 default. The board restyle made btn-large h-12 (48px) against a 44px default, so large now means large and the @deprecated JSDoc is gone. Ironically the product then stopped using it entirely: 0 product call-sites, 3 in /dev.",
                verified: true,
            },
            {
                name: 'shape="square"',
                realUsages: 0,
                status: 'showcase-only',
                source: "src/components/0_Bruddle/Button.tsx (shape === 'square' -> btn-square, globals.css:839)",
                divergence:
                    'Unchanged: 0 product uses, /dev only. Three CSS rules (.btn-square, .btn-square svg, .btn-square.btn-small/.btn-medium) exist for a shape nothing renders.',
                verified: true,
            },
            {
                name: 'shadowType="secondary"',
                realUsages: 0,
                status: 'showcase-only',
                source: 'src/components/0_Bruddle/Button.tsx (buttonShadows.secondary -> btn-shadow-secondary-{3,4,6,8})',
                divergence:
                    'Was `dead`, now `showcase-only` on the strength of two /dev references. The whole buttonShadows.secondary sub-map and its four btn-shadow-secondary-* classes stay unreachable from the product.',
                verified: true,
            },
            {
                name: 'shadowSize="6" / shadowSize="8"',
                realUsages: 0,
                devUsages: 2,
                status: 'showcase-only',
                source: "src/components/0_Bruddle/Button.tsx (buttonShadows.primary['6'|'8'])",
                divergence:
                    'Unchanged: 0 product uses, /dev only. With "4" at 184 and "3" at 2, the product ships exactly one shadow depth.',
                verified: true,
            },
            {
                name: 'Orphan btn-* classes: btn-purple-2, btn-yellow, btn-xs, btn-xl, btn-2xl, btn-xl-fixed',
                realUsages: 6,
                status: 'dead',
                source: 'src/styles/globals.css:824-867',
                divergence:
                    "NEW ROW, and the largest untouched surface in this category. All 6 non-/dev matches are the class definitions themselves — no product file writes these class names, and the Button component's variant/size maps do not reference any of them. btn-purple-2 also keeps --color-purple-3 alive on paper (3 globals.css-only references), so deleting these classes also frees a palette entry. Pure delete candidates carried over from the v3 config into globals.css without triage.",
                verified: true,
            },
            {
                name: 'Ad-hoc <button> elements (bypassing Button)',
                realUsages: 65,
                devUsages: 47,
                status: 'adhoc',
                source: 'inline lowercase <button> JSX in product files',
                divergence:
                    '65 inline <button> elements in product files, of which 10 carry their own bg-/rounded- styling in the opening tag (a multi-line scan; the probe here counts all <button>, so the bg-/rounded- subset is not in the number). The styled offenders are concentrated: InvitesGraph 3, QRScanner 3, then one each in marketing/error.tsx, ShhhhhLandingPage, ExchangeRateWidget and — notably — 0_Bruddle/Notification.tsx itself, where the primitive hand-rolls its own dismiss button rather than using Button. Down from the June picture: the off-DS radii and hover:bg-gray-* colors mostly survive only inside InvitesGraph.',
                usedIn: [
                    'components/Global/InvitesGraph/index.tsx',
                    'components/Global/QRScanner/index.tsx',
                    'components/0_Bruddle/Notification.tsx',
                    'components/Global/ExchangeRateWidget/index.tsx',
                    'app/[locale]/(marketing)/error.tsx',
                ],
                verified: true,
            },
        ],
    },
    {
        category: 'Pills, Badges & Chips',
        layer: 'components',
        summary:
            "The June headline — 'the same status pill implemented six ways with drifting colors' — is now half-fixed. StatusBadge is firmly canonical (16 product call-sites) and has moved off the raw success-*/yellow-* palette onto the semantic --color-background-badge-* tokens. StatusPill's colour DRIFT IS RESOLVED: it now imports StatusType from StatusBadge and maps to the identical background-badge-* tokens, so the border-yellow-8 vs border-yellow-7 mismatch is gone (it also dropped from 7 to 2 call-sites). Two of the three ad-hoc families followed: PerkRewardReceipt and ExchangeRateWidget still render inline pills, but on tokens now instead of raw Tailwind. What did NOT move is the worst case: the Quest badge pills still use the byte-identical getBadgeColorClasses copy in QuestCard and QuestLeaderboard, and because Tailwind 4 disabled the stock yellow and gray scales, two of its four colour branches (YELLOW -> bg-yellow-100, default -> bg-gray-100) now render as UNSTYLED transparent pills in production while PINK and BLUE still work. New finding: the entire .label* component-class family in globals.css (10 classes: label, label-stroke, label-stroke-{yellow,pink,purple,teal}, label-{purple,teal,yellow,black}) is referenced by nothing outside its own definitions — a whole second badge system that no screen renders, and the only reason --color-teal-1 is still in the palette.",
        items: [
            {
                name: 'StatusBadge',
                realUsages: 16,
                devUsages: 6,
                status: 'canonical',
                source: 'src/components/Global/Badges/StatusBadge.tsx',
                divergence:
                    'Still the canonical token-based text pill, now restyled to the badge board (17802:61533): borderless, dark text, colours from --color-background-badge-{success,attention,info,error,accent,helper}, sizes on the semantic label type scale. Exhaustive STATUS_LABEL_KEYS map means a new status cannot compile without a label key. All other pill implementations should collapse into this via status + customText.',
                usedIn: [
                    'components/TransactionDetails/TransactionDetailsHeaderCard.tsx',
                    'components/Kyc/KYCStatusDrawerItem.tsx',
                    'features/limits/views/LimitsPageView.tsx',
                    'features/payments/shared/components/PaymentMethodActionList.tsx',
                    'components/AddWithdraw/AddWithdrawCountriesList.tsx',
                ],
                verified: true,
            },
            {
                name: 'ChainChip',
                realUsages: 12,
                status: 'live',
                source: 'src/components/AddMoney/components/ChainChip.tsx',
                divergence:
                    "Up from 5 to 12 product call-sites and now with ZERO /dev presence — a chip primitive the product leans on that the showcase does not document. Still built on 0_Bruddle/Card as a labelled logo chip rather than a status pill, so it is legitimately separate from StatusBadge, but it is the only 'chip' family and should be the standard for future chip work.",
                usedIn: [
                    'components/AddMoney/views/CryptoDeposit.view.tsx',
                    'components/AddMoney/views/RhinoDeposit.view.tsx',
                    'components/AddMoney/components/EvmChainChips.tsx',
                    'components/Global/TokenAndNetworkConfirmationModal/index.tsx',
                    'components/LandingPage/SupportedRailsFaqAnswer.tsx',
                ],
                verified: true,
            },
            {
                name: 'Quest badge pill (getBadgeColorClasses)',
                realUsages: 4,
                status: 'duplicate',
                source: 'src/app/quests/components/QuestCard.tsx + src/app/quests/components/QuestLeaderboard.tsx',
                divergence:
                    "WORST REMAINING PILL, AND IT GOT WORSE. getBadgeColorClasses is still byte-identical in both files (YELLOW/PINK/BLUE/default) and still uses raw stock Tailwind classes instead of tokens. Since the Tailwind 4 migration disabled the stock yellow and gray scales in the @theme block, two of the four branches now resolve to nothing: YELLOW -> 'bg-yellow-100 text-yellow-700' and default -> 'bg-gray-100 text-gray-700' render as transparent unstyled text, while PINK -> 'bg-pink-100' and BLUE -> 'bg-blue-100' still work because those stock scales were left enabled. A live visual bug, not just duplication. Fix by mapping onto StatusBadge customText.",
                usedIn: ['app/quests/components/QuestCard.tsx', 'app/quests/components/QuestLeaderboard.tsx'],
                verified: true,
            },
            {
                name: '.label* component-class family (10 classes)',
                realUsages: 9,
                devUsages: 6,
                status: 'dead',
                source: 'src/styles/globals.css:883-921',
                divergence:
                    'NEW ROW. A complete second badge system — .label, .label-stroke, .label-stroke-{yellow,pink,purple,teal}, .label-{purple,teal,yellow,black} — ported verbatim from the v3 config into globals.css. All 9 non-/dev matches are the definitions themselves; no product file writes any of these class names, and the bare .label class is unused too (every product `label` hit is the HTML <label> element). Their only consumer is the /dev label demo. Deleting them also removes the sole reason --color-teal-1 exists.',
                verified: true,
            },
            {
                name: 'StatusPill (icon dot)',
                realUsages: 2,
                devUsages: 2,
                status: 'variant',
                source: 'src/components/Global/StatusPill/index.tsx',
                divergence:
                    'DRIFT FIXED. It still forks a colour map rather than importing one, but the values now match StatusBadge exactly — both map completed/closed/refunded -> background-badge-success, pending -> attention, processing -> info, failed/cancelled -> error, soon -> accent. The June divergence (border-yellow-8 here vs border-yellow-7 there) is gone. Usage collapsed from 7 to 2 product call-sites, so it is now a small icon-only sibling: 3px padding, 14px icon, rounded-round, foreground-over-color-secondary.',
                usedIn: ['components/TransactionDetails/TransactionCard.tsx', 'components/Kyc/KycStatusItem.tsx'],
                verified: true,
            },
            {
                name: 'PerkRewardReceipt status pill (inline)',
                realUsages: 2,
                status: 'duplicate',
                source: 'src/components/TransactionDetails/provider-receipts/PerkRewardReceipt.tsx:52,56',
                divergence:
                    "HALF-FIXED. It now imports STATUS_LABEL_KEYS from StatusBadge and renders on the semantic tokens (rounded-round bg-background-badge-attention / -helper, px-3 py-1 text-label-m) instead of the raw bg-yellow-100 / bg-gray-100 it used in June — which is also what saved it from the dead-scale trap that still hits the Quest pills. But it is still two inline spans reimplementing StatusBadge's branch instead of rendering <StatusBadge status={...} />.",
                usedIn: ['components/TransactionDetails/provider-receipts/PerkRewardReceipt.tsx'],
                verified: true,
            },
            {
                name: "CardFace 'Virtual' pill (inline)",
                realUsages: 2,
                status: 'adhoc',
                source: 'src/components/Card/CardFace.tsx:234,260',
                divergence:
                    "Still duplicated twice within the file for the virtual/revealed states. Colour migrated (bg-background-default, text-body-s) but the shape did not: it uses rounded-full while the DS pill radius is now the semantic rounded-round, and the padding px-4 py-1.5 still matches StatusBadge size='large' — a decorative pill on the card art that could be StatusBadge size='large' customText='Virtual'.",
                usedIn: ['components/Card/CardFace.tsx'],
                verified: true,
            },
            {
                name: 'ExchangeRateWidget rate pill (inline)',
                realUsages: 1,
                status: 'adhoc',
                source: 'src/components/Global/ExchangeRateWidget/index.tsx:310',
                divergence:
                    "Migrated onto tokens (bg-background-disabled, text-label-m, text-foreground-secondary) but keeps the off-scale arbitrary padding py-[2px] and rounded-full instead of rounded-round. The June 'raw bg-grey-4 / text-gray-1' complaint is resolved; the off-scale padding is not.",
                usedIn: ['components/Global/ExchangeRateWidget/index.tsx'],
                verified: true,
            },
            {
                name: 'InvitesGraph stat pills (inline)',
                realUsages: 2,
                status: 'adhoc',
                source: 'src/components/Global/InvitesGraph/index.tsx',
                divergence:
                    'The one ad-hoc pill family that did NOT migrate. Still rounded-full bg-purple-100 / bg-blue-100 with raw stock palette — and purple is one of the nine scales the @theme block disables, so bg-purple-100 now renders nothing while bg-blue-100 still does. InvitesGraph is the single biggest holder of dead stock-shade classes in the app (35 of the 122 product-wide occurrences).',
                usedIn: ['components/Global/InvitesGraph/index.tsx'],
                verified: true,
            },
            {
                name: 'StatusTag (DS audit meta-tooling)',
                realUsages: 0,
                devUsages: 4,
                status: 'showcase-only',
                source: 'src/app/(mobile-ui)/dev/ds/_components/StatusTag.tsx',
                divergence:
                    'Unchanged: lives only under /dev/ds and labels components inside the design-system catalog. Never rendered in the product — meta-tooling, not a product pill. Kept in the inventory so nobody mistakes it for a shippable badge.',
                verified: true,
            },
        ],
    },
    {
        category: 'Tokens (defined vs used)',
        layer: 'tokens',
        summary:
            "tailwind.config.js is GONE. Every token now lives in the @theme block of src/styles/globals.css, and there are two palettes stacked in it: the legacy v3 palette ported verbatim (76 colour tokens) and a NEW semantic layer mapped 1:1 to vlad's figma variables (54 colour tokens: --color-action-*, --color-background-*, --color-foreground-*, --color-border-*, --color-avatar-*, plus a semantic type scale --text-{heading,body,label,button}-*, --radius-round and motion tokens). ADOPTION, MEASURED HONESTLY: the semantic colour layer carries 645 product call-sites against 1099 for the legacy palette — 37% of all colour call-sites, from a standing start. The semantic TYPE scale is further ahead: 500 product call-sites against 420 legacy (text-h1..h10, text-sm, text-heading*), so more than half of typography is already on the new scale. Where the semantic layer is thinnest: 22 of its 54 colour tokens have zero product call-sites, and 18 of those 22 are the avatar palette — only avatar-yellow, avatar-yellow-border and avatar-yellow-foreground are used, all in one file (HomeTopNav). On the legacy side 42 of 76 tokens have zero product call-sites. THE TRAP, QUANTIFIED: the @theme block sets --color-{red,gray,purple,yellow,green,teal,violet,cyan,orange}-*: initial to reproduce v3's scale replacement, so class names like text-gray-500, bg-gray-200 and bg-yellow-400 are valid-looking call-sites that generate NO CSS. There are 122 such occurrences across 37 product files (367 including /dev) — top offenders InvitesGraph (35), QuestCard (11), quests/explore (7). Nine other stock scales (blue, pink, slate, amber, ...) were left enabled, so 25 further off-token call-sites do render, which is why the breakage is invisible in review. The named-spacing worry in the globals.css comment is smaller than stated: only ONE genuine dead call-site (w-xl) exists — the '~70' figure counts max-w-*/min-w-*, which resolve through the still-live container scale.",
        items: [
            {
                name: 'DEAD-CLASS TRAP: disabled stock scales (text-gray-500, bg-gray-200, bg-yellow-400, …)',
                realUsages: 122,
                devUsages: 202,
                status: 'dead',
                source: 'src/styles/globals.css:22-30 (--color-{red,gray,purple,yellow,green,teal,violet,cyan,orange}-*: initial)',
                divergence:
                    "NEW ROW — this page's sharpest finding. v3 REPLACED the stock Tailwind scales; the v4 @theme block reproduces that by setting nine scales to `initial`. Every stock numeric shade of those nine families therefore generates no CSS, but the class names still look correct in review and in the editor. 122 live product call-sites across 37 files render nothing at all. Most frequent: text-gray-500 (40), bg-gray-200 (32), text-gray-700 (29), border-gray-300 (26), bg-yellow-400 (17), text-red-500 (7). Concentrated in InvitesGraph (35), the quests surface (27 across 5 files) and marketing error/help pages — but it also reaches 0_Bruddle/Button.tsx:198, where the long-press progress gradient `from-purple-400 to-purple-600` is invisible.",
                usedIn: [
                    'components/Global/InvitesGraph/index.tsx',
                    'app/quests/components/QuestCard.tsx',
                    'app/quests/explore/page.tsx',
                    'app/quests/components/QuestLeaderboard.tsx',
                    'app/(mobile-ui)/qr-pay/page.tsx',
                ],
                verified: true,
            },
            {
                name: 'semantic type scale: --text-{heading,body,label,button}-*',
                realUsages: 486,
                devUsages: 4,
                status: 'canonical',
                source: 'src/styles/globals.css:203-255',
                divergence:
                    'NEW ROW. The best-adopted part of the new token layer: 486 product call-sites, and only 19 more in /dev — this is a product-first migration, not a showcase. Breakdown: body-* 305, heading-* 135, label-* 30, button-* 16. Against it, the legacy scale (text-h1..h10, text-sm, text-heading/headingLarge/headingMedium, text-6xl..9xl) still holds 420 product call-sites, so typography is roughly 54% migrated.',
                usedIn: [
                    'app/(mobile-ui)/rewards/page.tsx',
                    'app/(mobile-ui)/recover-funds/page.tsx',
                    'app/(mobile-ui)/qr/[code]/page.tsx',
                    'app/(mobile-ui)/add-money/[country]/bank/page.tsx',
                    'app/(mobile-ui)/rewards/invites/page.tsx',
                ],
                verified: true,
            },
            {
                name: 'semantic colour: --color-foreground-*',
                realUsages: 386,
                devUsages: 4,
                status: 'canonical',
                source: 'src/styles/globals.css:164-169',
                divergence:
                    'NEW ROW, and by far the most-adopted semantic colour group: foreground-primary 183, foreground-secondary 177, foreground-error 20, foreground-over-color-secondary 4. It has largely displaced text-n-1 / text-grey-1 in new code, though both legacy names remain heavily live (n-1 225, grey-1 107). foreground-over-color-primary is the one member with zero product call-sites.',
                usedIn: [
                    'app/(mobile-ui)/card/page.tsx',
                    'app/(mobile-ui)/card/pin/page.tsx',
                    'app/(mobile-ui)/recover-funds/page.tsx',
                    'app/(mobile-ui)/rewards/invites/page.tsx',
                    'app/(mobile-ui)/card/physical/page.tsx',
                ],
                verified: true,
            },
            {
                name: 'color: n-1 (#000000, brand black border)',
                realUsages: 225,
                devUsages: 229,
                status: 'live',
                source: 'src/styles/globals.css:87',
                divergence:
                    'Still the most-used legacy token (225 product call-sites) and still hex-identical to `black` (113 call-sites) and to the semantic --color-border-button / --color-foreground-primary. Four names for #000000 now, one more than in June. The DS-06 direction is foreground-primary / border-default, so n-1 is the largest single migration backlog in the palette.',
                usedIn: [
                    'app/app/page.tsx',
                    'app/[locale]/(marketing)/press/page.tsx',
                    'app/[locale]/(marketing)/blog/[slug]/page.tsx',
                    'context/RainCooldownContext.tsx',
                    'app/[locale]/(marketing)/stories/page.tsx',
                ],
            },
            {
                name: 'radius: rounded-full',
                realUsages: 150,
                devUsages: 26,
                status: 'duplicate',
                source: 'tailwind default (v4 core)',
                divergence:
                    "STATUS CHANGE: live -> duplicate. The @theme block now defines --radius-round: 999px as the semantic pill radius, and 25 product call-sites already use rounded-round (including Button's .btn, StatusPill and PerkRewardReceipt). rounded-full is the same visual result under a second name, on 150 call-sites. Two names for one radius is exactly the kind of drift the semantic layer was supposed to end.",
                usedIn: [
                    'app/(mobile-ui)/rewards/page.tsx',
                    'app/quests/components/QuestCard.tsx',
                    'app/(mobile-ui)/qr-pay/page.tsx',
                    'app/(mobile-ui)/recover-funds/page.tsx',
                    'app/quests/components/UserRankCard.tsx',
                ],
                verified: true,
            },
            {
                name: 'radius: rounded-sm (the mandated DS radius)',
                realUsages: 113,
                devUsages: 142,
                status: 'live',
                source: 'src/styles/globals.css:289 (--radius-sm: 0.125rem — v3 parity override)',
                divergence:
                    "Re-sourced from the deleted config. Note the v4 default for rounded-sm is 0.25rem; globals.css:289 overrides it back to v3's 0.125rem, so the class means something different here than in stock Tailwind. Still the CLAUDE.md-mandated radius and still heavily live at 113 product call-sites.",
                usedIn: [
                    'app/quests/explore/page.tsx',
                    'app/[locale]/(marketing)/press/page.tsx',
                    'app/quests/[questId]/page.tsx',
                    'app/[locale]/(marketing)/content/page.tsx',
                    'app/[locale]/(marketing)/stories/page.tsx',
                ],
                verified: true,
            },
            {
                name: 'color: grey-1 (#5F646D) vs gray-1 vs n-3',
                realUsages: 107,
                devUsages: 249,
                status: 'duplicate',
                source: 'src/styles/globals.css:47 (grey-1), :81 (gray-1), :89 (n-3)',
                divergence:
                    'Unchanged and still the clearest duplicate in the palette: THREE token names for #5F646D — grey-1 (107 product call-sites), gray-1 (11), n-3 (0 direct). The semantic layer adds a fourth spelling of the same value, --color-foreground-secondary (177 call-sites), which is now the most-used of the four. The @theme comment already marks grey.*/gray.* as a deprecated duplicate pair; the collapse target is foreground-secondary.',
                usedIn: [
                    'app/app/page.tsx',
                    'app/recover-wallet/page.tsx',
                    'app/(mobile-ui)/qr-pay/page.tsx',
                    'app/[locale]/(marketing)/press/page.tsx',
                    'app/[locale]/(marketing)/stories/page.tsx',
                ],
                verified: true,
            },
            {
                name: 'color: primary-1 (#FF90E8, PINK)',
                realUsages: 87,
                devUsages: 17,
                status: 'live',
                source: 'src/styles/globals.css:32',
                divergence:
                    'Canonical brand pink, up from 60 to 87 product call-sites. Misleadingly named (it is pink, not purple) and still hex-identical to purple-1 — and now also to the semantic --color-action-primary (29 call-sites) and --color-background-brand (0). Three live names for #FF90E8; action-primary is the migration target.',
                usedIn: [
                    'app/shhhhh/ShhhhhLandingPage.tsx',
                    'app/m/[slug]/MerchantLandingPage.tsx',
                    'components/Home/ActivationCTAs.tsx',
                    'components/Home/WelcomeUnlockModal/index.tsx',
                    'features/payments/flows/contribute-pot/components/RequestPotActionList.tsx',
                ],
            },
            {
                name: 'semantic colour: --color-background-* (default/page/disabled/brand + badge + iconBubble)',
                realUsages: 120,
                status: 'canonical',
                source: 'src/styles/globals.css:146-162',
                divergence:
                    'NEW ROW. 120 product call-sites and ZERO extra in /dev — the whole group is product-driven. background-default 49, background-disabled 26, background-badge-* 31 (via StatusBadge/StatusPill/Notification), background-icon-bubble-* 20 (via IconBubble), background-page 7. Only --color-background-brand is unused, because primary-1 / action-primary already cover it. Watch the name collision: the legacy palette also has a plain --color-background (#faf4f0, 134 call-sites as bg-background), which is the same value as background-page under a different name.',
                usedIn: [
                    'app/(mobile-ui)/rewards/page.tsx',
                    'app/(mobile-ui)/qr/[code]/page.tsx',
                    'features/limits/components/IncreaseLimitsButton.tsx',
                    'components/Card/LockCardModal.tsx',
                    'components/Card/CardPinScreen.tsx',
                ],
                verified: true,
            },
            {
                name: 'semantic colour: --color-border-*',
                realUsages: 73,
                status: 'canonical',
                source: 'src/styles/globals.css:171-177',
                divergence:
                    'NEW ROW. 73 product call-sites, none extra in /dev. border-default 51, border-subtle 14, border-button 4, border-disabled 3. Two of the seven members are unused: border-accent and border-button-secondary (the latter is byte-identical to border-button, so it should probably not exist). The competing legacy idiom `border border-n-1` still has 225 call-sites.',
                usedIn: [
                    'app/(mobile-ui)/rewards/page.tsx',
                    'app/(mobile-ui)/profile/backup/page.tsx',
                    'features/home/views/BalanceSection.tsx',
                    'features/limits/components/IncreaseLimitsButton.tsx',
                    'components/Card/AddToWalletCarousel.tsx',
                ],
                verified: true,
            },
            {
                name: 'semantic colour: --color-action-*',
                realUsages: 58,
                devUsages: 1,
                status: 'canonical',
                source: 'src/styles/globals.css:140-144',
                divergence:
                    'NEW ROW. 58 product call-sites. action-primary 29, action-ghost-hover 12 (mostly inside the Button variant strings), action-focus 11, action-secondary 6, action-primary-hover 3. All five members are used — the only semantic colour group with no dead entries. It is also the group that makes .btn-purple and .btn-stroke token-backed rather than hex-backed.',
                usedIn: [
                    'app/(mobile-ui)/rewards/page.tsx',
                    'app/(mobile-ui)/qr/[code]/page.tsx',
                    'app/(mobile-ui)/qr/[code]/success/page.tsx',
                    'features/home/views/BalanceSection.tsx',
                    'features/limits/components/FiatLimitsLockedCard.tsx',
                ],
                verified: true,
            },
            {
                name: 'legacy type scale: text-h1 … text-h10',
                realUsages: 43,
                devUsages: 9,
                status: 'variant',
                source: 'src/styles/globals.css:340-369',
                divergence:
                    'Re-sourced from the deleted config. The v3 heading scale survives on 43 product call-sites against 486 for the semantic scale — and half of its ten steps (h3, h4, h5, h9, h10) have zero product call-sites at all. It duplicates the semantic heading scale step for step (text-h4 1.5rem == text-heading-s 1.5rem, text-h6 1.125rem == text-heading-card 1.125rem). Collapse target: --text-heading-*.',
                usedIn: [
                    'app/(mobile-ui)/card-recovery/page.tsx',
                    'components/Marketing/DestinationGrid.tsx',
                    'components/Marketing/mdx/Steps.tsx',
                    'components/Request/link/views/Create.request.link.view.tsx',
                ],
                verified: true,
            },
            {
                name: 'radius: rounded-{md,lg,xl,2xl,3xl}',
                realUsages: 34,
                devUsages: 22,
                status: 'variant',
                source: 'tailwind default (v4 core)',
                divergence:
                    "Off-spec radii still coexisting with the mandated rounded-sm, and up from 18 to 34 product call-sites since June — this drift is growing, not shrinking. Each is an ad-hoc deviation from the 'always rounded-sm' rule (and now also from rounded-round for pills).",
                usedIn: [
                    'components/Card/CardFace.tsx',
                    'components/Tooltip/TooltipContent.tsx',
                    'components/Home/PerkClaimModal.tsx',
                    'app/[locale]/(marketing)/error.tsx',
                    'components/Card/share-asset/PixelatedCardFace.tsx',
                ],
            },
            {
                name: 'color: secondary-1 / yellow-1 (#FFC900, brand yellow — two names)',
                realUsages: 33,
                devUsages: 3,
                status: 'duplicate',
                source: 'src/styles/globals.css:37 (secondary-1), :63 (yellow-1)',
                divergence:
                    'Unchanged duplicate, now with a third name: secondary-1 (33 product call-sites), yellow-1 (23) and the semantic --color-action-secondary (6) are all #FFC900. Merged into one row this round — June carried them as two separate entries saying the same thing.',
                usedIn: [
                    'app/(mobile-ui)/qr-pay/page.tsx',
                    'app/(mobile-ui)/rewards/page.tsx',
                    'app/m/[slug]/MerchantLandingPage.tsx',
                    'app/shhhhh/ShhhhhLandingPage.tsx',
                    'components/Home/PendingVerificationTasks.tsx',
                ],
                verified: true,
            },
            {
                name: 'motion tokens: duration-{instant,fast,moderate,slow}',
                realUsages: 29,
                status: 'live',
                source: 'src/styles/globals.css:267-270',
                divergence:
                    'NEW ROW. The motion scale is real and already used: 29 product call-sites (instant 14, fast 7, moderate 7). --transition-duration-slow (500ms) has ZERO product call-sites — a fourth step nothing needs. Note the namespace trap documented in the file: --transition-duration-* is what drives duration-*; a bare --duration-* would generate nothing.',
                usedIn: [
                    'features/home/views/BalanceSection.tsx',
                    'components/0_Bruddle/LinkButton.tsx',
                    'components/0_Bruddle/Accordion.tsx',
                    'components/0_Bruddle/ProgressBar.tsx',
                    'components/0_Bruddle/CarouselDots.tsx',
                ],
                verified: true,
            },
            {
                name: 'radius: rounded-round (999px, semantic pill)',
                realUsages: 25,
                status: 'canonical',
                source: 'src/styles/globals.css:261',
                divergence:
                    'NEW ROW. The only semantic radius token, 25 product call-sites — .btn, StatusPill, PerkRewardReceipt, IconBubble, CarouselDots, SlideToConfirm. It is the intended replacement for rounded-full (150 call-sites), so the pill radius currently ships under two names.',
                usedIn: [
                    'features/home/views/BalanceSection.tsx',
                    'components/0_Bruddle/SlideToConfirm.tsx',
                    'components/0_Bruddle/IconBubble.tsx',
                    'components/0_Bruddle/CarouselDots.tsx',
                    'components/TransactionDetails/provider-receipts/PerkRewardReceipt.tsx',
                ],
                verified: true,
            },
            {
                name: 'OFF-TOKEN BUT RENDERING: stock scales left enabled (blue, pink, slate, amber, …)',
                realUsages: 25,
                devUsages: 11,
                status: 'adhoc',
                source: 'src/styles/globals.css:22-30 (these families are absent from the `initial` list)',
                divergence:
                    "NEW ROW, and the reason the dead-class trap goes unnoticed. Nine stock families were disabled; the rest (blue, pink, slate, zinc, neutral, stone, amber, lime, emerald, sky, indigo, fuchsia, rose) were left alone, so 25 product call-sites across 9 files DO render — bg-pink-100, bg-blue-100, text-blue-700 and friends. Same file often mixes both: QuestCard's badge helper has two branches that render and two that do not. These are off-token colours with no DS entry, so even the working ones are drift.",
                usedIn: [
                    'app/quests/components/QuestCard.tsx',
                    'app/quests/components/QuestLeaderboard.tsx',
                    'app/quests/explore/page.tsx',
                    'app/quests/[questId]/page.tsx',
                    'app/quests/components/UserRankCard.tsx',
                ],
                verified: true,
            },
            {
                name: 'color: success-* family',
                realUsages: 24,
                devUsages: 15,
                status: 'variant',
                source: 'src/styles/globals.css:100-106',
                divergence:
                    'Seven slots, three of them live: success-3 (15), success-1 (9), and nothing else — success-2, success-4, success-5, success-6 and success-7 all have ZERO product call-sites now, because StatusBadge moved its success colour to --color-background-badge-success. The scale is 4/7 dead and shrinking.',
                usedIn: [
                    'app/(mobile-ui)/qr-pay/page.tsx',
                    'app/(mobile-ui)/recover-funds/page.tsx',
                    'app/(mobile-ui)/withdraw/manteca/page.tsx',
                    'features/limits/views/BridgeLimitsView.tsx',
                    'features/payments/shared/components/PaymentSuccessView.tsx',
                ],
                verified: true,
            },
            {
                name: 'color: error / error-1 … error-6',
                realUsages: 21,
                devUsages: 20,
                status: 'variant',
                source: 'src/styles/globals.css:115-121',
                divergence:
                    'NEW ROW. Seven slots, two live: the bare `error` (#b3261e) and error-4. error-1, error-2, error-3, error-5 and error-6 have zero product call-sites — every one of their matches is a /dev showcase or audit page. The semantic replacements (--color-foreground-error 20 call-sites, --color-background-badge-error 5, --color-border-error 1) already carry the error surface.',
                usedIn: [
                    'app/shhhhh/ShhhhhLandingPage.tsx',
                    'components/Kyc/ProvideEmailStep.tsx',
                    'components/Home/PendingVerificationTasks.tsx',
                    'components/0_Bruddle/BaseSelect.tsx',
                    'features/limits/utils.ts',
                ],
                verified: true,
            },
            {
                name: 'shadow: shadow-4 / shadow-primary-4 / btn-shadow-primary-4 (three names, one shadow)',
                realUsages: 13,
                devUsages: 4,
                status: 'duplicate',
                source: 'src/styles/globals.css:714 (@utility shadow-4), :956 (.shadow-primary-4), :986 (.btn-shadow-primary-4)',
                divergence:
                    'Re-sourced from the deleted config, and the duplication got one level worse. The count above is shadow-4 alone. THREE class names expand to the identical 0.25rem black drop shadow: shadow-4 (13 product call-sites, promoted to an @utility so it can take variants), shadow-primary-4 (10) and btn-shadow-primary-4 (9). On top of that, .btn-purple and .btn-stroke inline the same shadow a fourth time as shadow-[0.25rem_0.25rem_0_var(--color-shadow-primary)]. One visual effect, four spellings.',
                usedIn: [
                    'app/[...recipient]/error.tsx',
                    'app/(mobile-ui)/withdraw/manteca/page.tsx',
                    'app/not-found.tsx',
                    'components/0_Bruddle/SlideToConfirm.tsx',
                    'components/Marketing/MarketingHero.tsx',
                ],
                verified: true,
            },
            {
                name: 'shadow: shadow-secondary-{4,6,8} & btn-shadow-secondary-{3,4,6,8}',
                realUsages: 14,
                status: 'dead',
                source: 'src/styles/globals.css:965-972, :995-1005',
                divergence:
                    'STATUS CHANGE: variant -> dead. All 14 non-/dev matches are the class definitions in globals.css plus the buttonShadows.secondary map inside Button.tsx. No product file writes any shadow-secondary-* class, and shadowType="secondary" — the only way to reach the btn- variants — has 0 product call-sites. Seven classes for an upward shadow nothing renders.',
                usedIn: ['components/0_Bruddle/Button.tsx', 'components/0_Bruddle/Card.tsx'],
                verified: true,
            },
            {
                name: 'DEAD LEGACY PALETTE: 32 tokens with zero product call-sites',
                realUsages: 0,
                devUsages: 28,
                status: 'dead',
                source: 'src/styles/globals.css:32-121 (legacy palette block)',
                divergence:
                    "MERGED ROW replacing eight separate June entries. Every one of these still exists in the @theme block and has ZERO product call-sites: outline-1/2/3, cyan-1, teal-3, purple-2/4/5/6, secondary-2/5/9, green-2, yellow-2/3/4/5/10, kyc-red, kyc-green, gray-2/3/4/5, violet-9, error-3/5/6, grey-3, n-4, success-6/7. Every remaining match is a /dev showcase or this audit's own data. Two June rows were REMOVED rather than merged here — primary-base and secondary-base no longer exist in the token source at all, the v4 migration dropped them.",
                verified: true,
            },
            {
                name: 'semantic colour: --color-avatar-* (21 tokens, 3 used)',
                realUsages: 3,
                status: 'showcase-only',
                source: 'src/styles/globals.css:179-199',
                divergence:
                    'NEW ROW — the thinnest part of the new layer. Seven avatar colours × (fill, border, foreground) = 21 tokens ported 1:1 from figma, and exactly THREE have a product call-site: avatar-yellow, avatar-yellow-border and avatar-yellow-foreground, all in one file (features/home/views/HomeTopNav.tsx). The other 18 (pink, orange, blue, purple, red, green) are defined and rendered nowhere — not even in /dev. If avatar colour is meant to vary per user, that logic does not exist yet.',
                usedIn: ['features/home/views/HomeTopNav.tsx'],
                verified: true,
            },
            {
                name: 'color: purple-1 (#FF90E8, == primary-1)',
                realUsages: 4,
                devUsages: 15,
                status: 'duplicate',
                source: 'src/styles/globals.css:56',
                divergence:
                    "Unchanged: exact hex duplicate of primary-1, down to 4 product call-sites against 87 for primary-1. The @theme comment now says the purple.* group was 'marked todo: remove in the old config' and repeats the deprecation — but the tokens were carried over anyway. purple-1 and purple-3 are the only survivors; purple-3's 3 remaining references are all inside the dead .btn-purple-2 class.",
                usedIn: [
                    'app/not-found.tsx',
                    'components/PeanutRagdoll/index.tsx',
                    'components/Global/CancelSendLinkDrawer/index.tsx',
                    'hooks/useHomeCarouselCTAs.tsx',
                ],
                verified: true,
            },
            {
                name: 'color: teal-1 (#23A094)',
                realUsages: 4,
                devUsages: 1,
                status: 'showcase-only',
                source: 'src/styles/globals.css:78',
                divergence:
                    'Unchanged verdict, re-sourced. All 4 non-/dev matches are inside globals.css itself — the .label-teal and .label-stroke-teal definitions. Since that whole .label* family has zero product call-sites (see the Pills category), teal-1 reaches no screen. Delete the label classes and this token goes with them.',
                verified: true,
            },
            {
                name: 'color: green-1 (#98E9AB)',
                realUsages: 1,
                devUsages: 9,
                status: 'live',
                source: 'src/styles/globals.css:75',
                divergence:
                    'Verdict from the June re-verification holds: exactly ONE genuine product call-site — app/m/[slug]/MerchantLandingPage.tsx renders the live cripto-dolar status dot with bg-green-1. Everything else is /dev. Hex-identical to outline-1 (which is fully dead). Product greens otherwise come from success-* and background-badge-success.',
                usedIn: ['app/m/[slug]/MerchantLandingPage.tsx'],
                verified: true,
            },
            {
                name: 'shadow: shadow-2 (0.125rem black)',
                realUsages: 4,
                devUsages: 1,
                status: 'live',
                source: 'src/styles/globals.css:953',
                divergence:
                    "Re-sourced from the deleted config. The June re-verification stands: it is genuinely live, not showcase-only — TokenSelector's NetworkButton and Global/Slider both apply it, and NetworkButton is rendered twice by TokenSelector. Still the thinnest custom drop shadow against a product that otherwise standardises on the 0.25rem depth.",
                usedIn: [
                    'components/Global/TokenSelector/Components/NetworkButton.tsx',
                    'components/Global/Slider/index.tsx',
                ],
                verified: true,
            },
            {
                name: 'ease-spring / ease-sharp (motion easing)',
                realUsages: 2,
                status: 'showcase-only',
                source: 'src/styles/globals.css:271-272',
                divergence:
                    'NEW ROW. Both easing tokens exist and both non-/dev matches are their own definitions in globals.css — no product file writes ease-spring or ease-sharp as a class. The curves DO reach screens indirectly (the accordion keyframes hard-code the same cubic-bezier), which is precisely the divergence: the token was defined and the animation duplicated the value instead of using it.',
                verified: true,
            },
            {
                name: 'radius: rounded-1 (0.0625rem)',
                realUsages: 0,
                status: 'showcase-only',
                source: 'src/styles/globals.css:290',
                divergence:
                    "Survived the v4 migration untouched and is still referenced 0 times in the product. A 1px radius in a DS whose rule is 'always rounded-sm' (and now rounded-round for pills). Delete candidate, unchanged since June.",
                verified: true,
            },
            {
                name: 'named spacing scale (w-xl, w-2xl …) — the smaller half of the trap',
                realUsages: 1,
                status: 'dead',
                source: 'src/styles/globals.css:131-137 (the DEFERRED note in the @theme comment)',
                divergence:
                    "NEW ROW, and a CORRECTION. The @theme comment defers the named spacing scale because '~70 dead call-sites use exactly those classes today'. Measured with a boundary that excludes max-w-*/min-w-* — which resolve through the still-live container scale and are fine — the real figure is ONE: a single w-xl call-site. The other ~69 are max-w-xl / max-w-2xl / max-w-3xl and render correctly. Worth recording so the DS-06 sweep does not budget for a problem that is one line.",
                verified: true,
            },
        ],
    },
]
