import type { UsageCategory } from '../../_components/UsageAudit'

// AUTO-GENERATED by the ds-real-usage-audit workflow (real-app usage verified via grep, dead claims
// independently re-verified). Do not hand-edit — regenerate with the workflow.
export const APP_DIVERGENCE_CATEGORIES: UsageCategory[] = [
    {
        category: 'Primitives & Backgrounds',
        layer: 'primitives',
        summary:
            'Audited all 10 files in src/components/0_Bruddle/ plus the Tailwind bg-peanut-repeat-* utilities and public/bg.svg via path-based greps (no 0_Bruddle barrel exists, so imports can\'t hide). 8 of 10 primitives are genuinely live in the product; Button (134 real) is the workhorse and PageContainer (30 real) is the canonical page-layout wrapper. Two suspicions CONFIRMED: (1) Title has exactly ONE real usage — MarketingHero — and otherwise only appears in the /dev showcase, so it is effectively a Marketing-only primitive dressed as a DS component; (2) all three bg-peanut-repeat-normal/-large/-small classes have ZERO real usages (only /dev/components + /dev/ds/foundations/colors), so the "waving peanut pattern" CLAUDE.md documents as a product background is showcase-only. Worst dead finding: public/bg.svg (2.2KB) is referenced NOWHERE in src (the tailwind classes point at a different file, src/assets/bg/peanut-bg.svg, 62KB) — fully dead. BaseSelect is barely-live (1 real call-site). The internal Toast render component is never imported outside its file; only ToastProvider (1 real, in contextProvider) and useToast (18 real) are consumed.',
        items: [
            {
                name: 'Button (0_Bruddle/Button)',
                realUsages: 134,
                status: 'live',
                devUsages: 17,
                source: 'src/components/0_Bruddle/Button.tsx',
                divergence:
                    "Canonical primitive — 134 real call-sites. No competing impl; keep. Only 'variant' concern is the internal 'large' size (h-10, shorter than default h-13) already @deprecated in JSDoc.",
                usedIn: [
                    'components/Invites/JoinWaitlistPage.tsx',
                    'components/AddMoney/views/RhinoDeposit.view.tsx',
                    'components/AddMoney/components/InputAmountStep.tsx',
                    'components/Profile/index.tsx',
                    'components/AddMoney/components/AddMoneyBankDetails.tsx',
                ],
            },
            {
                name: 'PageContainer (0_Bruddle/PageContainer)',
                realUsages: 30,
                status: 'live',
                devUsages: 2,
                source: 'src/components/0_Bruddle/PageContainer.tsx',
                divergence:
                    'Canonical page-shell wrapper (30 real usages, mostly route page.tsx/layout.tsx). Hard-codes md:pl-24 + md:*:max-w-xl — a fixed left desktop gutter baked into every page that uses it.',
                usedIn: [
                    'app/(mobile-ui)/home/page.tsx',
                    'app/(mobile-ui)/card/page.tsx',
                    'app/[...recipient]/page.tsx',
                    'app/(mobile-ui)/profile/page.tsx',
                    'components/Claim/Claim.tsx',
                ],
            },
            {
                name: 'Card (0_Bruddle/Card)',
                realUsages: 15,
                status: 'live',
                devUsages: 8,
                source: 'src/components/0_Bruddle/Card.tsx',
                divergence:
                    'duplicate/variant vs Global/Card (default export): 0_Bruddle/Card is the standalone-container card (named export, rounded-sm border-n-1 bg-white), Global/Card is stacked list-items. Two Card components with the same name imported from different paths — a naming collision that forces devs to disambiguate by import path.',
                usedIn: [
                    'components/AddMoney/components/ChainChip.tsx',
                    'components/Global/SuccessViewComponents/SuccessViewDetailsCard.tsx',
                    'components/Home/HomeCarouselCTA/CarouselCTA.tsx',
                    'components/Setup/Views/Landing.tsx',
                    'app/(mobile-ui)/withdraw/manteca/page.tsx',
                ],
            },
            {
                name: 'BaseInput (0_Bruddle/BaseInput)',
                realUsages: 9,
                status: 'live',
                devUsages: 3,
                source: 'src/components/0_Bruddle/BaseInput.tsx',
                divergence:
                    "Live thin wrapper over the .input @apply utility (defined in tailwind.config.js line 623). variant sizes (sm/md/lg) duplicate height logic that also lives in the .input class default h-16 — the class hard-codes h-16 while variant='md' re-applies h-16.",
                usedIn: [
                    'components/Global/ValidatedInput/index.tsx',
                    'components/Global/FileUploadInput/index.tsx',
                    'components/Global/CopyField/index.tsx',
                    'components/Profile/components/ProfileEditField.tsx',
                    'components/AddWithdraw/DynamicBankAccountForm.tsx',
                ],
            },
            {
                name: 'Divider (0_Bruddle/Divider)',
                realUsages: 7,
                status: 'live',
                devUsages: 3,
                source: 'src/components/0_Bruddle/Divider.tsx',
                divergence:
                    'Live. Hard-codes line thickness h-0.25 and bg-n-1 (black) / dark:bg-white with no thickness/color prop — callers can only override via dividerClassname twMerge.',
                usedIn: [
                    'components/Send/views/SendRouter.view.tsx',
                    'components/Global/TokenSelector/TokenSelector.tsx',
                    'components/Claim/Link/SendLinkActionList.tsx',
                    'components/Common/SavedAccountsView.tsx',
                    'features/payments/shared/components/PaymentMethodActionList.tsx',
                ],
            },
            {
                name: 'Checkbox (0_Bruddle/Checkbox)',
                realUsages: 4,
                status: 'live',
                devUsages: 4,
                source: 'src/components/0_Bruddle/Checkbox.tsx',
                divergence:
                    "Live but concentrated in Card flows. Uses template-literal className interpolation (`... ${className}`) instead of twMerge — the only 0_Bruddle primitive that does NOT use twMerge, so caller classes can't override the box border/size, they only append.",
                usedIn: [
                    'components/Card/CardTermsScreen.tsx',
                    'components/Card/CardUnlockDrawer.tsx',
                    'components/Card/BadgeSkipCelebration.tsx',
                    'components/Global/QRScannerOverlay/index.tsx',
                ],
            },
            {
                name: 'CloudsBackground (0_Bruddle/CloudsBackground)',
                realUsages: 3,
                status: 'live',
                devUsages: 0,
                source: 'src/components/0_Bruddle/CloudsBackground.tsx',
                divergence:
                    "Live decorative background but ALL 3 real call-sites pass `minimal` — the full non-minimal cloud config (desktopClouds/mobileClouds, ~10 cloud objects) is never rendered in the product, so most of the file's config arrays are effectively dead branches.",
                usedIn: [
                    'components/Invites/InvitesPageLayout.tsx',
                    'components/Setup/components/SetupWrapper.tsx',
                    'components/Global/IframeWrapper/StartVerificationView.tsx',
                ],
            },
            {
                name: 'BaseSelect (0_Bruddle/BaseSelect)',
                realUsages: 1,
                status: 'live',
                devUsages: 3,
                source: 'src/components/0_Bruddle/BaseSelect.tsx',
                divergence:
                    "Barely-live: exactly ONE real consumer (DynamicBankAccountForm). Radix-based; hard-codes h-12 trigger height (vs BaseInput's h-16 md default) and rounded-sm — a lone select primitive that would be trivial to inline or accidentally break DS-wide with no real coverage.",
                usedIn: ['components/AddWithdraw/DynamicBankAccountForm.tsx'],
            },
            {
                name: 'Title (0_Bruddle/Title)',
                realUsages: 1,
                status: 'live',
                devUsages: 5,
                source: 'src/components/0_Bruddle/Title.tsx',
                divergence:
                    'SUSPICION CONFIRMED: only ONE real usage (MarketingHero.tsx line 44) and otherwise only in /dev (dev/components, dev/ds/primitives/title, dev/ds/page, dev/ds/foundations/typography, audit-data). Effectively a Marketing-only decorative title (font-knerd-filled + offset outline layer), not a product-wide primitive — merge/delete candidate: could live in components/Marketing/ instead of the shared DS.',
                usedIn: ['components/Marketing/MarketingHero.tsx'],
            },
            {
                name: 'ToastProvider (0_Bruddle/Toast)',
                realUsages: 1,
                status: 'live',
                devUsages: 1,
                source: 'src/components/0_Bruddle/Toast.tsx',
                divergence:
                    'Provider mounted once at the app root (contextProvider.tsx). The actual `Toast` render component in the same file is internal-only (never imported elsewhere); consumers use the `useToast` hook (18 real usages) — so the exported surface is the hook, not the component.',
                usedIn: ['context/contextProvider.tsx'],
            },
            {
                name: 'bg-peanut-repeat-normal (tailwind utility)',
                realUsages: 0,
                status: 'showcase-only',
                devUsages: 2,
                source: 'tailwind.config.js:627',
                divergence:
                    "SUSPICION CONFIRMED: 0 real usages. Only appears in dev/components/page.tsx and dev/ds/foundations/colors/page.tsx. CLAUDE.md documents it as 'the waving peanut pattern' background for the product, but no non-dev file renders it — the documented product background is showcase-only. @apply bg-[url('../assets/bg/peanut-bg.svg')] bg-[length:100px_100px].",
                verified: true,
            },
            {
                name: 'bg-peanut-repeat-large (tailwind utility)',
                realUsages: 0,
                status: 'showcase-only',
                devUsages: 2,
                source: 'tailwind.config.js:630',
                divergence:
                    '0 real usages; only in dev/components + dev/ds/foundations/colors. Identical to -normal except bg-[length:200px_200px] — a size variant of a class the product never renders. Delete candidate.',
                verified: true,
            },
            {
                name: 'bg-peanut-repeat-small (tailwind utility)',
                realUsages: 0,
                status: 'showcase-only',
                devUsages: 2,
                source: 'tailwind.config.js:633',
                divergence:
                    '0 real usages; only in dev/components + dev/ds/foundations/colors. Identical to -normal except bg-[length:50px_50px] — third size variant of an unused class. Delete candidate.',
                verified: true,
            },
            {
                name: 'public/bg.svg',
                realUsages: 0,
                status: 'dead',
                devUsages: 0,
                source: 'public/bg.svg',
                divergence:
                    "DEAD: 2.2KB file referenced NOWHERE in src (no '/bg.svg' URL, no import). Not to be confused with src/assets/bg/peanut-bg.svg (62KB) which the bg-peanut-repeat-* classes point at — and even those classes are dev-only. public/bg.svg is a truly orphaned asset — safe delete.",
                verified: true,
            },
        ],
    },
    {
        category: 'Button variants & ad-hoc buttons',
        layer: 'primitives',
        summary:
            'The Button primitive (src/components/0_Bruddle/Button.tsx) exposes 7 variant values, 3 sizes, 2 shape values, 4 shadowSizes and 2 shadowTypes. Of the 7 variants, 6 are live and one is fully dead: variant="dark" (btn-dark) has 0 usages anywhere — no product, no /dev showcase, no tests, no expression-based use. purple (54, also the default) and stroke (15) dominate; primary-soft (14) and transparent (11) are moderate; transparent-light (1) and transparent-dark (2) are marginal. On the knobs: shadowSize="4" is effectively the only shadow (113 real vs 2 for "3", zero for "6"/"8"), shadowType="secondary" is dead (0 real, 0 dev), and shape="square" is showcase-only (0 real, 1 dev). Separately, 7 ad-hoc <button> elements across 5 product files hand-roll bg-+rounded styling instead of using Button, with off-DS radii (rounded-full/rounded-lg vs DS rounded-sm) and gray hover colors (hover:bg-gray-*) — notably InvitesGraph which imports Button yet forks it 3x.',
        items: [
            {
                name: 'variant="purple"',
                realUsages: 54,
                status: 'live',
                devUsages: 13,
                source: 'src/components/0_Bruddle/Button.tsx (buttonVariants.purple -> btn-purple; also the default variant)',
                divergence:
                    "canonical primary CTA; also the implicit default (variant='purple' in props), so real render count exceeds the 54 explicit call-sites.",
                usedIn: [
                    'components/AddMoney/components/InputAmountStep.tsx',
                    'components/Profile/components/PublicProfile.tsx',
                    'components/AddMoney/components/MantecaDepositShareDetails.tsx',
                    'components/AddMoney/components/AddMoneyBankDetails.tsx',
                    'components/Home/ActivationCTAs.tsx',
                ],
            },
            {
                name: 'variant="dark"',
                realUsages: 0,
                status: 'dead',
                devUsages: 0,
                source: 'src/components/0_Bruddle/Button.tsx (buttonVariants.dark -> btn-dark)',
                divergence:
                    'DEAD: 0 usages in product, 0 in /dev showcase, 0 in tests, 0 via variant={} expression — delete-candidate variant + its btn-dark class.',
                verified: true,
            },
            {
                name: 'variant="stroke"',
                realUsages: 15,
                status: 'live',
                devUsages: 9,
                source: 'src/components/0_Bruddle/Button.tsx (buttonVariants.stroke -> btn-stroke)',
                divergence: 'canonical secondary CTA (outline); healthy live usage.',
                usedIn: [
                    'components/AddMoney/views/CryptoDeposit.view.tsx',
                    'components/Claim/Generic/ClaimError.view.tsx',
                    'components/Card/CardLimitsScreen.tsx',
                    'components/Card/BadgeSkipCelebration.tsx',
                    'components/Card/CardRejectionScreen.tsx',
                ],
            },
            {
                name: 'variant="primary-soft"',
                realUsages: 14,
                status: 'live',
                devUsages: 2,
                source: "src/components/0_Bruddle/Button.tsx (buttonVariants['primary-soft'] -> 'bg-white')",
                divergence:
                    "the only variant not backed by a btn-* class — its style is an inline 'bg-white' literal, unlike every other variant which maps to a named btn- utility.",
                usedIn: [
                    'components/Profile/index.tsx',
                    'components/Profile/components/ProfileHeader.tsx',
                    'components/Invites/InvitesPage.tsx',
                    'components/AddMoney/views/RhinoDeposit.view.tsx',
                    'components/AddMoney/components/AddMoneyBankDetails.tsx',
                ],
            },
            {
                name: 'variant="transparent"',
                realUsages: 11,
                status: 'live',
                devUsages: 1,
                source: 'src/components/0_Bruddle/Button.tsx (buttonVariants.transparent -> long inline bg-transparent/hover/focus/disabled chain)',
                divergence:
                    "like primary-soft, no btn- class — a raw utility string; also the only variant needing a special-case line in buttonClasses (variant==='transparent' && disabled) to patch disabled styling.",
                usedIn: [
                    'components/Claim/Link/Initial.view.tsx',
                    'components/SearchInput/index.tsx',
                    'components/Global/TokenSelector/TokenSelector.tsx',
                    'components/Global/LogoutButton/index.tsx',
                    'app/(mobile-ui)/withdraw/manteca/page.tsx',
                ],
            },
            {
                name: 'variant="transparent-dark"',
                realUsages: 2,
                status: 'live',
                devUsages: 0,
                source: "src/components/0_Bruddle/Button.tsx (buttonVariants['transparent-dark'] -> btn-transparent-dark)",
                divergence:
                    'marginal (2 sites) and, unlike its sibling transparent-light, not even in the /dev showcase (0 dev usages) — near-orphan, consolidation candidate with transparent.',
                usedIn: ['components/Badges/BadgesRow.tsx', 'components/Setup/components/SetupWrapper.tsx'],
            },
            {
                name: 'variant="transparent-light"',
                realUsages: 1,
                status: 'live',
                devUsages: 2,
                source: "src/components/0_Bruddle/Button.tsx (buttonVariants['transparent-light'] -> btn-transparent-light)",
                divergence:
                    'single real call-site (QRScanner); appears more in /dev (2) than in product (1) — barely-live, merge candidate with transparent/transparent-dark.',
                usedIn: ['components/Global/QRScanner/index.tsx'],
            },
            {
                name: 'size="large" (Button size)',
                realUsages: 2,
                status: 'variant',
                devUsages: 2,
                source: 'src/components/0_Bruddle/Button.tsx (buttonSizes.large -> btn-large; @deprecated in JSDoc)',
                divergence:
                    "JSDoc-@deprecated: 'large' is h-10 (40px), SHORTER than the default h-13 (52px) — a naming trap flagged in CLAUDE.md; only 2 real uses. (size= counts are prop-level, may include non-Button consumers.)",
            },
            {
                name: 'shadowType="secondary"',
                realUsages: 0,
                status: 'dead',
                devUsages: 0,
                source: 'src/components/0_Bruddle/Button.tsx (buttonShadows.secondary -> btn-shadow-secondary-{3,4,6,8})',
                divergence:
                    "DEAD: 0 real, 0 dev, 0 test. The entire buttonShadows.secondary sub-map (4 btn-shadow-secondary-* classes) is unreachable — only shadowType='primary' (the default) is ever selected.",
                verified: true,
            },
            {
                name: 'shadowSize="6" / shadowSize="8"',
                realUsages: 0,
                status: 'showcase-only',
                devUsages: 2,
                source: "src/components/0_Bruddle/Button.tsx (buttonShadows.primary['6'|'8'])",
                divergence:
                    "showcase-only: 0 product uses, only appear in /dev. Product shadows are effectively one value — shadowSize='4' has 113 real uses vs '3'=2 and '6'/'8'=0.",
                verified: true,
            },
            {
                name: 'shape="square"',
                realUsages: 0,
                status: 'showcase-only',
                devUsages: 1,
                source: "src/components/0_Bruddle/Button.tsx (shape==='square' -> btn-square)",
                divergence:
                    'showcase-only: 0 real product uses, appears once under /dev. The btn-square class is never rendered in the real product.',
                verified: true,
            },
            {
                name: 'Ad-hoc <button> with bg-+rounded (bypassing Button)',
                realUsages: 7,
                status: 'adhoc',
                devUsages: 0,
                source: 'inline lowercase <button> JSX elements in product code, not the 0_Bruddle Button primitive',
                divergence:
                    '7 hand-rolled <button bg-*...rounded-*> elements across 5 files use off-DS radii (rounded-full/rounded-lg/rounded vs DS rounded-sm) and gray hover colors (hover:bg-gray-50/100) instead of Button; InvitesGraph forks it 3x despite importing Button on line 35. (Of 57 total inline <button> product elements, 7 carry bg-+rounded styling and should be Button.)',
                usedIn: [
                    'components/Global/InvitesGraph/index.tsx',
                    'components/Global/QRScanner/index.tsx',
                    'components/Global/ExchangeRateWidget/index.tsx',
                    'components/Global/Carousel/index.tsx',
                    'app/[locale]/(marketing)/error.tsx',
                ],
            },
        ],
    },
    {
        category: 'Pills, Badges & Chips',
        layer: 'components',
        summary:
            'The design brief\'s "info pills in 5 variations" is real: there is ONE canonical token-based text pill (StatusBadge, 17 real usages) but at least 6 competing implementations of the same "small rounded status label" concept. StatusPill (icon-only, 7 uses) shares StatusType with StatusBadge but has drifted color tokens (pending = border-yellow-8 vs StatusBadge\'s border-yellow-7). Three ad-hoc families reimplement the SAME completed/pending/failed semantics with raw Tailwind-default palette (bg-green-100/bg-yellow-100/bg-gray-100) instead of design tokens: PerkRewardReceipt\'s status pill, the InvitesGraph debug pills, and the Quest badge pills — the latter via a byte-identical getBadgeColorClasses helper copy-pasted across QuestCard and QuestLeaderboard. ChainChip is a separate token-less "chip" built on Card. StatusTag is showcase/DS-audit only (0 product usages). Net: 1 canonical pill live, 1 divergent-token sibling live, 3 hard-coded-color duplicates live, 1 duplicated helper, 1 showcase-only. Consolidation target: fold PerkRewardReceipt + Quest pills into StatusBadge/customText and align StatusPill\'s color map to StatusBadge\'s.',
        items: [
            {
                name: 'StatusBadge',
                realUsages: 17,
                status: 'canonical',
                devUsages: 4,
                source: 'components/Global/Badges/StatusBadge.tsx',
                divergence:
                    'The canonical token-based text pill: rounded-full, size small/medium/large (px-2 py-0.5 text-[10px] → px-4 py-1.5 text-sm), color via design tokens (bg-success-2/text-success-4/border-success-5). All other pill implementations should collapse into this via status + customText; it already supports arbitrary labels through customText.',
                usedIn: [
                    'components/TransactionDetails/TransactionDetailsHeaderCard.tsx',
                    'components/Kyc/KYCStatusDrawerItem.tsx',
                    'components/LandingPage/CurrencySelect.tsx',
                    'components/Send/views/SendRouter.view.tsx',
                    'features/limits/views/LimitsPageView.tsx',
                ],
            },
            {
                name: 'StatusPill (icon dot)',
                realUsages: 7,
                status: 'variant',
                devUsages: 4,
                source: 'components/Global/StatusPill/index.tsx',
                divergence:
                    "Icon-only 14px rounded-full dot (size-[14px]) that reuses StatusBadge's StatusType but re-declares its own colorClasses map which has DRIFTED: pending/processing/soon use border-yellow-8 here vs border-yellow-7 in StatusBadge — same status renders a different border shade depending on which component drew it. Should import StatusBadge's color map, not fork it.",
                usedIn: [
                    'components/TransactionDetails/TransactionCard.tsx',
                    'components/Kyc/KycStatusItem.tsx',
                    'features/payments/flows/semantic-request/views/SemanticRequestReceiptView.tsx',
                    'features/payments/shared/components/PaymentSuccessView.tsx',
                    'utils/history.utils.ts',
                ],
            },
            {
                name: 'PerkRewardReceipt status pill (inline)',
                realUsages: 1,
                status: 'duplicate',
                devUsages: 0,
                source: 'components/TransactionDetails/provider-receipts/PerkRewardReceipt.tsx',
                divergence:
                    "Reimplements StatusBadge's exact completed/processing/fallback branch as three inline rounded-full spans with RAW Tailwind-default palette (bg-green-100/text-green-700, bg-yellow-100/text-yellow-700, bg-gray-100/text-gray-700) instead of design tokens, and padding px-3 py-1 text-xs (StatusBadge 'medium' is px-3 py-1 text-xs but token-colored). Pure duplicate of StatusBadge — should be <StatusBadge status={transaction.status} />.",
                usedIn: ['components/TransactionDetails/provider-receipts/PerkRewardReceipt.tsx'],
            },
            {
                name: 'Quest badge pill (getBadgeColorClasses)',
                realUsages: 2,
                status: 'duplicate',
                devUsages: 0,
                source: 'app/quests/components/QuestCard.tsx + app/quests/components/QuestLeaderboard.tsx',
                divergence:
                    'getBadgeColorClasses(color) is BYTE-IDENTICAL in both files (YELLOW/PINK/BLUE/default → bg-yellow-100 text-yellow-700 etc., raw Tailwind palette not tokens). Both render the pill inline with rounded-full px-1.5 py-0.5 text-[10px] md:px-2 md:text-xs. Copy-paste duplicate helper + hard-coded colors; extract one shared QuestBadge or map onto StatusBadge customText.',
                usedIn: ['app/quests/components/QuestCard.tsx', 'app/quests/components/QuestLeaderboard.tsx'],
            },
            {
                name: 'InvitesGraph stat pills (inline)',
                realUsages: 1,
                status: 'adhoc',
                devUsages: 0,
                source: 'components/Global/InvitesGraph/index.tsx',
                divergence:
                    'Debug/stat count pills: rounded-full bg-purple-100 text-purple-700 and bg-blue-100 text-blue-700, px-2 py-1, raw Tailwind palette, no shared component. Ad-hoc info pills unrelated to StatusBadge tokens; low-stakes (dev-ish graph overlay) but still a color-source divergence (Tailwind purple-100 vs Peanut primary tokens).',
                usedIn: ['components/Global/InvitesGraph/index.tsx'],
            },
            {
                name: 'ChainChip',
                realUsages: 5,
                status: 'live',
                devUsages: 1,
                source: 'components/AddMoney/components/ChainChip.tsx',
                divergence:
                    "A distinct 'chip' family (icon + chain name), built on 0_Bruddle/Card with rounded-full border-0 bg-transparent p-1 px-1.5, text-xs text-black. No status semantics, no token bg — it's a labeled logo chip, not a status pill. Legitimately separate from StatusBadge but is the only 'Chip' primitive, so any future chip work should standardize here.",
                usedIn: [
                    'components/AddMoney/views/CryptoDeposit.view.tsx',
                    'components/AddMoney/components/ChooseNetworkDrawer.tsx',
                    'components/AddMoney/components/SupportedNetworksModal.tsx',
                    'components/AddMoney/views/RhinoDeposit.view.tsx',
                    'components/Global/TokenAndNetworkConfirmationModal/index.tsx',
                ],
            },
            {
                name: "CardFace 'Virtual' pill (inline)",
                realUsages: 1,
                status: 'adhoc',
                devUsages: 0,
                source: 'components/Card/CardFace.tsx',
                divergence:
                    "Inline label pill rounded-full bg-white px-4 py-1.5 text-sm font-semibold (duplicated twice within the file for virtual/revealed states). Matches StatusBadge 'large' padding (px-4 py-1.5 text-sm) but hard-codes bg-white and skips the component — a one-off decorative pill on the card art, but padding/size is a candidate to reuse StatusBadge size='large' customText='Virtual'.",
                usedIn: ['components/Card/CardFace.tsx'],
            },
            {
                name: 'ExchangeRateWidget rate pill (inline)',
                realUsages: 1,
                status: 'adhoc',
                devUsages: 0,
                source: 'components/Global/ExchangeRateWidget/index.tsx',
                divergence:
                    "rounded-full bg-grey-4 px-2 py-[2px] text-xs font-bold text-gray-1 — uses a bespoke py-[2px] (arbitrary value) and text-gray-1 (note lowercase misleading name) rather than StatusBadge's px-2 py-0.5. Off-scale padding is the divergence; a small info pill that doesn't reuse the DS.",
                usedIn: ['components/Global/ExchangeRateWidget/index.tsx'],
            },
            {
                name: 'CardLandingPage feature/nav pills (inline)',
                realUsages: 1,
                status: 'adhoc',
                devUsages: 0,
                source: 'app/lp/card/CardLandingPage.tsx',
                divergence:
                    'Marketing landing pills in two styles within one file: (a) bg-primary-1 px-2 py-0.5 text-[10px] font-bold text-white badges, (b) border-2 border-n-1 bg-white px-4/px-5 py-1/py-2 text-sm font-bold nav/feature pills. border-2 (2px) diverges from the DS 1px border-n-1 rule and from StatusBadge (no border-2 variant). Landing-only styling, intentionally off-DS, but is a 5th+ distinct pill visual.',
                usedIn: ['app/lp/card/CardLandingPage.tsx'],
            },
            {
                name: 'StatusTag (DS audit)',
                realUsages: 0,
                status: 'showcase-only',
                devUsages: 7,
                source: 'app/(mobile-ui)/dev/ds/_components/StatusTag.tsx',
                divergence:
                    "production/limited/unused/needs-refactor audit tag: rounded-full px-2 py-0.5 text-[10px] font-bold with bg-*/30 opacity colors. Lives only under /dev/ds; used to label components in the design-system catalog. Never rendered in the real product — it's meta-tooling, not a product pill.",
                verified: true,
            },
        ],
    },
    {
        category: 'Tokens (defined vs used)',
        layer: 'tokens',
        summary:
            'The Tailwind config (/workspaces/sandbox/mono/peanut-ui/tailwind.config.js) defines ~90 color palette entries, exactly ONE custom border-radius (`rounded-1` = 0.0625rem), and a family of custom neo-brutalist shadow component-classes (`shadow-{2,4}`, `shadow-primary-{4,6,8}`, `shadow-secondary-{4,6,8}`, `btn-shadow-primary-{3,4,6,8}`, `btn-shadow-secondary-{3,4,6,8}`). Roughly a third of the color palette is DEAD or showcase-only. Fully dead (0 references anywhere, incl /dev): the entire `outline-{1,2,3}` group, both `primary-base`/`secondary-base` CSS-var aliases, `cyan-1`, `teal-3`, `kyc-red`, `kyc-green`, `secondary-5`, `green-2`, `purple-{2,4,5,6}`, and `yellow-{2,3,4,5}`. Showcase-only: `teal-1` (only in the `/dev` label demo) and the custom `rounded-1` radius (0 real, 1 dev). Live/heavily-used: `primary-1` (pink CTA), `grey-1` (secondary text, ~108 files), `n-1` (border black, ~70 files), `rounded-full` (103), `rounded-sm` (61), `yellow-1`/`secondary-1`, and `shadow-primary-4`/`btn-shadow-primary-4` — the latter reaches ~115 product call-sites through the Button `shadowSize` prop (only 6 as a literal class). The biggest divergence is that the config carries two parallel grey scales (`grey-*` AND `gray-*` AND `n-*`) and two pink aliases (`primary-1` == `purple-1` == #FF90E8), so "delete-dead + collapse-duplicates" would remove ~25 palette entries and one radius token.',
        items: [
            {
                name: 'color: outline-1 / outline-2 / outline-3',
                realUsages: 0,
                status: 'dead',
                devUsages: 0,
                source: 'tailwind.config.js:38-42',
                divergence:
                    'Whole outline color group (#98E9AB/#AE7AFF/#E99898) never referenced via any bg-/text-/border-/outline-/ring- utility anywhere in src (0 real, 0 dev). Pure delete candidate; the greens/purples duplicate green-1/purple-4 anyway.',
                verified: true,
            },
            {
                name: 'color: primary-base (var(--primary-color))',
                realUsages: 0,
                status: 'dead',
                devUsages: 0,
                source: 'tailwind.config.js:112',
                divergence:
                    'CSS-var alias token bg-primary-base/text-primary-base referenced 0 times; the --primary-color var itself is set in globals.css:34 but only the literal primary-1 (#FF90E8) is used in classes. Alias is orphaned.',
                verified: true,
            },
            {
                name: 'color: secondary-base (var(--secondary-color))',
                realUsages: 0,
                status: 'dead',
                devUsages: 0,
                source: 'tailwind.config.js:113',
                divergence:
                    'Same as primary-base: the var-backed alias utility is referenced 0 times in real or dev code; only the raw violet-3 (#6340DF) is used directly.',
                verified: true,
            },
            {
                name: 'color: kyc-red / kyc-green',
                realUsages: 0,
                status: 'dead',
                devUsages: 0,
                source: 'tailwind.config.js:108,110',
                divergence:
                    'bg-/text-kyc-red (#C80000) and kyc-green (#00C800) referenced 0 times. KYC status UI uses success-* and error-* instead; these two are orphaned one-offs.',
                verified: true,
            },
            {
                name: 'color: cyan-1 (#4CCCEF)',
                realUsages: 0,
                status: 'dead',
                devUsages: 0,
                source: 'tailwind.config.js:90-92',
                divergence: 'Single-entry cyan scale, 0 references anywhere. Delete candidate.',
                verified: true,
            },
            {
                name: 'color: teal-3 (#00577d)',
                realUsages: 0,
                status: 'dead',
                devUsages: 0,
                source: 'tailwind.config.js:71',
                divergence:
                    'teal-3 referenced 0 times (its sibling teal-1 exists only in the /dev label demo). Delete candidate.',
            },
            {
                name: 'color: teal-1 (#23A094)',
                realUsages: 0,
                status: 'showcase-only',
                devUsages: 3,
                source: 'tailwind.config.js:70',
                divergence:
                    'Only referenced via .label-teal/.label-stroke-teal component classes, and those classes render exclusively under /dev (3 dev files, 0 real). The teal label variant is defined in config (lines 484-491) but never shipped in product.',
                verified: true,
            },
            {
                name: 'color: purple-2 / purple-4 / purple-5 / purple-6',
                realUsages: 0,
                status: 'dead',
                devUsages: 0,
                source: 'tailwind.config.js:44-51',
                divergence:
                    "Config comments the whole purple group '// todo: remove these colors'. purple-2/4/5/6 have 0 references anywhere; only purple-1 (#FF90E8, duplicate of primary-1) and purple-3 survive. Duplicate palette slated for removal by its own comment.",
                verified: true,
            },
            {
                name: 'color: purple-1 (#FF90E8, == primary-1)',
                realUsages: 4,
                status: 'duplicate',
                devUsages: 9,
                source: 'tailwind.config.js:45',
                divergence:
                    'Exact hex duplicate of primary-1 (#FF90E8 pink). Only 4 real files still use purple-1 vs 60 for primary-1 — same color, two token names. Merge into primary-1 and delete (config already flags the purple group for removal).',
                usedIn: [
                    'components/PeanutRagdoll/index.tsx',
                    'components/Global/CancelSendLinkModal/index.tsx',
                    'hooks/useHomeCarouselCTAs.tsx',
                    'app/not-found.tsx',
                ],
            },
            {
                name: 'color: secondary-5 (#FBEAEA)',
                realUsages: 0,
                status: 'dead',
                devUsages: 0,
                source: 'tailwind.config.js:26',
                divergence:
                    'secondary-5 referenced 0 times (siblings secondary-1/3/6/7/8 are live). Orphaned pale-pink entry.',
                verified: true,
            },
            {
                name: 'color: green-2 (#EAFBEE)',
                realUsages: 0,
                status: 'dead',
                devUsages: 0,
                source: 'tailwind.config.js:67',
                divergence:
                    'green-2 pale mint referenced 0 times; green-1 itself is nearly dead too (1 real). Success states use success-2/success-6 instead.',
                verified: true,
            },
            {
                name: 'color: green-1 (#98E9AB)',
                realUsages: 1,
                status: 'live',
                devUsages: 10,
                source: 'tailwind.config.js:66',
                divergence:
                    "Duplicate hex of outline-1 (#98E9AB); appears in 10 /dev files vs 1 real. Effectively a showcase color — product greens come from success-*. Merge/delete candidate. [reclassified after verify: Real product usage in /workspaces/sandbox/mono/peanut-ui/src/app/m/[slug]/MerchantLandingPage.tsx:431 — `className={`inline-block h-2 w-2 rounded-full ${isLive ? 'bg-green-1' : 'bg-n-1'}`}` renders a live cripto-dolar rate status indicator dot. This is the customer-facing merchant landing route /m/[slug], NOT under /dev/ and NOT a test file. All other green-1 occurrences are confined to /dev/ showcase/audit pages (dev/components, dev/debug, dev/ds/audit, showcase-utils). The 'showcase-only' claim is wrong — green-1 has genuine product render usage.]",
                usedIn: ['components/Global/PaymentsFooter/MobileNavigation.tsx'],
                verified: true,
            },
            {
                name: 'color: yellow-2 / yellow-3 / yellow-4 / yellow-5',
                realUsages: 0,
                status: 'dead',
                devUsages: 0,
                source: 'tailwind.config.js:53-57',
                divergence:
                    'Four entries of the 11-slot yellow scale (#f5ff7c/#fbfdd8/#FAE8A4/#FFD25C) referenced 0 times. Scale is bloated: yellow-1 is heavily used, but 2-5 are dead.',
                verified: true,
            },
            {
                name: 'color: yellow-1 (#FFC900, == secondary-1)',
                realUsages: 26,
                status: 'duplicate',
                devUsages: 11,
                source: 'tailwind.config.js:53',
                divergence:
                    'Exact hex duplicate of secondary-1 (#FFC900). Both live (yellow-1=26, secondary-1=21 real). Two names for the brand yellow — consolidation candidate.',
                usedIn: [
                    'components/AddMoney/views/AddMoneyMethodSelection.view.tsx',
                    'components/AddMoney/views/RhinoDeposit.view.tsx',
                    'components/AddMoney/views/CryptoDeposit.view.tsx',
                    'components/Profile/views/UnlockedRegions.view.tsx',
                    'components/AddMoney/components/MantecaDepositShareDetails.tsx',
                ],
            },
            {
                name: 'color: primary-1 (#FF90E8, PINK)',
                realUsages: 60,
                status: 'live',
                devUsages: 7,
                source: 'tailwind.config.js:16',
                divergence:
                    'Canonical brand pink CTA color. Misleadingly named — has hex-identical alias purple-1 (see duplicate). Heavily live.',
                usedIn: [
                    'components/Slider/index.tsx',
                    'components/Profile/components/ProfileMenuItem.tsx',
                    'components/Profile/components/ShowNameToggle.tsx',
                    'components/Profile/components/ProfileEditField.tsx',
                    'components/AddMoney/views/RhinoDeposit.view.tsx',
                ],
            },
            {
                name: 'color: grey-1 (#5F646D, secondary text)',
                realUsages: 108,
                status: 'live',
                devUsages: 46,
                source: 'tailwind.config.js:33',
                divergence:
                    'Most-used non-black text color (secondary text per CLAUDE.md). Hex-identical to gray-1 and n-3 (#5F646D) — THREE token names for one grey. grey-1/gray-1/n-3 should collapse.',
                usedIn: [
                    'components/Profile/components/PublicProfile.tsx',
                    'components/Profile/components/ProfileEditField.tsx',
                    'components/AddMoney/views/RhinoDeposit.view.tsx',
                    'components/AddMoney/views/CryptoDeposit.view.tsx',
                    'components/AddMoney/components/SupportedNetworksModal.tsx',
                ],
            },
            {
                name: 'color: gray-1 (#5F646D, == grey-1 == n-3)',
                realUsages: 13,
                status: 'duplicate',
                devUsages: 2,
                source: 'tailwind.config.js:74',
                divergence:
                    "Third spelling of the same #5F646D grey (grey-1 uses 108 files, gray-1 13, n-3 shares the hex). gray-2..5 map to Tailwind's own default grays (#9CA3AF/#e5e7eb/#d1d5db) — gray-3/gray-4/gray-5 are 0 real. Redundant custom scale over Tailwind defaults.",
                usedIn: ['components/Global/MessageContainer/index.tsx', 'components/Setup/Views/SetupPasskey.tsx'],
            },
            {
                name: 'color: n-1 (#000000, brand black border)',
                realUsages: 70,
                status: 'live',
                devUsages: 36,
                source: 'tailwind.config.js:81',
                divergence:
                    'The neo-brutalist 1px black border/text token (border border-n-1 per CLAUDE.md). Hex-identical to black (#000000). Heavily live; consolidation with `black` is possible but n-1 is the DS convention.',
                usedIn: [
                    'components/Profile/index.tsx',
                    'components/AddMoney/views/CryptoDeposit.view.tsx',
                    'components/Global/ActionModal/index.tsx',
                    'components/0_Bruddle/Button.tsx',
                    'components/Slider/index.tsx',
                ],
            },
            {
                name: 'color: n-2 / n-3 / n-4 (dark-mode grey scale)',
                realUsages: 1,
                status: 'live',
                devUsages: 0,
                source: 'tailwind.config.js:82-84',
                divergence:
                    "Direct class usage is tiny (n-2/n-3/n-4 = 1/1/0 real files), but they ARE load-bearing via the config's own addBase/addComponents layer: body uses dark:bg-n-2, .btn uses disabled:bg-n-4, .input uses placeholder:text-n-3. So they're live-through-config, not dead — count reflects direct component references only.",
                usedIn: ['components/Global/ActionModal/index.tsx'],
            },
            {
                name: 'color: secondary-1 (#FFC900, brand yellow)',
                realUsages: 21,
                status: 'live',
                devUsages: 2,
                source: 'tailwind.config.js:22',
                divergence: 'Live brand yellow; hex-identical duplicate of yellow-1 (see duplicate entry).',
                usedIn: [
                    'components/AddMoney/views/AddMoneyMethodSelection.view.tsx',
                    'components/Profile/views/UnlockedRegions.view.tsx',
                    'components/AddMoney/views/RhinoDeposit.view.tsx',
                ],
            },
            {
                name: 'color: success-3 (#29CC6A) and success-* family',
                realUsages: 9,
                status: 'live',
                devUsages: 5,
                source: 'tailwind.config.js:97-105',
                divergence:
                    'success-1/2/3/4 live (success-3 highest at 9 real); success-6/success-7 are down to 1 real each — tail of the 7-slot scale is thin. Product success/positive states rely on this over green-*.',
                usedIn: [
                    'components/Global/MessageContainer/index.tsx',
                    'components/Profile/components/ProfileHeader.tsx',
                ],
            },
            {
                name: 'radius: rounded-1 (0.0625rem)',
                realUsages: 0,
                status: 'showcase-only',
                devUsages: 1,
                source: 'tailwind.config.js:247-249',
                divergence:
                    "The ONLY custom border-radius the config adds; referenced 0 times in product, once in /dev. CLAUDE.md mandates 'always rounded-sm', so this 1px radius is an unused DS artifact. Delete candidate.",
                verified: true,
            },
            {
                name: 'radius: rounded-full',
                realUsages: 103,
                status: 'live',
                devUsages: 16,
                source: 'tailwind default',
                divergence:
                    'Most-used radius (avatars, pills, badges). Tailwind default, not a custom token — heavily live.',
                usedIn: [
                    'components/Profile/AvatarWithBadge.tsx',
                    'components/Profile/components/ProfileMenuItem.tsx',
                    'components/Profile/components/PublicProfile.tsx',
                    'components/AddMoney/components/MantecaDepositShareDetails.tsx',
                    'components/Profile/views/UnlockedRegions.view.tsx',
                ],
            },
            {
                name: 'radius: rounded-sm',
                realUsages: 61,
                status: 'live',
                devUsages: 37,
                source: 'tailwind default',
                divergence:
                    "The mandated DS radius per CLAUDE.md ('Border radius: always rounded-sm'). Live. Coexists with rounded-md/lg/xl/2xl/3xl (all 2-8 real) which drift from the DS rule.",
                usedIn: [
                    'components/Slider/index.tsx',
                    'components/Invites/JoinWaitlistPage.tsx',
                    'components/Profile/index.tsx',
                    'components/Profile/components/ProfileEditField.tsx',
                    'components/AddMoney/views/CryptoDeposit.view.tsx',
                ],
            },
            {
                name: 'radius: rounded-{lg,xl,2xl,3xl}',
                realUsages: 18,
                status: 'variant',
                devUsages: 13,
                source: 'tailwind default',
                divergence:
                    "Off-spec radii (lg=6, xl=6, 2xl=4, 3xl=2 real) coexisting with the mandated rounded-sm — each is an ad-hoc deviation from the 'always rounded-sm' DS rule. Not tokens the config adds, but drift worth flagging.",
                usedIn: ['components/Global/InvitesGraph/index.tsx'],
            },
            {
                name: 'shadow: btn-shadow-primary-4 (via Button shadowSize)',
                realUsages: 115,
                status: 'live',
                devUsages: 1,
                source: 'tailwind.config.js:597-600 + components/0_Bruddle/Button.tsx:78',
                divergence:
                    "Direct literal-class count is only 6, but the class is applied to ~115 real product sites through the Button component's shadowSize prop ('4' -> btn-shadow-primary-4, the standard depth). This is the true canonical shadow; counting only literal classes massively undercounts it.",
                usedIn: [
                    'components/Invites/JoinWaitlistPage.tsx',
                    'components/Profile/index.tsx',
                    'components/Invites/InvitesPage.tsx',
                    'components/Profile/components/ProfileHeader.tsx',
                    'components/Profile/views/ProfileEdit.view.tsx',
                ],
            },
            {
                name: 'shadow: shadow-primary-4 / shadow-4 (neo-brutalist drop)',
                realUsages: 8,
                status: 'live',
                devUsages: 7,
                source: 'tailwind.config.js:557-563',
                divergence:
                    "shadow-4 (8 real) and shadow-primary-4 (6 real) are hex-identical ('.shadow-4' and '.shadow-primary-4' BOTH expand to shadow-[0.25rem_0.25rem_0_#000000]) — literal duplicate component classes. Merge candidate.",
                usedIn: ['components/0_Bruddle/Card.tsx', 'components/Global/ActionModal/index.tsx'],
            },
            {
                name: 'shadow: shadow-secondary-{4,6,8} & btn-shadow-secondary-{3,4,6,8}',
                realUsages: 2,
                status: 'variant',
                devUsages: 1,
                source: 'tailwind.config.js:572-582,608-621',
                divergence:
                    "The 'secondary' (upward, negative-Y) shadow family is barely used directly (2 real for shadow-secondary-*, 1 real each for the btn-shadow-secondary-* variants) — they only reach product when a caller passes shadowType='secondary' to Button, which is rare. Low-traffic mirror of the primary family.",
                usedIn: ['components/0_Bruddle/Button.tsx'],
            },
            {
                name: 'shadow: shadow-2 (0.125rem black)',
                realUsages: 1,
                status: 'live',
                devUsages: 3,
                source: 'tailwind.config.js:553-556',
                divergence:
                    "Thinnest custom drop shadow: 1 real file vs 3 /dev. Effectively a showcase depth; product standardizes on the 0.25rem shadow-4/shadow-primary-4. [reclassified after verify: Real product usage in shared Global component (NOT /dev/, NOT a test): /workspaces/sandbox/mono/peanut-ui/src/components/Global/TokenSelector/Components/NetworkButton.tsx:35 applies `shadow-2` in the Button className: 'shadow-2 flex h-fit min-w-14 flex-1 flex-col items-center justify-center gap-1 p-3 ...'. NetworkButton is not itself dead — it is imported and rendered twice by the TokenSelector: /workspaces/sandbox/mono/peanut-ui/src/components/Global/TokenSelector/TokenSelector.tsx:25 (import), and rendered at TokenSelector.tsx:416 and :430. So the shadow-2 token is live in the real product chain surface. The only other hits were /dev/components showcase, a shadow-2xl false-positive (different Tailwind class), and audit-data.ts (the audit's own data file). The 'showcase-only' claim is incorrect.]",
                usedIn: ['components/Global/Modal/index.tsx'],
                verified: true,
            },
        ],
    },
]
