name: Preview deploy
on:
    pull_request:
        branches:
            - peanut-wallet
            - peanut-wallet-dev

jobs:
    Deploy-Preview:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: 9
            - name: Install Vercel CLI
              run: pnpm add --global vercel@latest
            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
            - name: Build Project Artifacts
              run: vercel build --target=preview --token=${{ secrets.VERCEL_TOKEN }}
            - name: Deploy Project Artifacts to Vercel
              run: vercel deploy --prebuilt --target=preview --name=peanut-wallet --token=${{ secrets.VERCEL_TOKEN }}
